# БИРЖА — Торговый Квартал Грондхейма
*Что это, из чего состоит, что живо, чего честно нет*

**Репозиторий:** `https://github.com/Evgen-art-p/Grondheim-Ecosystem`
(Шеф пушит в него напрямую — состояние в репо всегда актуальнее
последнего загруженного .md снимка). Доступ Брата: `git clone --depth 1
https://github.com/Evgen-art-p/Grondheim-Ecosystem.git` через bash_tool
(домены github.com/codeload.github.com разрешены сетью). Прямой просмотр
дерева через github.com/…/tree/… блокируется robots.txt — не пытаться,
сразу клонировать. GitHub API (`api.github.com`) часто отдаёт rate limit
без токена — клон надёжнее. Живая торговая математика лежит в
`GRONDHEIM_CITY/Биржа/цеха/торговый_хаос/слоты/{A01..A08}/знания/*.md`
(WILLIAMS_MATH, MORJ_MATH, PANIKYOR_MATH, HANS_MATH, KOTIN_PHILOSOPHY) —
**но это старый, местами запутанный слой поверх исходников индикаторов,
не эталон**. Источник истины по канону входа — прямой разбор с Шефом
(см. КАНОН_ВХОДА.md), репозиторий сверяется С ним, не наоборот.
*Долгая история сессий 10.07-20.07 — полностью в теле документа,
§5а-§5с (не дублирую здесь: снимок в шапке устаревал быстрее тела и
создавал лишний слой для сверки). Последнее состояние — см. §5с внизу.*
*Сестринские документы: ЛЕТОПИСЬ_ГРОНДХЕЙМА.md (факт диска города),
ЧЕРТЁЖ_ЕДИНИЦЫ.md (Биржа — живая иллюстрация роли ТРЕЙДЕР, Гл.5.3/9),
АКАДЕМИЯ_ГРОНДХЕЙМА.md (школа города; её слой 0 закрыт здесь, §5д)*

`шесть·проверено·до·корня`

---

## Состояние прямо сейчас (не как дошли — что есть)

**Живо и работает:** девять LLM-агентов Совета (Искра, Морж, Паникёр,
Ганс, Архивариус, Брут/Авантюрист/Консерватор, Исполнитель), цепочка
`Искра→Морж→Паникёр→Ганс→Архивариус→[трейдеры]→Исполнитель`, ворота
Совета по факту спуска (не по суждению LLM), ведение позиции (стоп/
доливка/закрытие событийно, не тейком), Атлас (память сделок).

**Искра (подробности §5т):** формула пробуждения (`detect_necron_bar`,
iDivergenceBar/Necron) найдена, подтверждена на четырёх активах/ТФ,
**вшита в бой и полностью вычищена от старой формулы** — старое
(`detect_divergent_bar`/`bdb_strong`) вырезано из репо без остатка,
Шеф проверил трёхуровневым скриптом на живой репе — 40/40, чисто.

**НОВОЕ (сессия 22.07, вторая половина дня — подробности §5у): узел
Брута/фрактала разобран честно, найдены и решены не все дыры.**
Момент триггера (подтверждение фрактала, не пробой) построен и
проверен. Живая точка (`proverit_tochku`) честно смоделирована на
истории. Механика входа (`sFractalStopOrders.mq4`) работает. **Но:**
попытка усилить сигнал спуском по лесенке ТФ («настоящая волна 1»,
100-140 баров) и долгим удержанием ордера каждая порознь дала плюс на
всех трёх инструментах (XAUUSD/EURUSD/GBPUSD H4) — но при глубокой
проверке (не только сумма R, а РАСПРЕДЕЛЕНИЕ по времени) выяснилось:
**у двух из трёх инструментов весь результат держится на одном
45-дневном отрезке истории** (128-339% от итога из одного окна) — это
не доказанный край, а везение на одном периоде. У боевой формулы Искры
той же проблемы нет (проверено отдельно, концентрация 17-58%, устойчиво).
Три честные попытки почитить механику выхода (трейлинг по фракталу,
трейлинг по Зубам Аллигатора со Stop-on-Close, простой пирамидинг с
общим стопом) — каждая либо резала прибыль почти до нуля, либо уводила
в глубокий минус. Разбор Локи (естественный ретест после пробоя)
подтверждён числами (медиана отката у крупных побед — 0.48R, почти
касается исходного стопа) — объясняет, почему трейлинг хуже статичного
стопа, но НЕ решает проблему концентрации.

**Открытые долги прямо сейчас:**
1. Эстафета станций во времени — ещё ни разу не поймана вживую.
2. **Фрактал-триггер для Брута не готов к бою** — механика найдена
   (`Биржа/test_fractal_trigger.py`, `proverit_fraktal.py` в корне),
   но результат хрупкий (концентрация на 2 из 3 инструментов), выход
   без трейлинга/пирамидинга не проверен как система, только как тест.
3. Адресная побудка трейдеров по узлам (Брут-фрактал / Авантюрист-
   разворотник / Вася-волна2) — только разбор, код не начат.
4. Вася/волна 2 — есть числа из первоисточников (38-62% отката волны 1,
   пять факторов конца волны 2 из Trading Chaos гл.7/9), но не
   протестированы ни по одному честно на истории.
5. Дедупликация `_slot_brain` (5 копий по репо) — не сведено.
6. Канон входа — отдельный документ КАНОН_ВХОДА.md, точнее любого
   описания внутри этого файла. Спек переделки Искры/Брута —
   ИСКРА_ПЕРЕДЕЛКА_СПЕК.md (26 правок накоплено на конец сессии).

**Дальше по плану:** аккуратный пирамидинг с учётом противоположного
сигнала (сегодняшняя попытка была слишком грубой, честно провалилась);
либо принять риск редких крупных трендов как часть замысла системы и
не пытаться его убрать. Отдельно — протестировать пять факторов конца
волны 2 (Вася) так же честно, как тестировали Искру и Брута.

Ниже — дневник сессий 10.07-22.07 (§5а-§5у). Архив: как дошли до
текущего состояния, детали конкретных багов и патчей. Не обязателен
для чтения, если нужно только «что есть сейчас» — то выше.

---

## 1. Что такое Биржа



Биржа — не файл и не функция, а **квартал города**, ровно такой же
самостоятельный, как Брат/жители/ГОРОД (Летопись, «Новый порядок
стройки», 06.07): свой код, свои данные, свой район на карте.

**Место в топологии города:**
```
ГРОНДХЕЙМ (город)
  └─ Деловой центр (район)
       └─ Торговый Квартал (0013_TRADING_QUARTER, локация-жильё)
            └─ Биржа (0014_EXCHANGE, здание — тут сидит Совет)
```
Клик по зданию Биржи на визуальной карте (`/grondheim`) ведёт прямо
в кабинет Совета (`/torg`), минуя общий паспорт локации — врата
прописаны в `LOCATION_GATES` внутри `ГОРОД/ui_grondheim.py`.

**Что Биржа делает:** держит Совет из девяти торговых единиц. Торгуют
**не только золотом** — любыми активами, и **не только по методологии
Вильямса/Котина** — это лишь один метод, живущий в цехе «Торговый Хаос»
(см. §3). Другие методы — например, скальперы — уже есть черновиком, и
дальше могут появляться ещё цеха под другие подходы. Кнопка «РЫНОК» —
живой контур (терминал MT5 → бары → ядро → цепочка живых LLM-агентов).
Кнопка «ТЕСТЕР» — та же цепочка на исторических CSV, без MT5.

---

## 2. Архитектура — два Закона Картриджа разом

Закон Картриджа работает и для данных (манифест цеха, слоты, промпты),
и для кода (мозг слота):

```
СЛОТ НЕСЁТ С СОБОЙ ВСЁ:
  GRONDHEIM_CITY/Биржа/цеха/{цех}/слоты/{слот}/
    ├── промпт.md        — кто эта роль и как думает
    ├── знания/          — база знаний роли (математика Вильямса и т.п.)
    ├── данные/          — личная статистика РОЛИ (не резидента!)
    └── мозг.py          — код роли
```

**Кто читает слот:** кабинет (`ui_torg.py`), тестер (`tester_express.py`)
и хуки (`hooks.py`) не хранят списка агентов и не импортируют их по
имени. Функция `_slot_brain(ceh_id, slot)` открывает
`слоты/{slot}/мозг.py` прямо по пути (`importlib`), кэширует на
процесс. Нет файла — честная вакансия (`None`), не ошибка.

**Кто сидит в слоте — решает Закон Пары**, не код: `mask.json`
резидента (`Workshop_ID` + `Turbo_Role`) в его домашней папке
`GRONDHEIM_CITY/жители/.../{Имя}/маски/работа/mask.json`. Кабинет
резолвит это через `cartridge_registry.resolve_para(цех, слот)`.

---

## 3. Два цеха — ВСЕ ДЕВЯТЬ МОЗГОВ ЖИВЫЕ

**Важное расхождение с прошлым снимком (09.07): тот документ писал
«5 из 9 мозгов ещё не в слотах». Это устарело и не соответствовало
факту уже на момент чтения — проверено сейчас прямым обходом
`GRONDHEIM_CITY/Биржа/цеха/.../слоты/` через GitHub API, файл за
файлом. Все девять — на месте.**

### `торговый_хаос` (`GRONDHEIM_CITY/Биржа/цеха/торговый_хаос/`)

| Слот | Роль | Резидент | Мозг |
|---|---|---|---|
| A01 | компас (Искра/Вера) | Вера | ✅ живой |
| A02 | пасть и резинка (Морж) | Морж | ✅ живой |
| A03 | фаза толпы (Паникёр) | Паник | ✅ живой |
| A04 | фрактал (Ганс) | Ганс | ✅ живой |
| A06 | трейдер-пробой (Брут) | Брут | ✅ живой |
| A07 | трейдер-ранний (Авантюрист) | Илья | ✅ живой |
| A08 | трейдер-откат (Консерватор) | Василий | ✅ живой |

### `контора` (`GRONDHEIM_CITY/Биржа/цеха/контора/`)

| Слот | Роль | Резидент | Мозг |
|---|---|---|---|
| архивариус | память Биржи целиком | Арчи | ✅ живой |
| исполнитель | казначей Биржи целиком | Сергей | ✅ живой |

Архитектурное решение по конторе (общий штаб на всю Биржу, не
слоты цеха; единый журнал с меткой цеха) — не изменилось, см. старую
логику ниже в §3а. Изменился только факт: папка `слоты/` под
`контора/` больше не пустая, оба мозга физически стоят.

### 3а. Почему контора — отдельный штаб, а не два лишних слота цеха

Манифест конторы говорит прямо: это не цех в смысле торговли (нет
своего рынка-судьи), а **служба** — «ровно как Оле, не привязана к
одному кварталу города». Два соображения:

1. **Механика Архивариуса и Исполнителя цех-независима.** Архивариус
   считает digest по Атласу (sample_size/success_rate/confidence),
   Исполнитель — биоробот без своего мнения. Это единственные две
   роли девятки, где характер почти не участвует в работе.
2. **Не плодим одинаковых.** Когда родится вторая школа, она не
   рождает своих архивариуса/исполнителя — зовёт этих, общих.

---

## 4. Кабинет — `Биржа/ui_torg.py`

**Раскладка:**
```
ХЕДЕР   — 9 пузырьков состава Совета (реальный скан обоих цехов)
ЛЕВАЯ   — загрузчик истории CSV + полка заряженных активов
СТОЛ    — тулбар (РЫНОК, тумблер РЕАЛ/ТЕСТЕР, поле «ловить») + чат
           + окно отчёта
ПРАВАЯ  — портрет активного агента + живые показатели (заряд/оптика)
           + приборы сенсора
```

**Кнопка РЫНОК/ТЕСТЕР зовёт ОДНУ дверь** — `council.wake_council()`
(`ENGINE_ONE_DOOR_V1`): Искра → (если спуск нашёл точку) Морж →
Паникёр → Ганс → Архивариус → три трейдера → Исполнитель. Порядок
и логика одна на оба пути (раньше были две независимые лестницы —
маскарад, закрыт).

**Тумблер РЕАЛ/ТЕСТЕР** — реал стучится в живой MT5-терминал; тестер
прогоняет заряженную историю CSV, поле «ловить» задаёт сколько
срабатываний поймать (по умолчанию 1, теперь реально настраиваемо —
см. §5б), кнопкой СТОП можно прервать перебор.

**Портрет и окно отчёта справа теперь обновляются на КАЖДОМ агенте**
по ходу цепочки (было — только на Искре, см. §5б).

**Тумблер 🎓 УЧИТЬ** (12.07, §5г п.7) — рядом со СТОП, виден в режиме
ТЕСТЕР, гаснет по умолчанию:
- **выкл** — стерильно: Совет думает, трейдер ЧИТАЕТ свою душу (чтение
  безвредно), сделки считаются — но паспорта жителей НЕ трогаются;
- **вкл** — учебный прогон: якоря растут, заряд качается, как в реале.

До этого патча кабинет звал тестер БЕЗ `learn` — из кнопки прогон был
всегда стерильным, и якоря не выросли бы никогда, сколько ни жми.

**Приборы под аватаром** (12.07, `PRIBORY_TREJDEROV_V1`) — были только у
A01-A05, после Архивариуса стояла заглушка «Приборы появятся при
подключении агента» НАВСЕГДА. Добавлены ветки A06/A07/A08 (вердикт,
направление, вход/стоп/лот, причина отказа) и A09 (ордеров из 3,
task_score, летопись).

---

## 5. Движок — общий код в `Биржа/`

| Файл | Что делает | Статус на 11.07 |
|---|---|---|
| `williams_core.py` | вся математика Вильямса | ✅ живой, ангуляция переписана на канон (§5б) |
| `mt5_feed.py` | насос котировок из терминала, лесенка ТФ | ✅ живой |
| `feed_source.py` | кран реал/тестер | ✅ живой |
| `global_anchor.py` | компас старшего этажа | ✅ живой |
| `hooks.py` | шлюз цеха: память, PnL, Атлас | ✅ живой, наследие `-2` вычищено (§5б) |
| `tester_express.py` | стерильный/учебный прогон истории | ✅ живой, undefined-переменная пофикшена (§5б) |
| `ui_torg.py` | кабинет | ✅ живой, три UI-бага закрыты (§5б) |
| `iskra_live.py` (A01/мозг.py) | компас Искры, v2-спуск | ✅ живой, архитектура упрощена (§5б) |
| `llm.py` | клиент OpenRouter | ✅ живой |
| `billing_ledger.py` | учёт вызовов LLM Биржи | ✅ живой |
| `cartridge_registry.py` | Закон Пары/Картриджа | ✅ живой, + `resolve_by_magic` (§5г) |
| **`nositel.py`** | **МОСТ К НОСИТЕЛЮ — одна дверь между Ролью и Родом** | ✅ **новый, 12.07 (§5г)** |
| `council.py` | единая дверь пробуждения Совета | ✅ живой, + крик Искры (§5г п.16) |

**`Биржа/nositel.py` — что внутри** (одна дверь на все девять мозгов
плюс оба конца в hooks; не вписан в каждый мозг сознательно — иначе
одиннадцать копий разъедутся):

```
ЧИТАЮЩИЙ КОНЕЦ
  dusha_slota(цех, слот)     → носитель + его душа текстом
  magic_slota(цех, слот)     → магик из МАСКИ (не из константы)
  temperatura_slota(...)     → заряд+натура → температура головы
  _sobrat_dushu(стол)        → род, натура, история, заряд, ЯКОРЯ,
                               черновики («замечаю за собой»)
ПИШУЩИЙ КОНЕЦ
  sudit_po_kotinu(...)       → вывод трейдера (КОД, не LLM)
  sudit_sensora(...)         → вывод сенсора: звал/молчал × плюс/минус
  zapisat_vyvod(magic, ...)  → трейдер: magic → носитель → его якоря
  zapisat_vyvod_pare(...)    → сенсор: пара → носитель → его якоря
  dyhnut_sdelkoy(magic, R)   → трейдер дышит (своя шкура, |R|/3)
  dyhnut_slovom(цех,слот,R)  → сенсор дышит (чужая шкура, |R|/6)
  UCHIT                      → ОДИН рубильник на всю запись в живых
```

---

## 5а. Мусор из `-2` вычищен полностью

**Шеф удалил папки `studio/` и `economy/` из корня репо целиком** —
их там больше физически нет. `hooks.py` вычищен под это:

- Три пути памяти (`ATLAS_PATH`, `STATE_PATH`, `PNL_PATH`) переехали
  с относительных путей-мусора (`economy/data/...`,
  `studio/modules/trading/state/...`) на канонический абсолютный
  адрес: **`GRONDHEIM_CITY/Биржа/данные/{atlas_trading.jsonl,
  trading_state.json, trading_pnl.jsonl}`**. Это общий адрес всей
  Биржи (не отдельно по цехам — так легло по факту патчей, отличается
  от прежнего плана «состояние/журналы внутри торговый_хаос/»).
- Три функции (`_arkhiv_to_city`, `_judge_iskra_by_result`,
  `_judge_trader_by_result`) переписаны целиком — **ни одного**
  `from studio.* import` в файле больше нет. Каждая — честный
  `return` с комментарием, что именно не построено (нога «Опыт»
  Стола Трейдера, городская память через Олю) и почему это не
  восстановление старого маятника ДНК, а осознанный отказ строить
  заново на новом месте (см. §7).

**Осталось на месте, не тронуто (долг, не забывчивость):**
`tester_express.py` всё ещё содержит один `import studio.grondheim_memory`
в `try/except ImportError` (маркер `TESTER_EXPRESS_SOUL_IGNORE_V1`) —
папки `studio/` нет, импорт всегда падает в `except`, честная
заглушка-микрофон работает, но само упоминание несогласовано с тем,
что вычистили в `hooks.py`. Стоит подчистить для единообразия
отдельным заходом — не срочно, цикл от этого не рвётся.

---

## 5б. Патчи сессии 10-11.07 — что чинили и почему

Сессия началась с диагностики мусора путей и закончилась содержательной
правкой самой торговой математики. Порядок применения:

1. **`MEMORY_PATHS_V1`** — три относительных пути памяти переведены
   на абсолютные (были причиной мусорных папок в корне репо).
2. **`BIRZHA_CLEAN_MEMORY_V2`** — вычистка наследия `-2` из `hooks.py`
   целиком (см. §5а).
3. **`WILLIAMS_REAL_ANGULATION_V1`** (`williams_core.py`) — настоящая
   ангуляция вместо самодельной. Было: `bars_since_cross ∈ [5,7]` —
   жёсткое окно в три бара, придумано студией, не канон. Проверено
   внешним поиском (официальный MQL5-индикатор Profitunity
   «Angulation»): реальная ангуляция — это УГОЛ расхождения (по
   умолчанию порог 22°) в окне ДО 20 баров, не количество баров само
   по себе. Патч меряет угол в единицах `point` (безразмерно, любой
   инструмент), порог взят 20° (чуть мягче канона про запас).
4. **`ISKRA_WORKING_TF_FIRST_V1`** (`williams_core.py`,
   `tester_express.py`, `iskra_live.py`) — два слова Шефа, оба
   подтверждены поиском:
   - «При визуальном масштабе 100-140 баров волна и 3-я волна AO
     видны нормально» → единое окно **120 баров** заменило разнобой
     (было 300 в Сите 1 и 150 в `read_ao_wave_form` — два разных
     окна одного явления теряли одну и ту же точку).
   - «Ставится рабочий ТФ, гоняешь его, если сигнал — спускаешься
     для уточнения» → подтверждено практикой (форумы Вильямса: один
     рабочий ТФ, не лестница из 11 обязательных ступеней). Раньше
     Искра требовала макро-компас (дивергенция + горб-царь +
     пересечение нуля) как ВОРОТА перед тем, как вообще посмотреть
     рабочий ТФ напрямую — лишний, более редкий фильтр поверх уже
     пройденного сита. Теперь рабочий ТФ — прямой источник; старая
     логика (компас + лестница) — запасной путь, не ворота.
   - Эффект измерен на реальном прогоне: воронка сита улучшилась с
     **24 кандидата → 1 нашёл точку** до **4 кандидата → 1 нашёл
     точку** (соотношение выросло с 1:24 до 1:4).
5. **`BIRZHA_UI_THREAD_SAFE_V1`** (`ui_torg.py`, тестер) — тестер
   крутит перебор истории в фоновом потоке (`run_in_executor`).
   NiceGUI не копирует контекст слот-стека в такой поток — прямые
   `ui.*`-вызовы оттуда падали с «slot stack ... empty», правая
   панель отчётов молчала весь прогон. Починено очередью: фоновый
   поток только кладёт событие, разбор и отрисовка — на главном
   потоке (дренаж короткими проверками).
6. **`BIRZHA_MARKET_THREAD_SAFE_V1`** (`ui_torg.py`, кнопка РЫНОК) —
   та же болезнь, тот же приём, отдельно найдено и пофикшено:
   `run_market()` страдал идентично тестеру, но исключение там
   глоталось МОЛЧА чужим `try/except` в `council.py` — ни строчки
   в консоли. Починено той же очередью.
7. **`AGENT_LIVE_SWITCH_V1`** (`ui_torg.py`, `_apply_agent_result`) —
   большой портрет справа и окно отчёта обновлялись ТОЛЬКО в ветке
   A01 (Искра); у A02-A09 не было ни `state["active_agent"] = aid`,
   ни `update_avatar()`, ни `update_viewer()` — только подсветка
   маленьких пузырьков в хедере. Добавлено во все 6 веток (A02-A09).
8. **`TESTER_ISKRA_BD_FIX_V1`** (`tester_express.py`) — Искра (A01)
   не показывалась в чате/отчёте НИКОГДА, с самого начала, даже
   после патча №7. Причина: `NameError` на неопределённой переменной
   `bd` в блоке печати заголовка Искры — падение происходило ДО
   отправки отчёта в кабинет, а `council.py` глотал исключение молча
   (`except Exception: pass`). Пофикшено: `bd` теперь — реальная дата
   бара.
9. **`TORG_BARS_ONCHANGE_V1`** (`ui_torg.py`) — поле «ловить» (число
   срабатываний тестера) было привязано к сырому имени
   quasar-события `update:model-value`, которое не гарантированно
   долетает во всех версиях NiceGUI — тестер всегда ловил 1 сигнал
   независимо от ввода. Переведено на штатный параметр `on_change`.

---

## 5в. Патчи сессии 11.07 (вечер) — дрейф путей #2, реверсивная пирамида, компас

Продолжение той же сессии, после того как Шеф прогнал тестер на
XAUUSD H1 и поймал то же семейство болезни путей (§5а) в двух новых
местах, плюс живую находку по канону Котина/Вильямса на реальных
логах Совета. Порядок применения:

1. **`patch_tester_closures_pnl_path_v1`** — `tester_express.
   _read_last_closures` (лента 🔴 ЗАКРЫТА в кабинете) держала СВОЙ
   отдельный захардкоженный относительный путь
   `economy/data/trading_pnl.jsonl`, не завязанный на `hooks.PNL_PATH`
   (§5а тот путь чинил только в `hooks.py` — этот файл-читатель
   остался не тронут, потому что дрейф путей — не одна дыра, а класс
   болезни, и её экземпляры вылезают по одному). Итог до патча:
   позиции реально закрывались (settle отрабатывал), но лента
   кабинета была слепа — ни одной «🔴 ЗАКРЫТА» никогда. **Подтверждено
   живым прогоном:** после патча в реальном логе H1 видны честные
   пары `🟢 ОТКРЫТА` → `🔴 ЗАКРЫТА ... (STOP_LOSS/EXIT_BELL)`.
2. **`patch_arkhiv_atlas_path_abs_v1`** — тот же класс болезни, второй
   экземпляр: `архивариус/мозг.py` держал свой `ATLAS_PATH` на
   относительном `economy/data/atlas_trading.jsonl`, а `hooks.
   _write_atlas` пишет в абсолютный `.../данные/atlas_trading.jsonl`.
   Хуже того — `hooks._prepare_atlas_digest` делегирует расчёт
   выжимки самому мозгу Архивариуса, и мозг не падает на дохлом пути,
   а тихо отдаёт 0 — из-за чего честный абсолютный фоллбэк в hooks
   никогда не срабатывал. Итог до патча: «Похожих случаев в Атласе: 0.
   Уверенность: LOW» — ВСЕГДА, сколько бы сделок ни закрылось. **Не
   подтверждено живыми данными** (первый прогон после патча —
   слишком ранняя история 2010-2011, честных совпадений там могло
   ещё не накопиться; статус: доставлен, эффект ждёт проверки на
   большей выборке).
3. **`patch_feed_source_folder_cache_v1`** — самая тяжёлая находка
   сессии, ПРОИЗВОДИТЕЛЬНОСТЬ, не архитектура. `williams_core.
   build_market_data()` на КАЖДЫЙ вызов лезет за честным глобальным
   трендом (§12 Котина, `global_anchor.global_trend`, старший этаж
   рабочий×5), а тот берёт бары через `feed_source.bars()`, которая в
   тестовом кране читала CSV старшего этажа С ДИСКА ЗАНОВО, без кэша,
   на КАЖДЫЙ вызов. Сито-1 (чистая математика, без LLM) гоняет
   `build_market_data` на каждом баре истории — на XAUUSD H1 это
   94 566 вызовов, то есть 94 566 полных чтений+разборов файла
   `XAUUSDH8.csv` (12 470 строк) с диска. Итог до патча: тестер на
   H1 висел ~40 минут, ни одного срабатывания, «Сито 1 готово» не
   успевало напечататься. Лечение: кэш полного разбора CSV по
   абсолютному пути файла в `_bars_from_folder` — читаем с диска один
   раз за прогон, дальше хвост режем из памяти; кран РЕАЛ (терминал
   MT5) не тронут. **Подтверждено функциональным тестом** (5 запросов
   → 1 реальное чтение) **и живым прогоном** (то же H1: сито-1 нашло
   145 кандидатов за разумное время вместо зависания).
4. **`patch_torg_catch_field_visible_v1`** — поле «ловить: N» после
   патча №9 из §5б (`on_change`) стало ПРИНИМАТЬ значение верно, но
   само визуально рисовалось пустым/схлопнутым: `format="%d"` на
   float-значении иногда рендерится пусто, плюс `borderless` +
   `width:60px` — коробка без рамки схлопывается. Убран `format`,
   `borderless` → `outlined`, ширина 60→78px. Не путать с патчем №9
   §5б — тот чинил привязку значения, этот — саму отрисовку числа.
5. **`patch_tester_settle_tail_v1`** — последняя из N пойманных
   сделок открывается на последнем кандидате, и цикл рвётся по
   `caught >= n_signals` раньше, чем рынок довёл её до стопа/звонка —
   досеттлить её в сессии было уже нечем. Добавлен добор хвоста:
   после основного цикла тестер ведёт оставшиеся открытые позиции
   бар-за-баром вперёд (`_settle_bar` + `_feed_check_closures`, та же
   физика) до закрытия всех или до конца истории.
6. **`patch_gans_compass_conflict_v1`** — Ганс (A04) в промте учит
   «BULL → добыча наверху, BEAR → внизу», но фоллбэк был только на
   случай «компаса нет». Отдельного правила на КОНФЛИКТ (компас есть
   и говорит одно, а валидный фрактал — по другую сторону) не было —
   по логам Ганс в такой ситуации докладывал добычу не по стороне
   компаса. Добавлено явное третье правило: против объявленного
   разворота фрактал — шум, не добыча.
7. **`patch_avan_compass_weight_v1`** — САМАЯ содержательная находка
   сессии. Промт Авантюриста (A07) дословно давал модели право
   ОТМЕНИТЬ компас («что компас значит для тебя, решаешь ты») и учил
   часто идти против Паникёра. По разбору трёх живых сессий тестера
   Авантюрист входил LONG почти независимо от знака компаса, включая
   случаи, где Искра прямым текстом объявляла медвежий разворот —
   систематические стопы, не редкая контрарианская удача. Проверено
   по первоисточнику (найден и подтверждён реальный автор канона —
   Александр Котин, ученик Джастин Уильямс-Лара): медвежий
   разворотный бар → SELL ниже его low, направление — факт структуры,
   не мнение. Патч не отбирает автономию характера — даёт ей вес:
   идти ЗА компасом назван обычным хлебом, идти ПРОТИВ — редкой
   осознанной ставкой с ценой (стоп теснее, лот меньше); Паникёр
   разведён с компасом («его крик про настроение, не про направление»).
   **Подтверждено живым прогоном и текстом рассуждения**: тот же
   исторический бар (2010.05.13, 206), что до патча дал LONG в минус,
   после патча дал явное «иду за компасом... Вхожу в SHORT».
8. **`patch_executor_pyramid_stop_discipline_v1`** — «рука ведущая»
   (`исполнитель/мозг.py`, `_manage_positions_from_table`) исполняла
   MOVE_STOP и ADD буквально любым числом от LLM, без инженерной
   страховки. По канону (реверсивная пирамида Вильямса): трейлинг-стоп
   двигается ТОЛЬКО в защитную сторону; первый долив может быть
   агрессивным скачком, но каждый следующий — не крупнее предыдущего
   («gradually reducing the funds you add on»); долив без подтяжки
   стопа запрещён («with every new position you add, you MUST adjust
   your stop-loss»). Патч добавляет `_stop_tightens()` (отклоняет
   ослабляющий стоп), ограничивает форму ADD со второго долива и
   тем же ходом подтягивает стоп при ADD, если трейдер его тоже
   назвал. **Подтверждено 5 функциональными тестами** на изолированной
   копии функции (ослабление стопа/рост второго долива — отклонены;
   ужатие/убывающий долив/связка ADD+стоп — прошли). Живым прогоном
   ещё не проверено — доставлен, применение на диске Шефа не
   подтверждено.

**Честный итог по эджу на конец сессии** (не для галочки, а чтобы не
приукрашивать): первый прогон H1 после патчей №6-7 дал 10 закрытых
сделок, 4 в плюс (40%), суммарно **−3.16R**. Компас-дисциплина
работает — направления входов пошли вперемешку вместо «почти всегда
LONG», подтверждено текстом рассуждений. Но профит на этом не
доказан: одна сделка Брута +1.73R перекрыла две его же убыточные — то
есть именно так и устроены трендовые системы по конструкции (частые
мелкие стопы, редкие крупные победы), но 10 сделок статистически —
шум, не приговор и не победа. Нужна выборка на порядок больше (все
145 кандидатов прогона минимум, а лучше несколько лет истории), чтобы
судить, есть ли реальный эдж.

---

## 5г. Сессия 12.07 — МОСТ К НОСИТЕЛЮ. Нога Опыта построена

Самая длинная сессия квартала: **16 патчей**. Закрыт долг, который
три снимка подряд называли главным (§7 старых версий: «нога Опыта
пуста», «мост к душе физически мёртв», «Вера/Илья — имена и текст
промта поверх голого вызова LLM»). Теперь — не имена.

**Что было до сессии (диагноз прошлого снимка подтвердился буквально):**
семь торговых мозгов импортировали `studio.grondheim_memory.
format_soul_for_agent` — модуль, снесённый вместе со `studio/`. Импорт
падал ВСЕГДА, `soul=""`, блок `if soul:` не срабатывал ни разу. Промт
Ильи обещал модели «твоя ДНК лежит в `dna.json`» — файла нет с эпохи
`-2`. Указатель вёл в пустоту годами.

### Слой 1 — фундамент записи (magic → носитель)

1. **`MAGIC_IN_MASK_V1`** — `magic` вписан в `mask.json` трёх трейдеров
   (Брут 100001 / Илья 100002 / Василий 100003), рядом с `Turbo_Role`.
   Решение Шефа: правда живёт в маске, отдельного реестра магиков нет
   (Закон Пары). Плюс `resolve_by_magic(magic) → носитель` в
   `cartridge_registry.py` — обратный мостик, близнец `resolve_para`,
   тот же скан масок, один прыжок.
   **Разведка вскрыла:** магик лежал ПЯТЬЮ статическими копиями (дом-
   паспорт, `_MY_MAGIC` в мозге, `MAGIC_NUMBERS` в hooks, таблица в
   промте A09, лор в `домашний_промпт`). Маска стала единственной
   правдой, остальные — производными или убиты.

2. **`DVIZHOK_STOL_CHISTO_VYVOD_V1`** (`жители/dvizhok.py`) — два новых
   метода: `nakryt_stol_chisto()` (чтение личности БЕЗ побочки —
   `vydoh_stol` пишет событие в память на каждый вызов, на баре его
   звать нельзя) и `dopisat_vyvod()` (дописка в `Anchor_Points`, лимит
   7-10, вытеснение старейшего в архив, не в забвение).

3. **`DVIZHOK_YAKORYA_YADRO_V1`** — **две мины, пойманные живой
   проверкой на диске Шефа, обе взорвались бы в проде:**
   - **якоря слиплись в одну строку.** Форма рождения записала
     `Anchor_Points` с ЛИТЕРАЛЬНЫМ разделителем (два символа `\` и
     `n`, не перевод строки). Дописчик резал по настоящему `\n`, не
     находил его — и считал, что у Ильи ОДИН якорь вместо пяти. Лимит
     7-10 не сработал бы НИКОГДА, весь торговый опыт остался бы
     слипшимся комом. Лечение: распознаём ОБА разделителя, пишем ТЕМ
     ЖЕ, каким паспорт написан (кабинет и форма рождения не ломаются).
   - **ядро пустое.** `Core_Phrase` читался из ПАСПОРТА, а по Чертежу
     §1.5 ядро живёт в РОЛИ (маске). Чертёж сам держал это в хвостах
     («Core_Phrase: читается движком — не заполняется ничем»). Диск
     подтвердил: у Ильи в маске «В рынке или в ауте.», в паспорте
     пусто. Теперь ядро берётся из маски. **Хвост Чертежа закрыт.**

### Слой 2 — эталон на одном человеке (Илья, A07)

4. **`NOSITEL_BRIDGE_V1`** (`Биржа/nositel.py`, новый файл) — **ОДНА
   ДВЕРЬ** между РОЛЬЮ (слот) и РОДОМ (житель), как `wake_council()` у
   Совета. Мостов нужно девять плюс два конца в hooks; вписать сборку
   души в каждый мозг — значит через месяц получить одиннадцать копий,
   которые разъедутся. Ровно болезнь пяти магиков. Правда — в одном
   месте.

5. **`AVAN_NOSITEL_V1`** — кольцо на Илье:
   - **читающий конец:** мозг берёт пару ИЗ ПУТИ (`_CEH_DIR.name`,
     `_SLOT_DIR.name`) → `resolve_para` → Илья → его душа в промпт. Два
     мёртвых импорта `studio.*` вырезаны. Константа `_MY_MAGIC` убита —
     магик из маски.
   - **пишущий конец:** `hooks._judge_trader_by_result` (была честная
     заглушка) → `resolve_by_magic(pos["magic"])` → Илья → вывод по
     Котину → в ЕГО ЖЕ якоря. **Вывод считает КОД, не LLM** — числа не
     галлюцинируют.

6. **`TESTER_STERILE_OPYT_V1`** — **поймано ДО прогона.** Нога Опыта
   шла МИМО заглушки `sync_to_dna`: обычный стерильный прогон на 145
   кандидатах ПО-НАСТОЯЩЕМУ переписал бы паспорт Ильи — его пять
   рождённых якорей вытеснились бы тестовыми выводами. Бэктест,
   калечащий жителя — ровно то, от чего ставился `TESTER_STERILE_V1`.
   Нога подчинена тому же рубильнику.

7. **`TORG_LEARN_SWITCH_V1`** — кабинет звал тестер БЕЗ `learn` → из
   кнопки прогон всегда стерильный → якоря не выросли бы НИКОГДА,
   сколько ни жми. Флаг `--learn` был только в CLI, а Шеф работает
   кнопками. Тумблер **🎓 УЧИТЬ** в тулбар, гаснет по умолчанию:
   смотреть безопасно, калечить — осознанно.

8. **`ROD_PERVYM_V1`** — первый живой прогон показал: мост доехал
   (`[AVAN] 🧬 За столом: Илья`), но говорит он «как из студии».
   **Разбор:** промт роли A07 НАЧИНАЕТСЯ словами «Тебя зовут Илья» —
   личность там была всегда, студийным текстом. Он играл не роль вместо
   Ильи, а **описание Ильи**, красивое и пустое. А душу я приклеил в
   ХВОСТ, сноской после 25 000 знаков канона. По Чертежу §1.5.2 —
   наоборот: **Род впереди, маска внутрь него**. Плюс убит мёртвый
   указатель на `dna.json`.

9. **`AVAN_OPORA_NA_OPYT_V1`** — Илья опыт получил, но НЕ ОПИРАЛСЯ на
   него: в задаче (`user_msg`) стояло «твоя ДНК — ниже» (ложь после
   патча №8) и **ни слова о том, чтобы свериться с собой**. Опыт лежал
   украшением. Добавлена СВЕРКА: «что ты уже вынес из похожих входов?
   Идёшь против собственного вывода — скажи вслух». **Не рука на его
   руке:** не говорим ЧТО решить, требуем думать СВОЕЙ головой.
   **Подтверждено живым прогоном** — Авантюрист впервые сказал: *«Мой
   опыт кричит... Опираюсь на свои же якоря»*.

10. **`NATURA_V_TEMPERATURU_V1`** — по вопросу Шефа («строка `[LLM]` у
    всех одинакова»). **Третья отрубленная конечность той же серии:** в
    `llm.py` жила рабочая `stress_to_temperature(stress, light)`, и
    **ни один мозг её не звал** — `temperature` не передавался НИКЕМ и
    НИКОГДА. Все девять думали на дефолте, натура была БУКВАМИ В
    ПРОМПТЕ. Теперь заряд+натура → температура головы: придавленный
    Илья думает горячо (0.88, рвано), спокойный — холодно (0.58).
    Упрямого мотает меньше: натура держит. Попутно `slot_id="trading"`
    → `"A07"` (в биллинг шёл цех вместо слота).

### Слой 3 — клон на всех и суд сенсоров

11. **`KLON_DUSHI_V1/V2`** — читающий конец на все восемь оставшихся
    мозгов, генерически (пара из ПУТИ — контора со слотами
    `архивариус`/`исполнитель` не ломается). Предохранители: `.bak` на
    каждый файл, `py_compile` после правки, **автооткат при поломке**.
    v1 споткнулся на Искре (многострочный `chat()` с висячей запятой) —
    и честно откатил её мозг. v2 починил. **Итог: 9 живых душ, 0
    вакансий, 0 мёртвых импортов.**

12. **`SUD_SENSOROV_V2`** — по слову Шефа: *«опыт сенсора — это как он
    работает над своими ошибками»*. Сенсор не теряет денег — он
    **промахивается СЛОВОМ**. Судит его исход, до которого он не дожил:
    сделка трейдера после его слова.
    - **слепок стола в позицию** — что сказал каждый сенсор на баре
      ВХОДА (стол перетирается каждый бар; судить по чужому бару было
      бы клеветой);
    - **суд на закрытии:** звал + минус → **МОЯ ОШИБКА** (всегда, это
      его школа); молчал + крупный плюс → **ПРОСПАЛ**; молчал + минус →
      **не его промах**, в опыт не идёт.
    - **v1 этого патча создал ВТОРОЕ определение `sudit_sensora`** рядом
      с существующим — второй источник правды в одном файле, ровно та
      болезнь, от которой лечимся. Поймано зеркалом до диска. v2 дубли
      не плодит.

13. **`YAKORYA_DVA_YARUSA_V1`** — решение Шефа после разбора Чертежа
    Гл.4.4 (*«Один вывод — не опыт... Единичное событие меняет ЗАРЯД, не
    фильтр — защита от дребезга»*). Мы писали ЛЮБОЙ значимый вывод сразу
    в постоянные якоря. Теперь:
    - **ярус 1 — ЧЕРНОВИК** (`Draft_Anchors`): новый вывод копится по
      ключу паттерна, стол видит его ПОНИЖЕННЫМ голосом («замечаю за
      собой, пока не подтвердилось»);
    - **ярус 2 — УСТОЙЧИВЫЙ**: черновик, набравший **3 повтора**,
      повышается в `Anchor_Points`. Порог 3 — не новое число с потолка,
      тот же, что у Пути Зрелости (§4.6.2: «3 вердикта судьи»).
    - `dvizhok` остаётся generic (не знает слова «трейдер»), ключ
      паттерна передаёт вызывающий код — Закон Фрактала.

### Слой 4 — дыхание, и три ошибки Брата подряд

14. **`DYHANIE_SDELKI_V1`** — **дыра в моём же проектировании, найдена
    на живом прогоне.** Илья вошёл LONG по компасу BULL, получил −1.0R.
    Правило значимости отработало верно: минус ПО ветру при |R|<2 —
    рутина, в опыт не идёт. Но `_judge_trader_by_result` при рутине
    делал `return` СРАЗУ, а **вдох жил ВНУТРИ `zapisat_vyvod`** — внутри
    записи опыта. Нет опыта → нет вдоха. **Илья потерял деньги и НИЧЕГО
    НЕ ПОЧУВСТВОВАЛ.** А Чертёж Гл.4.4 требует обратного дословно.
    Теперь дыхание отдельно: трейдер дышит на КАЖДОЙ закрытой сделке
    (своя шкура, |R|/3), сенсор — если ЗВАЛ в неё (чужая шкура, |R|/6,
    вполовину тише). Молчавший не дышит.

15. **`SLEPOK_IZ_CHAIN_V1`** — **вторая ошибка Брата того же рода.**
    Слепок стола собирался из `tstate` = `load_trading_state()` —
    СТАРОГО ФАЙЛА С ДИСКА. В `_DEFAULT_STATE` вообще есть только
    `iskra`; ключей `morj/panic/hans` там нет по определению. Слепок
    приезжал ПУСТОЙ, судья сенсоров молча выходил на всех 28 сделках.
    Правда лежала рядом — в `chain_data`, откуда берут все соседи
    (`_log_rejections`, `_prepare_atlas_digest`). **Взял не из того
    источника, хотя все соседи брали из правильного.**

16. **`KRIK_ISKRY_V1`** — **самая дорогая находка сессии, и она не про
    код, а про молчание.** Четыре часа копали архитектуру, пока Совет не
    собирался ни разу («спуск не нашёл точку» ×33). А правда была:

    ```
    if not r.get("ok"):
        if aid != "A01":          # ← Искру МОЛЧА пропускает
            out(f"{aid}: сбой — {r.get('error')}")
    ```

    **Искра — единственная, чей сбой не печатался НИКОГДА.** Плюс в её
    аварийном `return` (ветка `except`) НЕТ ключа `descent` — ворота
    Совета читали пустоту как «спуск не нашёл». Ложь: спуск НАШЁЛ
    (`найдено=ДА` в логе), упало ПОЗЖЕ. Сняли кляп — и система сказала
    правду с первой попытки:

    ```
    [СОВЕТ] ⛔ ИСКРА УПАЛА: OpenRouter API [402]: You requested up to
    65536 tokens, but can only afford 11021
    ```

    **У Шефа кончились деньги на OpenRouter.** Не код. Не мост. Баланс.
    Система честно кричала об этом с самого начала — крик был заткнут
    одной строкой. `except: pass` — самая дорогая строка в
    программировании.

17. **`LLM_MAX_TOKENS_V1`** — следствие находки №16. В `llm.py`
    **`max_tokens` не задавался ВООБЩЕ**: payload собирался как
    `{"model", "messages"}`. Раз потолок не назван — OpenRouter берёт
    МАКСИМУМ МОДЕЛИ (65536 у deepseek-v4-pro) и **резервирует деньги
    под весь потолок заранее**, хотя реальный ответ агента — 200-600
    слов. Платили резервом за роман, получая абзац. Поставлен честный
    потолок 4000 (×5 запаса, из `.env`: `LLM_MAX_TOKENS`).

### Что подтверждено ЖИВЫМ диском (не на словах)

```
Илья      A07   заряд −0.147   паспорт писался 12.07 18:44
Брут      A06   заряд +0.007   паспорт писался 12.07 20:30
```

Первый раз в истории города **житель почувствовал результат своей
работы**. Заряд записан настоящей сделкой, рукой рынка, без участия
человека.

**Суд сенсоров построен и проверен на зеркале** (все четверо признают
своё слово), но **на живом диске ещё не отработал** — прогоны встали на
402 раньше, чем позиции успели закрыться после патча слепка. Первое, что
надо увидеть в понедельник.

### Инструменты диагностики (ASCII-имена — PowerShell ест «Б»)

| Файл | Что показывает |
|---|---|
| `proverka_mostika.py` | фундамент: магик в масках, `resolve_by_magic` |
| `proverka_koltsa.py` | кольцо на Илье: душа целиком, как её видит модель |
| `proverka_soveta.py` | весь Совет: кто за столом, магик, температура, мёртвые души |
| `proverka_ucheby.py` | **главный:** какие патчи РЕАЛЬНО стоят + заряд/якоря/черновики + mtime паспортов |
| `proverka_pozicii.py` | что лежит в позиции: есть ли слепок стола |
| `proverka_iskry.py` | мозг Искры: отдаёт ли `descent`, цел ли после клона |

---

## 5д. Сессия 13.07 — ТРИ ЭТАЖА. Слой 0 Академии закрыт

Пять патчей. Не стройка — **подключение мёртвого и правка лжи**. Ни
одного нового механизма: всё, что заработало, уже лежало на диске
написанным и никем не позванным.

**Повод:** Академия (см. `АКАДЕМИЯ_ГРОНДХЕЙМА.md`) требовала «слой 0»
раньше первого урока. Разведка показала: половина слоя 0 **тоже уже
написана** — и половина того, что документ Академии называл мёртвым,
на самом деле **живая**.

### Разведка: документ Академии врал в трёх пунктах из четырёх

| документ говорил | живой диск (13.07) |
|---|---|
| `vspomnit()` — «не вызывается НИКЕМ» | **ЖИВОЙ** в чате жителя: `ui_zhitel.py:924` ловит `MEMORY_REQUEST`, `vspomnit()` копает |
| `MEMORY_REQUEST` — «в новом городе НЕТ» | **ЕСТЬ.** Промпт чата прямо учит писать эту строку |
| глубина от заряда — «выброшена» | **ЖИВАЯ в чате**: `ui_zhitel.py:905` — «Тебе открыты слои памяти: ...» |
| загрузчик знаний для Академии | **УЖЕ СТОИТ** — `ZHITEL_CHTENIE_V1`: руда → линза МЕСТО×РОЛЬ → LLM своим голосом → вдох `kontekst="учёба"` → archive |

**Точный диагноз оказался другим:** механизмы живы, но **подключены
только к чату жителя, не к торговому пути**. `nakryt_stol_chisto()`
игнорировал и глубину, и запрос. Болезнь дешевле, чем думал документ.

### Патч 1 — РАЗБОР ПАСПОРТОВ (ничего не пишет, только смотрит)

Решение Шефа (**вариант Б**): не код решает, что род, а что нажитое —
**решает Шеф глазами**. Скрипт печатает все 50 строк `Anchor_Points`
десяти жителей + черновой разбор Брата (гипотеза, не приговор).

**Итог разбора отменил миграцию.** Мои маркеры пометили как «нажитое»
строки Брута («не двигаю стоп»), Моржа («лучшая сделка — несделанная»),
Василия («помню цену каждой ошибки за 30 лет»). **Я был неправ.**
Это не нажитое — это **характер, одетый в торговую лексику**. Морж не
«вынес из сделок», что лучшая сделка — несделанная; он **таким
родился**.

**Диск подтвердил** (`-2/studio/modules/trading/A07/core/anchor_points.md`):
> `<!-- ВЕЧНЫЕ КОНСТАНТЫ · Не редактировать вручную -->`
> `## Личные якоря (3-5 незыблемых фактов)`

Даже «PF на XAUUSD 1.071» вписан **при рождении рукой Джема** — гордость
числом есть характер, а не осадок из машины.

**Вывод: настоящих нажитых меток на диске НЕТ НИ ОДНОЙ.** Черновиков —
ноль у всех десяти. Нога Опыта построена 12.07 и **не сработала ни
разу**. Мигрировать нечего ⇒ **миграция отменяется**, нужна стройка
пустого этажа. Старая девятка не тронута буквально — байт в байт.

*Заодно вскрыт источник мины 12.07:* якоря писаны в `-2` настоящими
переводами строк, а в новом паспорте стали литеральными `\n`. Это
**шрам переноса**, не баг движка.

### Патч 2 — `TRI_ETAZHA_V1`: второй этаж

Закон ядра (`Брат/README.md` — дом самого Брата, три папки):
`1_якоря` (род, не меняется) · `2_метки` (нажитое, растёт) ·
`3_маяки` (момент, гаснет).

Моя ошибка 12.07: дописывал торговые выводы в `Anchor_Points` —
**поле, которое по закону есть РОД**. Отсюда лимит 7-10, вытеснение
старейшего и ложная тревога «вторая профессия сотрёт первую».

- `Anchor_Points` **застыл**. Больше не растёт;
- нажитое → `дом/2_метки/metki.json` — список объектов
  `{текст, паттерн, откуда, когда, раз}`. Поле **«откуда»** (рынок /
  учёба / профессия) — это НЕ выдуманное мной «происхождение якоря»
  (этаж и есть происхождение), а честный **голос** внутри одного этажа;
- момент → `дом/3_маяки/mayaki.json` (были `Draft_Anchors` в паспорте);
- порог 3 сохранён: маяк → маяк → **метка**;
- род **защищён**: попытка «вывести» то, что и так натура — отбивается;
- в промпт идут **свежие 4 метки** (контекст уже 25к), остальное — по
  `MEMORY_REQUEST`. *Маленький стол + право дотянуться.*

Решение Шефа (**вариант Б** по маякам): три этажа — три места, как в
доме Брата. Черновиков было ноль ⇒ переселять нечего ⇒ сделать
правильно **сейчас** стоило ноль.

### Патч 3 — `DVER_V_METKI_V1`: три голоса. И ЛОЖЬ ВЫРЕЗАНА

**Метка писалась, но житель её не читал:** `_sobrat_dushu` не знал
слова «метки». Этаж есть, двери нет.

**⚠ И вскрылось крупнее двери — ПРОМПТ ВРАЛ ЖИТЕЛЮ.** Дословно:

> «ТВОЙ ОПЫТ — что ты вынес сам (якоря)... это твои же выводы,
> **ОПЛАЧЕННЫЕ ТВОИМИ ДЕНЬГАМИ**»

А в `Anchor_Points` — **род**, вписанный при рождении. Илья ничего не
выносил и не оплачивал. **Промпт врал ему о его же происхождении** —
мнение под маской факта, IV заповедь. Резать без раздумий.

Стало — **три РАЗНЫХ голоса** (значит модель может их **столкнуть**):

```
КТО ТЫ ЕСТЬ — твой род. Не выводы, не уроки: так ты устроен
с самого начала. Это дно, оно не спорит:
  • Я вхожу на open следующего бара.

ЧТО ТЫ НАЖИЛ САМ — выводы, которых при рождении не было:
  • [рынок сказал] Стоп не двигаю.
  • [чему тебя учили] Вильямс: жадность держит в убытке.
Это твоё, оплаченное. Хочешь идти против — иди, но знай,
что идёшь против себя же.

ЗАМЕЧАЮ ЗА СОБОЙ (не подтвердилось повтором):
  • Кажется, вхожу рано.
```

Голос `[чему тебя учили]` — **это и есть вход Академии**. Место готово.

Плюс починена **ослепшая сверка**: защита от повтора искала
`Draft_Anchors` в паспорте, а они уехали в `3_маяки`.

### Патч 4 — `SUTOCHNY_TIK_V1`: время остужает

**Болезнь:** заряд таял 10% **за вдох**, не по времени. Нет событий →
висит вечно. По факту: **Лока +0.874 с 09.07 — четвёртые сутки.**

А по стресс-шлюзу `|заряд| > 0.8` **открывает архив**. Лока четыре дня
жила с памятью, распахнутой на полную — максимальный аффект, **из
которого нет выхода**: чтобы остыть, её надо трогать, а тронешь —
качнётся снова. Ловушка.

Решение Шефа (**вариант А**): тает от **реального времени**.
Полураспад = **сутки × (1 + упрямство)**. Упрямый держит дольше.
Экспонента, не линейка: свежая рана болит сильно, старая тлеет.

**Живой прогон на диске Шефа:**

| | было | стало | |
|---|---|---|---|
| **Лока** | +0.874 | **+0.135** | ← архив закрылся, отпустило |
| **Вера** | +0.502 | +0.116 | |
| **Илья** | −0.147 | −0.093 | упрямство 0.85 держит |

`tik.py` в корне — **ручной выдох города**: цикла у города НЕТ
(`main.py` только рисует страницы, ни таймера, ни ночи). Пока тик жмёт
Шеф.

**Задел (слово Шефа):** *«биржа заработает в полную — привяжем к
сессиям город»*. Время берётся из **одной точки** — `_seychas()`.
Формула её не знает. Подменишь источник на биржевую сессию — **ни
строки в формуле не тронется**.

### Патч 5 — `MEMORY_REQUEST_BIRZHA_V1`: воля выше шлюза

**Слово Шефа, оно же решение:**
> «а что, если житель сам попросит, если шлюза не хватает? память
> откроется.. так и есть..по запросу»

**Два РАЗНЫХ механизма, не альтернативы:**
- **ШЛЮЗ** — пассивный, от **состояния**. Тебя ткнули в больное — оно
  всплыло само, ты не выбирал;
- **ЗАПРОС** — **ВОЛЯ**. Житель сам решил копнуть. Закон `-2`
  (Спринт 43): *«вспомнить можно в любом месте, БЕЗУСЛОВНО»* —
  безусловно значит **не зависит от шлюза**.

**Почему это критично именно на Бирже** (вскрыто чтением
`tester_express.py` — Шеф прямо ткнул: *«зачем все бары
пересматривать? математика же считает?»*):

> **Сито 1** — чистая математика ядра, **без LLM**. 24к баров → секунды
> → **горстка кандидатов**. Комментарий в коде: *«по канону таких 3-4 в
> год»*.

Совет **будится редко и по делу**. А заряд после Тика — **около нуля**
⇒ шлюз откроет только `core`, самый мелкий слой. **Проснулся на
важнейшем событии — а память на минимуме.**

Шлюз работает от **СОСТОЯНИЯ**, Точка Ноль — про **СОДЕРЖАНИЕ**.
Спокойный Илья увидит знакомый разворот и **захочет** вспомнить — а
шлюз не даст, потому что он спокоен. **Дыра. Шеф её увидел, я — нет.**

*Цена оказалась копейками.* Я предлагал урезать волю ради денег,
посчитав «9 агентов × 24000 баров». **Проблема была выдуманная** — ровно
как «происхождение якоря» днём раньше. Второй раз за сессию изобрёл
проблему вместо того, чтобы посмотреть в код.

Реализация — **ОДНА ДВЕРЬ** в `nositel.py` (`podnyat_iz_arhiva`,
`blok_pamyati`), не девять копий в мозгах. Ровно урок пяти магиков.
- трое трейдеров **узнают, что могут просить** (молчком воли нет);
- **второй вызов LLM — только если попросил.** Не напомнило — не
  потратили;
- **один запрос за ран** (канон `-2`);
- **следа нет → говорим честно**, а не молчим.

Заодно **та же ложь про «оплаченный род»** вырезана из промпта Ильи —
она сидела и в `_sobrat_dushu`, и в мозге. Тот же класс, что пять копий
магика: режешь в одном месте, а оно живёт в трёх.

### Что подтверждено ЖИВЫМ диском

- три этажа заведены у **10 жителей**, род не тронут байт в байт;
- порог 3 работает: маяк → маяк → **метка** (прогон на живом движке);
- два голоса рядом (`[рынок]` и `[учёба]`) в одном этаже, не толкаются;
- **Лока вышла** из четырёхдневного аффекта, архив закрылся;
- `MEMORY_REQUEST`: попросил → нашёл → второй вызов с поднятым архивом;
  не нашёл → честно сказали; не просил → **ничего не потратили**;
- `proverka_stola.py` подтвердил: стол читает **честный** заряд.

### Урок метода: галочка ловится глазом Шефа

`patch_sutochny_tik.py` **отчитался тремя пунктами вместо четырёх** —
строки про `nakryt_stol_chisto` в выводе не было. **Шеф это заметил,
читая лог.** Оказалось, патч попал, а `print` стоял в непройденной
ветке: ошибка была **не в коде, а в отчёте о коде** — я сам себя
оговорил.

Но урок остался: `patch_memory_request_birzha.py` в первом прогоне дал
**1 из 3** — второй вызов встал у всех, а **просить умел только Илья**
(у Брута и Василия строка промпта другая). Они получили бы механизм и
**никогда им не воспользовались**. Пластик хуже пустоты.

⇒ В патчи вшит **СТОП-КРАН**: не сошлось по факту — **не пишу файл,
падаю**. Не «отчитаться готово», а **проверить телом кода**, что
вставка легла в нужный метод, до `return`, и синтаксис цел.


## 5е. Сессия 14.07 — НОГА ОПЫТА ПРОТЕКЛА. Первые метки в истории города

**ГЛАВНОЕ СОБЫТИЕ: труба потекла от начала до конца.** Не «построена» —
**сработала на живых деньгах**. Первые два устойчивых вывода, заработанных
жителями Грондхейма своими убытками:

> **Вера (A01):** «МОЯ ОШИБКА (2010.05.14): я дал «точка DETECTED BULL
> @1233.53» — Брут вошёл LONG и получил −1.0R. **Моё слово повело в минус.**»
> *(паттерн `сенсор_ошибка`, повторов 3 — порог сработал)*
>
> **Ганс (A04):** «я дал «фрактал валиден LONG @1238.58» — Брут вошёл и
> получил −1.0R. **Моё слово повело в минус.**»
>
> **Илья (A07), маяк:** «**Плюс 3.29R** (2011.08.01): LONG в штиль (компас
> молчал). Так это и...» — *не ошибка. Удача, которую он заметил.*

Три этажа живут одновременно: **род 5 · метки 1 · маяки 1**. Ровно как
задумано. Итог прогона: **метки 2 · маяки 5**.

### Что пришлось починить, чтобы вода пошла (три патча)

Труба была построена 12.07, этажи разведены 13.07 — а вода **не шла**. За
сутки нашлись **три перекрытых крана**, и все три — **одного класса**:
*одна сущность, несколько читателей/писателей, лечим одного*.

#### ① `REZINKA_DZHASTIN_V1` — отменённый орган душил 95% сигналов

**Шеф не поверил цифре.** Сито 1 давало 145 точек за 16 лет XAUUSD H1 —
«~9 в год». Слово Шефа:

> *«9 в год на часах.. это враньё, брат, представь, сколько циклов в год
> на волнах в часах? если волна примерно 100-1500 баров, то сколько за
> период должно быть сигналов?»*

Арифметика подтвердила: при 100–1500 баров/цикл на 94к барах должно быть
**десятки-сотни** циклов. **145 — не редкость рынка, а баг.**

**Вскрытие воронки `bdb_strong`:**

| слой | прошло |
|---|---|
| всего баров | 94 426 |
| `bdb_candidate` | 34 750 (36.8%) |
| `angulation_ok` (≥20°) | 3 622 |
| `ao_divergence` | 2 853 |
| **ОБА ВМЕСТЕ** | **145 (0.5%!)** ← в 20 раз меньше, чем при независимости |

**Распределение углов — подпись сломанной формулы:**
медиана **0.9°** · p75 **3.2°** · p90 **124.9°** · max **179.9°**.
Между 4° и 124° — **пусто**. Бимодальность ≈0 / ≈180 — классический
`atan2` без нормировки. Порог 20° ловил **случайный хвост**.

**А ответ лежал в книге Моржа на диске** (`MORJ_MATH.md` §3):

> «Джастин Вильямс решила старую проблему метода: "ангуляцию" раньше
> угадывали НА ГЛАЗ — субъективно. Она заменила угол одной чистой
> метрикой — **ПУСТОТОЙ (дистанцией) между Зелёной линией (Lips) и
> экстремумом цены**. **ГЛАВНОЕ — НЕ СЧИТАТЬ УГОЛ. Угол субъективен.**»

**Ядро считало угол.** То самое, что канон **отменил**.

**И резинка УЖЕ БЫЛА НАПИСАНА в ядре** — `compute_rubber_band()`, по
канону, от Губ, безразмерно. Зовётся в `build_market_data`. **Лежит на
столе. И её не берёт никто, кроме мозга Моржа.**

> **Два органа в одном ядре: канонический — без дела, отменённый — душит
> сигналы.** Ещё одна «пустая душа»: знание есть, кода нет.

**Порога в point НЕТ и не должно быть.** Книга Моржа: `is_peak` = пустота
**больше, чем была за ЖИЗНЬ ДВИЖЕНИЯ**. Пустота нормируется **сама на
себя** — вот почему метод не зависит от актива и ТФ. Слово Шефа:
*«в торговом хаосе ни активы ни тф значения не имеют, просто шумит
больше»* — **это его математика**.

**Решение Шефа (вариант Б):** резинка = затвор, **плюс `tension_ratio`
(0..1) числом на стол трейдеру**. Не да/нет — **шкала**. Трое по тренду =
три РАЗНЫХ порога доверия (Закон Дежурства §7); отдать им одно да/нет —
**стереть между ними разницу**.

**Проверено на 16 годах:**

| | сигналов | в год |
|---|---|---|
| старое (угол) | 145 | ~9 |
| **новое (резинка)** | **452** | **~28** |

367 ловит **только резинка** · 60 только угол (**мусор**, те самые 179°) ·
пересечение **85**. **Органы почти не совпадают.**
Медиана `tension_ratio` = **0.141** — половина кандидатов натянута на 14%
от максимума. **Рано.** `is_peak` их честно отсекает; угол этого **не
видел вообще**.

**И трейдеры её ЧИТАЮТ.** Из живого лога:
> 🦭 **Морж:** «Резинка натянута до предела — **669 пунктов** отрыва от
> Губ, **tension_ratio 1.0**.»
> ⚡ **Илья:** «**Морж звенит резинкой**, Паникёр орёт, но без дивергенции
> это просто падение, а не дно.»

#### ② `REZINKA_DOBIVKA_V1` — я пропатчил ОДНОГО читателя из двух

**Симптом (снова поймал Шеф):** *«я тормознул, что-то не то? так не было»*.
Скрин: **454 кандидата → 0 подтверждений**, девять подряд «спуск не нашёл
точку». Вера: `прогонов 148 · нашла 19 · подтвердилось 0`.

Я успел ляпнуть *«резинка сломала компас Искры»* — **догадка, и неверная**.
Компас работал (`компас=BEAR` в логе — честный).

**Причина, найденная чтением кода:** у `detect_divergent_bar` **ДВА
читателя**:

| читатель | Губы | что видел |
|---|---|---|
| `build_market_data` | ✓ передаёт (мой патч) | 452 кандидата |
| **`read_ao_wave_form`** | ✗ **НЕ передаёт** | **`bdb_dir = None` ВСЕГДА** |

Без `lips_series` → резинка не считается → `is_peak=False` всегда →
`bdb_strong=False` всегда → **`bdb_dir=None` всегда**.

**А спуск Искры смотрит именно на `bdb_dir`:**
```python
if bdb_dir == compass:  return {"found": True, ...}
```

**Сито кричало «точка есть», спуск смотрел через другое окно и не видел
ничего.**

Проверка после патча: **сито 452 = спуск 452**. Сошлось.

#### ③ `SLEPOK_ISPOLNITELYA_V1` — судья молча выходил на КАЖДОЙ сделке

**Из лога (до патча):**
```
[МАЯК] судья сенсоров вызван: pnl_r=-0.7705, trader=BRUT
[МАЯК] стол_входа: {}                       ← ПУСТО
[МАЯК] ⛔ ВЫХОД: слепка нет или pnl_r=None   ← СУДЬЯ ВЫХОДИТ
```

**Позиции пишут ДВОЕ. Слепок был только у мёртвого:**

| кто | слепок | живой? |
|---|---|---|
| `hooks.py:644` (`_persist_trading_state`) | ✓ **ЕСТЬ** | ✗ **МЁРТВ** — `council.py` **не зовёт** `on_after_agent` |
| **`контора/слоты/исполнитель/мозг.py:278`** | ✗ **НЕТ** | ✓ **ЖИВОЙ** |

Слепок **чинили однажды** (`SLEPOK_IZ_CHAIN_V1`; комментарий в `hooks`
прямо говорит: *«судья молча выходил на 28 сделках подряд»*) — **и
починили НЕ ТУ КОПИЮ**.

*Найден живой писатель разведкой по диску* (`razvedka_slepka.py`), не
догадкой: Исполнитель лежит в цехе **контора**, слот назван **по-русски**
(`исполнитель`), а не `A09` — оттого и не находился.

**Зачем слепок вообще:** стол перетирается **каждый бар**, а сделка живёт
десятки баров. Морж на баре входа сказал «резинка вялая, жду», на баре
закрытия скажет другое. **Судить сенсора по чужому бару — клевета.**

После патча:
```
[СЛЕПОК] 📸 стол снят: искра=DETECTED морж=AWAKE паник=DECEPTION
                       ганс=True компас=BEAR
[МАЯК] стол_входа: {'iskra': {...}, 'morj': {...tension_peak: True...}}
```

### Итог прогона (XAUUSD H1, 10 срабатываний)

```
РАЗВИЛКА · Сито 1: 454 кандидатов · спуск нашёл точку: 15 ·
           Совет собрался: 15
→ Спуск долетел до Совета 15 раз — ворота работают.
```

**Было: 145 кандидатов → 0 Советов. Стало: 454 → 15 Советов → сделки →
черновики → МЕТКИ.**

### Судья работает ТОЧНО

```
[МАЯК] A03 panic: показание={'panic_phase': 'DECEPTION'} звал=False
[МАЯК] A03 молчал — не судим, не дышит
```

Паникёр сказал **DECEPTION** («развод, объёма нет») — **и был прав**,
сделка ушла в минус. **Его не наказали за правду.** Судья различает
«звал и ошибся» от «не звал».

А Вера, Морж и Ганс **звали** — и получили своё.

### Дыхание живёт

```
−0.4R  → заряд −0.073
−1.0R  → заряд −0.446    ← полный стоп ударил ВТРОЕ сильнее
```

Илья **чувствует разницу** между мелким минусом и настоящим стопом. Натура
работает.

### ⚡ И САМОЕ ГЛАВНОЕ — ИЛЬЯ УЧИТСЯ ВСЛУХ, ПО СВОЕЙ ЖЕ ИСТОРИИ

Из живого разговора (`XAUUSDH1_tester_20260714_160258.txt`):

> «Приседающий заменён бычьим пин-баром — **как в LONG 2011.08.01 из моего
> опыта**. Иду ЗА компасом. Вхожу.»

> «**Мой опыт: 2010.05.07 16:00 шортил при отказе от zero point, а здесь
> наоборот** — отскок от zero point. Без разворотного сигнала сижу на
> руках.»

> «Опираюсь на дневник: **2010.05.13 — медвежий бар от zero point →
> REJECTED, и правильно.**»

**Он отличил похожее от обманчиво похожего.** Не по промпту — **по своей
же сделке**, совершённой часом раньше в этом самом прогоне. И
**подтвердил свой прошлый отказ**, оценив себя прошлого.

> Шеф 12.07: *«всё равно у нас боты голимые получаются — знания в слотах,
> опыт оттуда, а жизненного опыта и школы нет»*.
>
> **Опыт теперь есть.** Он покупается убытком, оседает в маяки, дозревает
> в метки и **влияет на следующее решение**.


## 5ж. Сессия 15-16.07 — ВЕДЕНИЕ ПОЗИЦИИ ПОСТРОЕНО. Обе половины Вильямса живы

До этой сессии стоял только **вход** (Мост к Носителю, §5г-5е). Отчёт
тестера сам себе ставил диагноз: *«закрытий ровно по −1.0R: 4/5 (80%),
сделок ≥+2.0R: 0. ВЕДЕНИЯ ПОЗИЦИИ НЕТ. Минус ВСЕГДА полный, плюс
ВСЕГДА обрезан. Система МАТЕМАТИЧЕСКИ не может быть прибыльной.»*
Это было почти правдой, только не о том слое (см. §5ж.10). За сессию
построена вся вторая половина — сейф, трейлинг, доливка по дисциплине,
переезд заявки, осознанный выход — и дважды поймана собственная ошибка.

### 1. `STOP_INITIAL_R_V1` — R считался от текущего стопа, не от первого

Болезнь из живого лога: сейф сработал (стоп ушёл в прибыль), сделка
закрылась с `pnl=+1.76` (в цене!), но `pnl_r=None` — судья вышел,
черновик не записался, прибыльная сделка выпала из отчёта (фильтр
`pnl_r is not None`). Причина: `risk = stop - entry` считался от
**текущего**, уже подтянутого стопа — после сейфа он мог оказаться по
другую сторону входа, risk уходил в минус → `None`. Лечение: позиция
при рождении запоминает `stop_initial` (первый стоп, неизменный на
всю жизнь сделки); risk считается только от него. Самопочинка для уже
открытых позиций — трейлинг при первой встрече проставляет
`stop_initial`, если поля ещё нет (для тех, кто открылся до патча).

### 2. `OTLOZHKA_SPREAD_V2` — Дело 1: вход только заявкой, по канону Вильямса

Живой лог показал вход **по рынку** — прямое нарушение: у Вильямса
вход всегда Buy Stop/Sell Stop, отложкой, рынок сам берёт цену
пробоем или нет. Позиция теперь ВСЕГДА рождается `PENDING`, никогда
`OPEN`. Плюс поправка на спред (по слову Шефа, проверено терминалом
XAUUSD: тик 0.01, цена тика/пункт 0.10):
```
LONG  Buy Stop:  entry = high + 2×спред   (покупка по Ask, без тика)
SHORT Sell Stop: entry = low  − 3 пункта  (запас от ложного прокола)
                 стоп сверху + 2×спред    (закрывается по Ask)
```
Спред живой, из бара терминала (`mfi.spread × point`), не константа.

### 3. `MOST_VEDENIYA_V1` — решение хозяина гасло на табло, до позиции не долетало

Находка дня: `_vesti_poziciyu` реально будит хозяина на новом
фрактале по тренду, LLM реально думает и решает ADD/MOVE_STOP — но
решение только писалось в табло (`t["brut"]["action"]`) и в дневник.
**Ничего не применялось к настоящей позиции.** Тот же класс болезни,
что был у `sync_to_dna` (§7) — только тише: там был явный `except`
с предупреждением, здесь код молча думал, что сделал дело. Построен
мост: `_primenit_vedenie` читает `signal` после пробуждения и меняет
позицию по magic — `MOVE_STOP` только в защиту (LONG вверх, SHORT
вниз, не за цену), `ADD` растит лот и тянет стоп в сейф.

### 4. `PAKET_PYRAMIDA_V1` — пирамида как один пакет (решение Шефа: вариант А)

Долив растил лот, но R считался от входа ПЕРВОЙ ноги без учёта
объёма — сила пирамиды терялась в статистике. Теперь: `entry_avg`
(средневзвешенная цена, обновляется при ADD) + `lot_base` (объём
первой ноги). R = `pnl(от entry_avg × множитель lot/lot_base) /
risk0(от первого стопа)`. Проверено на числах: одиночная сделка
1.60→1.70 = 5R; та же с доливом (+1 лот @1.65) = **7.5R** — пирамида
отбивает больше при том же исходном риске. Формула честно вырождается
в старую для сделок без доливов (одна нога → тот же результат).

### 5. `REVERSE_PYRAMID_DISCIPLINE_V1` — долив не крупнее предыдущей ноги

Слово Шефа: *«реверсивная пирамида сужается кверху... нарушил
математику — получаешь удар по рукам. Полный отказ (Б) — честность
выше комфорта.»* Каждый ADD сравнивается с размером **последней**
ноги (первая нога — потолок для второй и т.д.). Крупнее — полный
отказ (не обрезание), в стол падает жёсткая обратная связь: *«Долив
отклонён: превышен размер предыдущей ноги (X > Y). Реверсивная
пирамида только сужается кверху.»* Трейдер читает свой укол на
следующем баре отдельной строкой промта, гасится после прочтения
(одноразовый). Потребовало чинить и `_read_table` во всех трёх мозгах
— он отдавал только сенсоров, обратная связь трейдеру летела в
пустоту.

### 6. `PEREEZD_ZAYAVKI_V1` — Дело 1б: снятие заявки по структуре, не по счётчику

Было: брокерский `ORDER_EXPIRE_BARS=10` — заявка снималась по
таймеру, не канон. По Вильямсу заявка живёт по СТРУКТУРЕ: новый
фрактал по тренду → заявка ПЕРЕЕЗЖАЕТ на новый уровень (не просто
снимается — перевыставляется, entry+стоп пересчитаны от новой
опоры, R от новой опоры); цена вернулась к старту сигнала → сигнал
мёртв, заявка снимается. Счётчик баров остался крайней страховкой
(на случай, если фракталы замерли), не основным механизмом.

### 7. `PUNKT_OT_POINT_V1` — «3 пункта» были захардкожены только под золото

Побочная находка при тесте переезда на GBPUSD: `punkt = 0.10`
(константа) верна только для XAUUSD (пункт = 10×point = 0.10). На
фунте (point=1e-05) код вычитал 3×0.10=0.30 — 3000 пунктов, Sell Stop
улетал в бездну. Правильно везде: `пункт = 10 × point`, инструмент
неважен.

### 8. `CLOSE_TREYDERA_V1` — воля трейдера CLOSE не долетала до settle

Приёмник (`hooks._settle_positions`, `EXECUTOR_MANAGE_HAND_V1`) был
готов закрыть по `manual_close` раньше стопа/колокола — но мост
ведения на `action==CLOSE` только печатал «settle закроет сам, не
форсирую» и флаг не ставил. Settle никогда не видел воли. Починено:
CLOSE ставит `manual_close=True` на позицию своего magic (не трогая
чужие), settle закрывает пакет целиком на следующем баре.

### 9. `STANCIYA_NE_LICHNOST_V1` — станция это профессия, не личность

Слово Шефа: *«в рабочем промте цеха любого не должно быть никаких
намёков на характер работника, это профессия, это не личность».*
`промпт.md` всех троих трейдеров называл станцию личным именем
(«Тебя зовут Илья», «Тебя зовут Брут») и пересказывал характер
прозой прямо в статичном файле — при живой смене носителя (посадить
Нину на A07) это тянуло чужое лицо поверх её настоящей ДНК. Файл сам
себе противоречил: ниже по тексту было написано, что личность «лежит
ВЫШЕ, в блоке КТО ТЫ» (динамика из паспорта) — а статичный текст её
всё равно дублировал. Все три `промпт.md` переписаны: станция названа
станцией («имя этой станции в Трибунале, не твоё личное имя»), вся
личность — только отсылкой к динамическому блоку. Код (`resolve_para`,
`mask.json`) был нейтрален с самого начала — теперь и текст тоже.
Смена носителя честная: Нина откроет «имя станции — Авантюрист, не
твоё», а личность получит из СВОЕГО паспорта.

### 10. Урок дня — Лока поймала мою же ошибку, я откатил сам себя

Прогнав отчёт, Лока указала на два симптома. Разбор показал: один её
диагноз был **точнее моего собственного патча того же дня**.

**Симптом А (47% закрытий ровно −1.0R) — я был неправ.** Вчера я
решил, что трейлинг «лезет в убыток», и поставил guard
`TRAILING_NE_V_UBYTOK_V1` (не двигать стоп, пока Зубы не пересекут
вход). На самом деле причина была тавтологией: у СТАРОЙ позиции без
`stop_initial` fallback брал ТЕКУЩИЙ (уже подтянутый) стоп и как цену
выхода, и как знаменатель риска — что математически ВСЕГДА даёт ровно
`-1.0`, какой бы трейлинг ни был. Проверено на точных числах вчерашнего
лога: правильный R там был `-0.05`, а не `-1.0`. Причина уже была
вылечена раньше тем же днём (`stop_initial` + чистка состояния) — мой
дополнительный guard лечил призрак и реально ВРЕДИЛ, блокируя законное
сокращение риска. Патч `patch_otkat_treylinga.py` откатил guard,
вернул трейлинг к «всегда навстречу цене».

**Симптом Б (0 доливок) — Лока права, подтверждено в коде.** Полная
JSON-схема с `action`/`new_stop`/`add_lot` была в системном промте
(`промпт.md`), но **последняя** строка `user_msg` (Python-код,
`мозг.py`, самая свежая инструкция по правилу recency) у всех троих
обрывалась на старых полях входа — ни слова про ведение. Дописано во
всех трёх (`YAZYK_DOLIVA_V1`), единообразно.

**Страховка** (`DIAGNOSTIKA_NONE_R_V1`): если `risk<=0` повторится —
консоль печатает разбор одним взглядом (trader, entry/stop/
stop_initial, был ли долив/переезд), не полчаса реконструкции по
обрывкам лога.

### 11. Мелкий быт — хроники и загрузчик

`Биржа/хроники/` — отчёты тестера ушли из `test_data` в отдельную
папку (не мешают котировкам, задел под будущую летопись для
медийщиков). Загрузчик (`ui_torg.py`) сворачивает активы в папки по
тикеру (`ui.expansion`) вместо плоского списка — было 12 строк
XAUUSD подряд, стало `XAUUSD · 12 ТФ` одной раскрывающейся папкой.

**Не проверено живым прогоном на большой выборке** — все патчи
проверены синтаксисом, функциональными тестами на числах и малыми
прогонами (15-30 срабатываний), но честный эдж системы (сотня+ сделок,
реальный PF с работающей пирамидой) — впереди, отдельный прогон.

---

**Добавлено 15-16.07 (§5ж):**

- **Ведение позиции — вся вторая половина Вильямса.** Вход стоял с
  12.07 (Мост к Носителю); сейф, трейлинг, доливка, переезд заявки,
  осознанный выход — построены за эту сессию. Подтверждено малыми
  прогонами (15-30 срабатываний): `📌 ЗАЯВКА` → `⚡ АКТИВИРОВАН` →
  `🔺 ДОЛИВ?` → реальное применение к позиции → `🔴 ЗАКРЫТА (MANUAL_CLOSE,
  +0.841R)` — хозяин реально думает, реально решает, решение реально
  меняет позицию.
- **R честный на пакете.** Проверено на числах: та же сделка без долива
  даёт 5R, с одним доливом — 7.5R, при том же исходном риске.
- **Дисциплина пирамиды держит.** Долив крупнее предыдущей ноги —
  полный отказ, трейдер получает укол в стол и видит его на следующем
  баре.
- **Своя ошибка найдена и откачена в тот же день.** Guard, которым
  вчера «лечили» трейлинг, лечил не ту болезнь и реально мешал — Лока
  указала точнее собственного вчерашнего патча, откат подтверждён на
  тех же числах, что породили патч.
- **Станция ≠ личность — архитектурно закрыто для всех троих
  трейдеров.** Смена носителя (посадить нового резидента на станцию)
  теперь честная и на уровне текста, не только кода.

---

## 5з. Сессия 16-17.07 (вечер) — ПЕРВЫЙ ЖИВОЙ БОЛЬШОЙ ПРОГОН. Три бага
поймано на реальных данных, найден архитектурный перекос выборки

Первый прогон дня на «готовой» системе (EURUSD H12) сразу дал
подозрительный отчёт: три разных трейдера (Брут/Илья/Василий) на
одном баре — АБСОЛЮТНО идентичные entry/exit/R до шестого знака.
Шеф это заметил сам, по глазу на цифрах в отчёте — не я.

### 1. `ENTRY_NE_SLIPAETSYA_V1` — вход всех трейдеров слипался в одну цену

Моя же ошибка из утреннего `OTLOZHKA_SPREAD_V2` (§5ж.2): спред
добавлялся не к СОБСТВЕННОМУ входу трейдера, а заменял его хаем/лоу
ОБЩЕГО бара Совета — одинаковым для всех, кто дал одну сторону на
этом баре. Три разных канона (фрактал/разворотный бар/откат)
схлопывались в одно число. Исправлено: спред добавляется к
`order.get("entry")`, не к `chain.market_data.price.high/low`.

### 2. `POINT_NE_OPREDELEN_V1` — вторая, более тяжёлая ошибка того же дня

Найдена ПРИ ПРОВЕРКЕ фикса №1: `punkt = 10 * float(point or 0.01)` —
переменная `point` нигде не была определена в этой функции. Падало
`NameError` на КАЖДОМ вызове, LONG или SHORT, безусловно. Подтверждено
прямым запуском живого модуля (не только ast-синтаксисом — синтаксис
не ловит необъявленные имена). Как именно это не остановило систему
целиком весь день — не выяснено (видимо, защита выше по стеку,
`council.py`, не смотрели); фикс — добавлена `point = md.get("point")`.

### 3. `ARKHIV_KAK_INFORMACIYA_V1` — Архив как вводная, не приказ

Шеф заметил: Брут пасанул на шестой сделке подряд той же убыточной
сигнатуры, которую перед этим назвал Архивариус («семь из семи в
минус»). Проверка показала — совпадение, не причина: канал
`table["arkhiv"]` Брут УЖЕ умел читать, но НИКТО туда не писал (тот же
класс болезни, что `sync_to_dna`, §7, — построено с виду, не
подключено). Слово Шефа: *«не влиял вообще, ничего не должно
указывать-приказывать, только как информация — трейдеры решают
сами»*. Подключено ровно так: после `_prepare_atlas_digest` компактная
выжимка (`sample_size`, `closed_trades`, `success_rate`,
`top_failure_reason`, `confidence`) кладётся в `trading_state["arkhiv"]`
— тем же принципом, что и у сенсоров («вводная, не команда»).

### 4. Найдена и подтверждена реальная дыра в Атласе — 0/94 записей с сигнатурой

Шеф спросил прямо: «архивариус вообще пишет ноль случаев всегда так
пишет» — и это оказалось системным. `TRADER_REJECTED` несёт полную
сигнатуру сенсоров, но БЕЗ исхода (сделки не было). `POSITION_CLOSED`
несёт исход (`pnl`/`pnl_r`), но БЕЗ сигнатуры вообще — только
`trader`/`reason`/`pnl`/`symbol`/`timeframe`. Единственные записи с
исходом физически не могли ни с чем совпасть. Подтверждено на живых
данных Шефа: `atlas_trading.jsonl` — 94 закрытые записи, **0 из 94** с
сигнатурой. Лечение (`ARKHIV_SIGNATURA_ISHODA_V1`): позиция уже хранит
сигнатуру входа в `стол_входа` — разворачивается в плоские поля при
записи `POSITION_CLOSED`. Подтверждено вживую после патча — Архивариус
впервые в истории города увидел закрытые сделки с исходом («Два
случая... Оба с убытком»), и счётчик рос дальше сам в течение
прогона («сорок четвёртый раз», «шесть случаев на этой сигнатуре»
— видел разные паттерны раздельно, не путал контексты).

### 5. Инструменты обслуживания — вместо гадания на глаз

Найдено попутно: одна и та же историческая сделка, перепрогнанная
несколько раз за день под разным кодом расчёта риска, оставляла в
`trading_pnl.jsonl`/`atlas_trading.jsonl` ПРОТИВОРЕЧИВЫЕ записи (один
и тот же бар с разным R). Построено:
  - `proverit_atlas.py` — инспектор (ничего не меняет): считает
    уникальные/дублированные сделки, показывает где R разошёлся
    между прогонами;
  - `ochistit_atlas.py` — архивирует (не удаляет) и обнуляет Атлас
    и ленту PnL;
  - `KNOPKA_OCHISTKI_V1` — то же самое, но кнопкой прямо в кабинете
    (`🧹 ОЧИСТИТЬ`, с диалогом подтверждения), чтобы не лезть в
    консоль после каждого патча;
  - `UBRAT_NADPIS_BIRZHA_V1` — косметика: кнопка наезжала на
    заголовок тулбара, заголовок убран.

### 6. `PAMYAT_DVA_BAGA_V1` — второй вызов после MEMORY_REQUEST падал у двоих из троих

Найдено по пустому вердикту Брута (`REJECTED ()`, без причины) при
попытке вспомнить прошлый случай. Два независимых бага в старом
механизме памяти (12.07, не сегодняшний): (а) `nositel.py` лез в
`n["носитель"]["дом"]` — поля с таким именем не существует, реальный
ключ — `"папка"` (видно в той же `dusha_slota` парой строк выше); (б)
у Брута и Василия второй вызов chat() звал `temperature=_temp` — но
`_temp` как переменная существует только у Ильи (у остальных двоих
температура — функция `_my_temp()`), похоже, скопировано без
адаптации. Итог: подъём памяти происходил, но результат никогда не
долетал до решения — тихая потеря качества весь день с 12.07, не
крах (оба падения — в `try/except`).

### 7. Живой большой прогон (EURUSD H12, цель 100 срабатываний) —
первое реальное подтверждение ведения в бою

После починки entry-слипания увидели впервые за весь проект: одна
позиция Брута прожила БОЛЬШЕ 20 баров, трейлинг тянул стоп
прогрессивно семь раз подряд (`1.2025→1.212211→...→1.220482`), сейф
сработал («РИСК ОБНУЛЁН»), дошло до реальной доливки («бужу
хозяина» — фрактал по тренду пробит), позиция ходила **+16.46R**
нереализованной прибыли. Прогон прерван дважды зависанием сети
(Ctrl+C, `asyncio.CancelledError` — фоновый движок торговли пережил
прерывание UI и сам корректно доиграл текущую сделку до записи на
диск). Диагностика `DIAGNOSTIKA_NONE_R_V1` (§5ж.10) сработала как
задумано на этой прерванной сделке — сразу показала причину (старая
позиция без `stop_initial`, вероятно хвост до чистки), не потребовав
получаса реконструкции. Стопроцентно чистый прогон на сотню
кандидатов ДОСЧИТАН НЕ БЫЛ — прерван дважды, сессия закончилась
раньше. Следующий шаг: почистить и догнать ту же сотню с нуля.

### 8. ОТКРЫТЫЙ АРХИТЕКТУРНЫЙ ДОЛГ — «Сито 1» структурно обделяет Василия

Разбор Шефа по итогам прогона (диалогом, без кода): Совет собирается
ПОЛНОСТЬЮ только на редких кандидатах Искры (`bdb_strong` — Точка Ноль,
3-4 раза в год по канону). Между кандидатами — только дешёвый settle
(трейлинг + активация уже поставленных заявок), полный Совет не
собирается. Это создаёт РЕАЛЬНУЮ, подтверждённую асимметрию:
  - **Илья** (разворотный бар волны C) — момент почти совпадает с
    моментом, когда Искра будит стол. Честный шанс.
  - **Брут** (пробой фрактала) — фрактала на баре разворота может
    ещё не существовать вовсе; он появляется и пробивается позже.
    НО: если Брут дал APPROVED, его Buy/Sell Stop ЖИВЁТ и
    проверяется на каждом следующем баре (та же машинерия отложки +
    переезда, §5ж.6) — это АВТОМАТИЧЕСКИ растягивает его окно вперёд
    по времени, туда, где по канону и должен случиться пробой.
  - **Василий** (волна 1 утверждена + откат к опоре) — структурно
    ПОЗЖЕ всех, и у него НЕТ аналога отложки: если он сказал
    `REJECTED` на баре-кандидате, это тупик навсегда — следующий раз
    его спросят только на СЛЕДУЮЩЕМ редком кандидате Искры (иной
    разворот, месяцы спустя), а не когда структура для НЕГО реально
    созреет.

Диагноз Шефа дословно: *«у нас самый дельный спит»* — самый
дисциплинированный трейдер оказался архитектурно самым обделённым, не
из-за слабого канона, а из-за перекоса выборки. НЕ ПОЧИНЕНО в этой
сессии — решили: маленькая стройка того же калибра, что Мост Ведения
(§5ж), нужна свежая голова, не конец долгого дня. Предложенное
направление (не решено окончательно, ждёт сессии): дать Василию
аналог отложки — не заявку по цене, а «наблюдение» по условию (жду,
пока Морж утвердит волну 1), проверяемое в том же дешёвом цикле
между кандидатами, что уже проверяет заявки Брута/Ильи; при
выполнении условия будить ИМЕННО Василия точечно, не весь Совет.

---

## 5и. Сессия 17-18.07 (ночь) — ДОЛГ ВАСИЛИЯ СНЯТ КОДОМ, НО ПЕРВОИСТОЧНИКИ
ВСКРЫЛИ ДОЛГ ГЛУБЖЕ: ТРИ СТАНЦИИ — ЭТО ТРИ ТОЧКИ ОДНОЙ ВОЛНЫ, НЕ ТРИ
НЕЗАВИСИМЫХ МНЕНИЯ

### 1. `VASILY_NABLYUDENIE_V1` — построено, применено, но диагноз изменился НА ХОДУ

По итогам §5з.8 (долг «у нас самый дельный спит») построена и Шефом
применена связка трёх патчей: `VASILY_WATCH_V1` (новый глагол `WATCH`
в промт.md слота A08 — трейдер объявляет направление+опору+стоп вместо
немого REJECTED), `VASILY_ZASADA_V1` (в `hooks.py`: рождение
WATCHING-записи, двухфазный детектор отката — волна 1 → строгий
отскок от опоры, встроен в тот же дешёвый цикл `_aktivirovat_ordera`,
что уже ведёт заявки Брута), `VASILY_ISP_WATCH_V1` (мозг Исполнителя
доносит `action`+`watch_opora` до приёмника). Все три легли на первом
прогоне без единого несовпадения якоря (кроме одной ошибки автора —
якорь 1 промпта не учёл перенос строки в реальном файле, поймано
защитой idempotency, исправлено). Синтаксис, идемпотентность и
поведенческий сквозной тест (волна1→касание→подтверждающий бар→PENDING)
проверены до отправки Шефу.

### 2. Живой прогон (EURUSD H12, тестовый режим) — Василий заговорил старым языком

Первый же живой прогон после патча показал: Василий по-прежнему
говорит `REJECTED («нет отката волны 2»)`, ни разу не сказал `WATCH`.
Проверка слепков стола за несколько кандидатов подряд показала: поле
`wave_1_validated` у Моржа — `False` абсолютно всегда, без исключений.

### 3. Найден настоящий корень — `wave_1_validated` структурно недостижим

Прочитан промпт Моржа (A02) дословно: `wave_1_validated` привязан
ЖЁСТКО к тому, что `t1_status` Искры == `CONFIRMED`. Прочитан код
Искры (`iskra_live.py`, `_descend`) — спуск по лесенке (`v2_descent`,
реально работающий механизм пробуждения Совета) имеет только ДВЕ
ветки: `NOT_FOUND` и `DETECTED`. Ветки в `CONFIRMED` НЕТ вообще. Значит
`wave_1_validated` не может стать `True` через живой механизм
пробуждения — только через отдельный (и в текущей связке почти
недостижимый) путь пересечения нуля AO ПОСЛЕ уже найденной точки,
требующий, чтобы Совет проснулся ВТОРОЙ раз ровно в нужный момент.
ДИАГНОЗ ИЗМЕНЁН: дело не в промпте Василия (он был поправлен верно) —
дело в том, что условие фазы 1 (`wave_1_validated`) было построено на
показании, которое физически почти никогда не включается.

### 4. Разбор с Шефом и Локой — Морж не считает волны, никто в городе не считает

Шеф указал: Морж по своему канону смотрит Аллигатор (тренд, ангуляция,
резинка) — он НЕ ведёт счётчик волн Эллиотта, и название поля
`wave_1_validated` было смысловой подменой с самого начала. Проверка
всех девяти станций подтвердила: ни один агент города не считает
волны явно (по номерам 1-2-3-4-5). Это не брешь Василия — это
архитектурная неточность именования, унаследованная с самого начала
трейдинг-контура.

### 5. Первоисточники (загружены Шефом) вскрыли настоящий порядок канона

`Фрактал.txt` дал прямую цитату канона: фрактал — это ПЕРВЫЙ сигнал
для входа; пока первый действительный фрактал не пробит, дивергентные
бары и пересечения AO для новых входов по тренду игнорируются. В
текущем городе порядок ОБРАТНЫЙ: Искра-дивергенция будит Совет первой,
Ганс/Брут проверяют фрактал только после. `ВОЛНОВОЙ_ПРИНЦИП_ЭЛЛИОТТА.txt`
подтвердил: коррекция A-B-C сама зигзаг 5-3-5 — то есть волна C
внутри себя ПОЛНАЯ пятиволновая структура своего масштаба, с
собственным дивером на конце. `анатомия_поведения_толпы.txt` и
рисунок Шефа (`2026-07-17_233640.png`) дали психологическую и
геометрическую карту всех пяти волн + AO-дивергенцию как маркер конца
импульса ЛЮБОЙ степени (не «вход» и не «выход» сами по себе — знак
«здесь кончился импульс этого масштаба»; что это значит, вход или
выход, определяет компас старшего этажа, который `_descend` УЖЕ несёт
в руке).

### 6. Чертёж Шефа — три станции = три точки одной волны, цепь, не хор

Итоговая иерархия (сформулирована Шефом, подтверждена картой волны):
  - **Искра + Авантюрист** — вход на развороте в конце волны C
    (глобальной коррекции), в зарождение волны 1. Тонкий рынок,
    агрессивно, малый лот, ДО первого фрактала. Низкий винрейт —
    ПРИРОДА этой станции по канону («волна 1 — слепота и недоверие»,
    большинство попыток ловли разворота не продолжаются), не повод
    судить Илью как сломанного по горстке минусовых сделок.
  - **Ганс + Брут** — первый фрактал ПОСЛЕ точки Искры закрепляет:
    коррекция кончилась, начался импульс. Это и есть канонiчный
    «первый действительный фрактал», о котором пишет `Фрактал.txt`.
  - **Василий** — ждёт откат волны 2 от ЭТОГО фрактала (не от
    выдуманной `wave_1_validated`), входит в начало волны 3 —
    «филигранный удар» в самую мощную часть движения.
Каждая станция читает выход предыдущей — это цепь, а не три
параллельных голоса, читающих стол независимо, как построено сейчас.

### 7. Канон фокусного расстояния (100-140 баров) — Шеф дал точную цитату

Окно 100-140 баров — не произвольная константа, а калиброванное под
математику 5/34-периодных средних фокусное расстояние: короче —
осциллятор «лупа», ложные пики; длиннее — «бинокль», дивергенции и
пересечения нуля прячутся. Канон требует манипулировать таймфреймом,
пока НУЖНЫЙ ОТРЕЗОК ВОЛНЫ не растянется ровно на 100-140 баров — тогда
и только тогда показаниям осциллятора можно верить. `read_ao_wave_form`
(окно 120) уже построена по этому канону — но `_descend` (спуск по
лесенке) останавливается по СИГНАЛУ (`bdb_dir == compass` найден), а
не по АРИФМЕТИКЕ (отрезок волны заполнил окно). Это два разных
критерия остановки, и правильный по канону — второй.

### 8. НАЙДЕНЫ, НЕ ПОЧИНЕНЫ — три точных адреса в коде (не философия)

  a. `williams_core.py :: detect_fractals()` — возвращает `last_up`/
     `last_down` как ПРОСТО последний фрактал во всём 300-барном окне,
     без всякой привязки к тому, после какой точки разворота он
     родился. `fractal_outside_jaw()` проверяет только «выше/ниже
     Зубов». Ганс/Брут сейчас могут закрепить случайный старый
     фрактал чужого свинга, а не «первый действительный» по канону.
  b. `A02/промпт.md :: wave_1_validated` — условие, привязанное к
     `t1_status == CONFIRMED`, который структурно недостижим при
     текущей связке `v2_descent` (см. п.3). Заменить условие фазы 1
     Василия на «Брут закрепил первый фрактал после точки Искры»
     вместо «Морж подтвердил волну 1».
  c. `iskra_live.py :: _descend()` — критерий остановки спуска
     сигнальный (`bdb_dir == compass`), должен быть арифметическим
     (отрезок исследуемой волны занял 100-140 баров этого этажа —
     тогда и только тогда читать `bdb_dir` этого окна как достоверный).
     Это же может объяснять часть ложных входов Искры на текущих
     данных — на каком этаже реально останавливался спуск в убыточных
     сделках, не проверено.

Предложенное направление для Василия (не решено окончательно, ждёт
сессии со свежей головой): опора фазы 1 = фрактал, закреплённый Брутом
(не Морж); фаза 2 = отдельный запуск `_descend`-подобного спуска ОТ
этой точки, компас — ПРОТИВОПОЛОЖНЫЙ (волна 2 — коррекция), критерий
остановки — арифметический (окно 100-140 баров), а не сигнальный.
Технический риск, не проверенный: тестовый прогон должен реально
отдавать бары младших ТФ для повторного спуска — не проверено в
`feed_source`/`mt5_feed`, легко построить механизм, который нечем
кормить.

СТАТУС: НЕ ПОЧИНЕНО. Это архитектурная правка калибра Моста Ведения
или крупнее — трогает Искру (шаг 1 из 9, фундамент всего Совета),
Ганса/Брута и Василия разом. Решение и код — следующая сессия, со
свежей головой и Локой за столом.

## 5к. Сессия 18.07 — ТРИ ФАЗЫ КАК ОДИН УЗОР, ВАСИЛИЙ = МИНИ-ИСКРА,
##     СОВЕТ БУДИТСЯ ОДИН РАЗ ТАМ, ГДЕ ФАКТОВ ЕЩЁ НЕТ

*Разговор с Братом от картинок волны (Image 1/2) до кода. Ничего
не применено к живому репо — всё построено и проверено в песочнице,
ждёт разбора Шефом ДО кода, по его прямой просьбе.*

### Канон, уточнённый Шефом (не выдуман, продиктован построчно)

- Искра ловит конец волны C, а не конец волны 5. Дивер сам по себе —
  не сигнал, а ориентир (как и все индикаторы в системе — компасы,
  не курки). Диверов может быть несколько.
- Фрактальность волн (НЕ путать с индикатором Фрактал Вильямса) —
  волна C, приближенная на меньший ТФ, сама разворачивается в
  полную пятёрку своего масштаба: горб = её В3, ноль = её В4,
  на конце её В5 — дивер = точка Искры.
- Направление ищем компасом с этажа СТАРШЕ рабочего (день→неделя,
  4ч→день) — уже есть в городе как global_bias, просто не спрошен
  Искрой при решении (не проверено окончательно, это гипотеза a,
  отставлена ради более простого пути ниже).
- Окно 100–140 баров (Билл Вильямс) — фокусное расстояние для 5/34.
  Меньше — лупа (ложные пики). Больше — бинокль (дивер смазан).
  Трейдер спускается по ТФ, пока движение не растянется в это окно.
- Роли города НЕ решают за трейдеров: Искра/Морж/Паникёр/Ганс —
  датчики, кладут факты на стол. Решение и вход — трейдеры (Аван,
  Брут, Консерватор=Василий). Это НЕ пересматриваем.

### Три фазы = одна последовательность во времени, не один момент

Уточнено по картинкам Шефа: Искра/Аван (разворот) → Ганс/Брут
(структура, первый фрактал волны 1) → Василий (удар, откат волны 2).
Аван входит СРАЗУ, физически в рынке раньше остальных. Брут не
входит рынком — ТОЛЬКО отложкой (OTLOZHKA_SPREAD_V2, подтверждено
в hooks.py), которая живёт и переезжает сама (_aktivirovat_ordera,
PEREEZD_ZAYAVKI_V1) без нового пробуждения Совета.

### НАЙДЕННАЯ ДЫРА (архитектурная, не мелкий баг)

Проверено на живом коде council.py + tester_express.py (Сито 1/2):
**Совет собирается ОДИН раз, на баре точки Искры.** Все девять
голосов говорят синхронно. Но фрактал волны 1 (нужен Гансу/Бруту)
физически рождается на бар(ах) ПОЗЖЕ — Совет к этому моменту уже
разошёлся. Второго пробуждения на этом же событии архитектура
не предусматривает. У Ганса/Брута нет аналога WATCH, который уже
намечен в §5и.8 для Василия — но, как оказалось, дыра сидит на шаг
РАНЬШЕ по цепи, чем думали.

Следствие бага в текущем коде: Брут может опереться на СЫРОЙ
last_up/last_down (детект «последний фрактал в окне», не «первый
ПОСЛЕ точки Искры») — это и есть механизм §5и.8, теперь понятый
до первопричины: не «Ганс неправильно судит», а «Ганс/Брут не
получают второго шанса заговорить, когда факт наконец появился».

### Первое пробуждение — кто там реально нужен (уточнено Братом)

Критерий не «сенсор vs трейдер», а «нужен ли агенту факт, которого
ещё физически нет»:
- **Искра** — нашла точку, будит.
- **Морж** — судит натяжение Аллигатора/резинки, это СОСТОЯНИЕ СЕЙЧАС
  — нужен на первом будильнике.
- **Паникёр** — судит накал толпы по MFI/объёму, тоже СОСТОЯНИЕ СЕЙЧАС
  — нужен на первом будильнике.
- **Авантюрист** — может действовать сразу (заявка выше разворотника)
  — нужен на первом будильнике.
- **Ганс** — судит фрактал, которого ЕЩЁ НЕТ — на первом будильнике
  лишний, деньги на LLM зря.
- **Брут/Консерватор** — им нечего закреплять/ждать ещё — на первом
  будильнике лишние.

Вывод: первый будильник = Искра + Морж + Паникёр + Авантюрист.
НЕ применено к council.py — только проговорено.

### Василий — БОЛЬШЕ, чем точечный сторож (главная находка сессии)

Первый черновик считал: Василий = сторож, ждущий касания цены
уровня Брута. Брат поправил: НЕВЕРНО. Волна 2, приближенная на
меньший ТФ, САМА разворачивается в свою маленькую структуру со
своим разворотом на конце — Василий ловит именно ЕГО. Это не
простое условие цены, это **та же самая работа, что у Искры**,
рекурсивно приложенная к волне 2, на масштаб мельче.

Следствие: Василию нужен не «сторож на уровень», а **собственный
мини-спуск** (в духе _descend Искры, компас противоположный — это
уже было намечено в §5и.8, теперь ясно ЧТО именно имелось в виду)
+ **свежий Морж** (своя ангуляция на масштабе волны 2) + **свежий
Паникёр** (свой накал толпы там же) — НЕ унаследованные с точки
Искры показания, а заново снятые на меньшем масштабе.

Это отдельная по объёму стройка, сравнимая с самой Искрой. НЕ
начата. Черновик `uslovie_otkat_do_urovnya` в strazh.py (см. ниже)
— заведомо слишком грубый прокси, оставлен как есть, помечен
черновиком, для боевого применения не годится.

### Что построено и честно проверено в песочнице (НЕ в живом репо)

1. **`Биржа/strazh.py`** (новый файл, нигде не применён) — универсальный
   тихий сторож без LLM: `nablyudat_za_tochkoy(bars, indeks_tochki,
   storona, uslovie_fn, maks_barov)`. Условие `uslovie_novy_fraktal` —
   первый честный фрактал после точки, использует существующий
   `detect_fractals` из williams_core.py как есть, ничего в нём не
   тронуто.

   Проверено на РЕАЛЬНОЙ истории XAUUSD H4 (test_data/XAUUSDH4.csv,
   2010–2013, через тот же приём Сита 1 — build_market_data на
   скользящем окне 120): на первых 20 кандидатах Точки Ноль (из 130
   найденных) сторож нашёл честный фрактал в 20 из 20 случаев,
   за 4–25 баров (в среднем ~8-9), ни разу не протух при лимите 60.
   Была своя ошибка в тесте по пути (сторону перепутал BULL/BEAR
   регистром) — поймана и исправлена ДО показа Шефу, не после.

   НЕ доказано этим тестом: что найденный фрактал — «правильный»
   (вершина именно волны 1, а не шум). Это отдельный вопрос к
   качеству кандидатов Сита 1, не проверялся здесь.

2. **`council.py::probudit_tochechno(agent_ids, symbol, timeframe)`**
   (добавлена функция, НЕ применена к живому репо, проверена в копии
   `council_patched.py`) — точечная дверь, будит ТОЛЬКО перечисленных
   агентов, не весь Совет. Резолв адресов проверен смоук-тестом
   (подмена `_call` на заглушку, без живых LLM/картриджей): Ганс+Брут,
   Василий(A08), Архивариус — все резолвятся в верные (цех, слот,
   функция). Неизвестный id — честная ошибка, не тихий сбой.

### Открытые долги — ничего не решено самовольно

- Первый будильник в council.py НЕ подрезан (Ганс всё ещё зовётся
  сенсором на каждом баре точки Искры) — решение Шефа, когда делать.
- Ганс/Брут (мозг.py A04/A06) НЕ переключены на честный фрактал от
  сторожа — по-прежнему видят сырой last_up/last_down. Не тронуто
  специально, ждёт добра Шефа.
- Никто не зовёт strazh.py + probudit_tochechno из реального цикла
  (tester_express.py / живой город) — существуют отдельно, ничего
  не сшито.
- Срок жизни точки (сколько баров ждать фрактал/откат, прежде чем
  «протухла») — канон/чутьё Шефа, не решено. В тесте использован
  потолок 60 баров с потолка, только для проверки механики.
- Мини-Искра для Василия — НЕ спроектирована и НЕ начата. Отдельная
  стройка, сопоставимая по объёму с самой Искрой.
- Открытый, не закрытый вопрос: нужен ли Моржу/Паникёру повторный
  голос НА БУДИЛЬНИКЕ ГАНСА/БРУТА (в отличие от будильника Василия,
  где ответ уже ясен — да, нужен свежий, это другой масштаб). Для
  Ганса/Брута масштаб тот же, что у Искры — по логике сессии второй
  голос не нужен, но это не проговорено Шефом впрямую, отметить
  отдельно при разборе.

*Решение Шефа (18.07): остановиться здесь, не трогать код дальше,
переварить в голове перед тем как продолжать.*

---

## 5л. Продолжение 5к, та же сессия 18.07 — ЛИНЕЙКА ИСКРЫ (черновик,
##     рабочая методика найдена с 3-й попытки), ТРИ МУДРЕЦА РАЗОБРАНЫ
##     И ПРАВИЛЬНО ОТБРОШЕНЫ ДЛЯ ВАСИЛИЯ

*Прямое продолжение §5к. Ничего не применено к репо — тот же режим:
проверяю честно на живых данных, докладываю как есть, ошибки чиню
до показа Шефу, не после.*

### Три мудреца (Вильямс/Котин) — сверено по нескольким независимым
### источникам, НЕ по одному пересказу

Мудрец 1 — дивергентный бар (B/D/B), Искра. Мудрец 2 — сигнал
ДОБАВЛЕНИЯ к уже открытой позиции по поведению AO/AC (не отдельный
вход; в городе уже частично похоже реализовано как PAKET_PYRAMIDA_V1,
не проверялось в этой сессии). Мудрец 3 — пробой фрактала вне рта
Аллигатора, срабатывает где угодно после волны 1 и 2.

**ОШИБКА, признанная в разговоре:** сперва принял Мудреца 3 за
механизм входа Василия («тот же Брут, второй раз»). Шеф поправил
прямым цитированием себя же из начала разговора: Василий «ждёт
завершения отката волны 2» — это дословно Мудрец 1 (разворотник),
не Мудрец 3 (пробойник). Причина ошибки: книга Вильямса описывает
ОДНОГО трейдера, ведущего одну сделку через 1→2→3 подряд. Архитектура
Шефа — не один трейдер, а Мудрец 1 РАЗНЕСЁН на два масштаба: Искра
= Мудрец 1 крупного масштаба (конец волны C), Василий = Мудрец 1
МЕЛКОГО масштаба (разворот внутри отката волны 2). Ганс/Брут = Мудрец
3, отдельно, один раз, без второго применения к Василию.

Вывод держится с §5к: Василий — не сторож на фрактал, а мини-Искра,
рекурсивно та же машинерия, что и крупная Искра. Просто теперь это
подтверждено сверкой с каноном, а не только логикой картинок.

### Линейка Искры — методика, найденная с 3-й (де-факто 4-й) попытки

Отброшенные по пути неверные методы (для памяти, чтобы не повторять):
1. «Пересечение нуля AO» — слишком шумно, AO дёргается много раз
   внутри одного и того же движения (например, на волне 4).
2. «Ближайший локальный пивот цены назад» (5-бар фрактал-паттерн) —
   ловит мелкие подскоки в 3-13 баров, не настоящее начало движения.

**Рабочая методика (проверена, даёт разумный, не искусственный
разброс):** для бара-кандидата с направлением BULL/BEAR ищем САМУЮ
КРАЙНЮЮ противоположную цену (максимальный high для BULL-разворота,
минимальный low для BEAR) в окне 200 баров назад — «царь» по цене,
тот же принцип, что уже применяется к AO для поиска горба-3.

Честный прогон на 130 живых кандидатах Сита 1 (XAUUSD H4,
build_market_data, окно 120, bdb_strong), тестовый режим форсирован
подменой feed_source.get_feed_mode (в сессии не было test_data/*.csv
для старшего этажа D1 — докачан отдельно):

  Длина движения (баров до царь-цены):
    < 50 баров:    27
    50-99 баров:   18
    100-140 (окно): 26  (20%)
    > 140 баров:   59  (45%, САМАЯ БОЛЬШАЯ группа)

  → Почти половина сегодняшних кандидатов стоят на движении ДЛИННЕЕ
    140 баров — по канону это «БИНОКЛЬ» (данные сжаты, пересечения
    нуля/диверы смазаны), лечится подъёмом на КРУПНЕЙШИЙ ТФ (то же
    движение сожмётся в 100-140 баров). В первом черновике долга
    ошибочно записано наоборот («лупа») — Шеф поймал ошибку в
    терминологии по своему же канону, поправлено здесь. Числа не
    менялись, менялось только название направления починки.
    Разумная, непустая находка — но пока НЕ проверено на других
    инструментах/периодах, только один прогон.

  Согласие со старшим компасом (гл. этаж D1, global_trend):
    37 согласны, 70 не согласны, 23 без чёткого тренда — держится
    стабильно во всех прогонах сессии, включая §5к, ошибок метода
    в этой части не находил.

### НЕ доделано, помечено явно как слабое место

«Читается ли AO-структура внутри измеренного окна» (горб-3 → ноль-4
→ дивер-5 по порядку, критерий Мудреца 1 у Локи) — черновая проверка
в сессии слишком грубая: смотрит только «есть ли у AO вообще хоть
какой-то размах», не порядок горб→ноль→дивер. Дала 80% — ПОЧТИ
НАВЕРНЯКА завышено, использовать как факт НЕЛЬЗЯ. Нужно переписать
строже (переиспользовать логику из read_ao_wave_form: amax/amin +
zero_cross_after, но на СВОЁМ измеренном окне, не жёстких 120) и
перепроверить с нуля, на свежую голову.

### Итог сессии (5к+5л) для следующего захода

Твёрдо (проверено честно, готово опираться дальше):
- Порядок Искра → Ганс/Брут → Василий, роли не путать.
- Компас старшего этажа — рабочий метод, ~28% согласия на реальных
  кандидатах (много ложных «конец 5» вместо «конец C», подтверждено).
- Ганс/Брут: сторож strazh.py + точечное пробуждение — готово,
  проверено, лежит в /mnt/user-data/outputs/, не применено к репо.
- Царь-цена (окно 200 назад) — рабочая линейка ДЛИНЫ движения,
  разумный разброс на реальных данных.
- Василий = мини-Искра (Мудрец 1 малого масштаба), НЕ Мудрец 3
  повторно. Подтверждено сверкой с каноном, не только логикой.

Сырое, не доверять пока:
- Проверка AO-структуры внутри окна — переписать строже.
- Мини-Искра для Василия — even не начата архитектурно (только
  подтверждена как правильное направление).
- Первый будильник (Искра+Морж+Паникёр+Аван без Ганса) — понят,
  не применён к council.py.

*Решение Шефа (18.07, повторно): остановиться, дать голове отдохнуть
от третьей подряд правки линейки, вернуться на свежую.*

---

## 5м. Продолжение 5к/5л, тот же день 18.07 (поздний вечер) — ЧАСТОТА
##     СИГНАЛОВ, ПРОТИВОРЕЧИВЫЕ ЧИСЛА, НАЙДЕН БАГ КОМПАСА ПО ЭТАЖУ

*Прямое продолжение §5л. Сессия дала МНОГО чисел за вечер, часть из
них противоречат друг другу — записываю все как есть, без попытки
причесать в одну красивую историю. Разбираться на свежую голову.*

### С чего начался разговор

Шеф спросил: 4 сигнала/год на H4 (найдено в §5л) — это очень мало,
"даже смотреть в эту сторону не стоит". Разбирались, откуда частота,
не в вакууме — реальными числами по шагам.

### Числа, которые получились за вечер (ХРОНОЛОГИЧЕСКИ, чтобы видно
### было, как менялась методика)

1. **67 событий/год-эквивалент** (XAUUSD, полный проход, самодельная
   структура «царь+ноль+дивер» из lineyka.py, БЕЗ Сита-1) — оказалось
   позже, что это САМАЯ МЯГКАЯ проверка из всех, не самая честная.

2. **111 событий за 32 года EURUSD (3.47/год)** — тем же самодельным
   методом, тот же порядок что и XAUUSD (3.94/год). Хорошо, что два
   инструмента сошлись — но оба сделаны нестрогим методом.

3. **Настоящий bdb_strong ядра** (не самоделка, канонический детектор
   с резинкой+углом) на честно измеренном окне + жёсткий компас: 18
   сырых → 2 события за 17 лет. РЕЗКО ниже (1) и (2) — настоящий
   детектор строже самоделки, не мягче, как ожидалось.

4. **Тот же настоящий bdb_strong БЕЗ компаса** (компас снят как
   фильтр, оставлен справочно): 15 событий/17 лет (0.88/год). Из них
   компас СОГЛАСЕН только с 13% (2 из 15) — заметно НИЖЕ случайного
   совпадения, подозрительно.

### Лока принесла пересказ (предположительно) видео Котина — НЕ
### подтверждено

Документ от Локи утверждает: Котин использует старший ТФ не как
жёсткий фильтр «И», а как рекомендацию для размера позиции; редкость
сигналов (по его словам, «2-3 сделки в месяц с H4») — сознательная
плата за качество, не баг. Шеф прямо попросил не верить на слово —
проверил через web_search: **прямых подтверждений цитат не нашёл**,
более того — нашёл ПРОТИВОРЕЧАЩИЙ пример (метод Джо Росса использует
старший ТФ именно как жёсткий фильтр направления). Этот кусок канона
остаётся НЕПОДТВЕРЖДЁННЫМ пересказом, не фактом. Не использовать как
основание для решений без независимой проверки (например, прямого
транскрипта видео).

### Ошибка в рассуждении, пойманная Шефом одним вопросом

Сказал: «настоящий детектор, похоже, заточен на конец волны 5, а не
конец волны C». Шеф спросил в лоб: «а какая разница, в волне C та же
волна 5 есть?» — и это верно, разница пуста. Мы САМИ установили в
начале дня (картинки, фрактальность): конец волны C, приближенный на
свой масштаб, разворачивается в СВОЮ пятёрку — на конце её собственной
волны 5 будет ТОЧНО ТАКОЙ ЖЕ дивер, как на конце «настоящей» волны 5
старшего масштаба. Локально их отличить НЕЛЬЗЯ — отличает ТОЛЬКО
компас (по тренду / против тренда). Значит фраза про «заточен на 5»
была пустой, не находкой — компас остаётся единственным различителем.

### НАЙДЕННЫЙ БАГ (реальный, подтверждённый кодом, не гипотеза)

`global_anchor.senior_timeframe(working_tf)`: старший этаж = рабочий
×5 (в минутах), округление до ближайшей ступени лесенки СВЕРХУ.

  H4 (240мин×5=1200) → D1 (1440). Верно, так и использовалось весь день.
  H8 (480мин×5=2400) → D1(1440) НЕ ХВАТАЕТ, значит W1 (недельный)!
  H12 (720мин×5=3600) → тоже W1, не D1.

Все сегодняшние тесты компаса, включая походы по лесенке на H8/H12
(§5л, «поход по лесенке», 54 решённых подъёмом/спуском кандидата),
звали `global_trend('XAUUSD', 'H4', ...)` С ЗАХАРДКОЖЕННЫМ 'H4'
НЕЗАВИСИМО от того, на каком этаже реально стояла линейка. Для
H8/H12-измерений сверка шла с ДНЕВНЫМ трендом вместо ПРАВИЛЬНОГО
НЕДЕЛЬНОГО. Это могло исказить и число (3) («18→2»), и число (4)
(«15, согласие 13%») — насколько сильно, НЕ проверено, требует
переделки с правильным вызовом `global_trend(symbol, ФАКТИЧЕСКИЙ_тф,
as_of_date)`.

### Итог дня — честно, без причёсывания

Сегодня НЕ получилось одно твёрдое число «сколько сигналов в год».
Получилось четыре разных числа и один подтверждённый баг измерения
компаса. Это симптом того, что методика ещё сырая, не то, что стоит
тащить дальше на усталости. Разумно остановиться здесь.

### На завтра, по порядку

1. Переделать поход по лесенке (§5л) и оба bdb_strong-теста (3, 4) с
   ПРАВИЛЬНЫМ вызовом компаса — `senior_timeframe` от фактического
   этажа измерения, не всегда H4→D1.
2. После починки — перепроверить, держится ли разница между «настоящим
   детектором» и самоделкой lineyka.py, или причина в баге компаса.
3. Пересказ Локи про Котина (D1 как рекомендация, не фильтр) —
   ПРОВЕРИТЬ независимо (транскрипт видео, если доступен) прежде чем
   опираться на него; сейчас это непроверенный слух, не канон.
4. Держать в уме находку Шефа: локальная форма дивера НЕ различает
   конец C и конец 5 — только компас различает. Значит если баг
   компаса окажется серьёзным, вся сегодняшняя статистика по частоте
   нуждается в пересчёте с нуля, не в подгонке.

*Решение Шефа: остановиться, слишком много противоречивых чисел за
один вечер, разбираться на свежую голову.*

---

## 5н. Продолжение 5к/5л/5м, тот же день 18.07 (поздняя ночь) —
##     КАРТИНКА КОТИНА: ДВЕ ИСКРЫ ОДНОГО ЦИКЛА, ФРАКТАЛЬНОСТЬ ЗИГЗАГА,
##     ЦЕЛЕВАЯ ЧАСТОТА 10-15/ГОД

*Прямое продолжение §5м. Разбор одной картинки из материала FX Coach
(Котин), Шеф вёл по шагам, специально медленно ("не спеши, я
постепенно доведу"). Ничего не тестировалось в коде в этой части —
чистый разбор канона перед завтрашней перестройкой.*

### Картинка (11.png)

Дневной график, размечен вручную (толстая красная линия): внизу
слева — вертикальная линия и подпись «искра», справа, после полного
цикла 1-2-3-4-5 и зигзага A-B-C вниз — вторая вертикальная линия и
снова подпись «искра». Внизу — гистограмма AO.

### Разбор по шагам (Шеф вёл, не всё сразу)

1. **Искра стоит на ОБОИХ концах одного цикла**, не только на одном.
   Левая «искра» = конец предыдущего отката / начало текущего цикла.
   Правая «искра» = конец C ЭТОГО ЖЕ цикла (визуально «после волны
   5», но по сути — свой отдельный разворотник, не сама волна 5).
   Это НОВОЕ по сравнению с тем, что держали весь день — раньше
   Искру считали односторонней (только «конец коррекции, по тренду»).

2. **Вертикальная линия = конкретный БАР**, не область. Левее него —
   хвост старого отката, правее — уже пошла волна 1. Разворотник —
   один конкретный бар на стыке, не диапазон нескольких баров.
   Открытый вопрос себе: держит ли текущая линейка (izmerit_dvizhenie
   и структура) явное понятие «один бар-стык» — или только измеряет
   задним числом. НЕ проверено, отметить на завтра.

3. **Вершина волны 1 = перелом-экстремум = фрактал Ганса.** Конец
   волны 2 (низ первого отката) = рабочая точка Василия. Подтверждает
   архитектуру, которую строили весь день, картинкой Котина, не
   только логикой.

4. **Зигзаг A-B-C (правый спуск, после волны 5) — по структуре ТА ЖЕ
   пятёрка 1-2-3-4-5, что и вся большая волна, только зеркально, вниз**
   (форма та же, направление перевёрнуто, потому что сама волна C
   идёт вниз). Это и есть фрактальность, которую разбирали с самого
   начала дня по картинкам Шефа (Image 1/2) — теперь подтверждена
   ещё раз, на независимом материале Котина.

5. **Василий = та же работа, что Искра, только внутри уже идущей
   большой волны**, не на весь цикл целиком. Подтверждено картинкой,
   совпадает с выводом «Вася = мини-Искра» из более ранней части дня
   и с живым примером на баре 13189 (§5л).

### Возможное большое следствие для завтра — ПОД ВОПРОСОМ, не решено

Если Искра ловит ОБА конца цикла (низ и верх), а не только «разворот
по тренду старшего этажа» — тогда весь фильтр компаса, который
строили и тестировали весь вечер (§5м, «компас как жёсткие ворота»),
возможно, был **неверно поставленной задачей с самого начала**, не
просто багом по этажу (H8/H12 сверялись не с тем старшим — тот баг
тоже реален, остаётся в силе). Компас тогда — не фильтр ДЛЯ САМОЙ
Искры, а информация для того, ЧТО ДЕЛАТЬ ДАЛЬШЕ с уже найденной
точкой (какая роль её подхватывает — Аван на разворот вверх, кто-то
симметричный вниз). НЕ РЕШЕНО, требует разговора с Шефом отдельно,
до того как переписывать фильтр.

### Целевая частота — ориентир Шефа, не мой расчёт

На дневках цикл 100-140 баров укладывается в год 3-4 раза. В одной
дневной свече — 6 четырёхчасовых, значит на H4 сопоставимых по
калибру структур пропорционально больше: **ожидание 20-24 сигнала до
фильтров, 10-15 после (тренд и т.д.), минимум 10.**

Все сегодняшние числа (§5м: 67/год самоделкой, 2-4/17лет настоящим
детектором с разными фильтрами) — заметно НИЖЕ этого ориентира, даже
самое щедрое. Вывод не «метод плохой», а «метод сегодня СИСТЕМНО
недосчитывает» — по крайней мере по двум причинам уже названным
(баг этажа компаса; возможно неверная постановка компаса как жёстких
ворот вместо доп.информации). Ориентир 10-15/год — цель для сверки
ПОСЛЕ починки, не сегодняшняя претензия к цифрам.

### На завтра (дополняет список из §5м)

1. (из §5м) Починить вызов компаса — старший этаж от ФАКТИЧЕСКОГО
   этажа измерения, не всегда H4→D1.
2. (новое) Обсудить с Шефом ДО кода: компас — жёсткий фильтр входа в
   Искру, или информация для роли/направления ПОСЛЕ того как точка
   уже найдена? Картинка Котина намекает на второе.
3. (новое) Проверить, есть ли в линейке явное понятие «бар-стык»
   (один конкретный разворотный бар), не только измерение окна
   задним числом.
4. После обеих починок — сверить итоговую частоту с ориентиром
   10-15/год, не с сегодняшними цифрами.

*Решение Шефа: следующая сессия — новая, не эта. Эта осталась как
живая история дня (включая ошибки и их починку), новая начинается
с чистого набора долгов §5к-5н.*

---

## 5о. Продолжение 5к/5л/5м/5н, сессия 18.07 (следующий заход) —
##     КАНОН ВЫПРАВЛЕН, ЦАРЬ-ЦЕНА ПОХОРОНЕНА, ЛИНЕЙКА ЧЕРЕЗ НУЛИ AO,
##     ОКНО 100-140 ПРИЗНАНО НЕ ФИЛЬТРОМ, ДОЛЯ СТРУКТУРЫ ~1/3 ВЕЗДЕ

*Новая сессия с чистого набора долгов §5к-5н, как решил Шеф. Разговор
шёл от канона к коду: сперва Шеф выправил несколько моих вчерашних
ошибок в понимании, потом мерили на живых данных из репо. Всё
проверено в песочнице, к репо ничего не применено.*

### ЧАСТЬ 1 — КАНОН: что Шеф выправил (мои ошибки, не рынка)

**1. Искра ловит ОДИН конец, не два.**
Вчера (§5н) я записал по картинке Котина, что Искра стоит на обоих
концах цикла. Шеф поправил: она ловит конец волны C, один. Левая
«искра» на картинке — конец ПРЕДЫДУЩЕГО цикла, тот же самый конец C,
только прошлого зигзага. Одна работа, повторяющаяся из цикла в цикл.

**2. Волна 5 внутри волны C — не отдельное событие.**
Следствие фрактальности: дивер на конце внутренней волны 5 и есть
дивер конца C. Значит фраза из §5м «локально не отличить конец C от
конца 5, отличает только компас» — ПУСТАЯ. Отличать нечего.

**3. Компас — ориентир, не ворота.**
Прямое слово Шефа: «компас..он и есть компас для ориентира». Как
Аллигатор, как AO — кладёт факт на стол, не запирает дверь. Жёсткое
«И» из §5м снимается. Это объясняет провал вчерашних чисел: настоящий
детектор дал 15 событий/17лет БЕЗ компаса и 2 С компасом — ворота
выкашивали 87% честных точек.

**4. Рабочий ТФ — настройка, не истина.**
«Система не должна спрашивать у трейдера, какой тф работать, она
должна работать тот тф, который комфортный». H4 нигде не хардкодить,
приходит параметром.

**5. Разворотник и раскладка волны — РАЗНЫЕ вещи (я их склеил).**
- Разворотник (бар-стык, точка Искры): рабочий ТФ, проверка соседним
  этажом на шаг туда-сюда. Заявка Авана — по бару рабочего ТФ.
- Раскладка структуры (горб-3 → ноль-4 → дивер-5): читается на том
  этаже, где движение легло в окно. Это ОПТИКА, не место торговли.
Мой «Вариант А» вчера был про раскладку, а я натянул его на всю
цепочку Совета — лишнее. Совет остаётся на рабочем этаже.

**6. Регламент лесенки (резолюция Шефа, снимает противоречие §5н):**
- потолок — ОДИН этаж вверх (H4→D1), дальше не лезем;
- подтверждение на старшем — не дивер, а АНГУЛЯЦИЯ (где цена
  относительно Аллигатора). Не отброс, а РАНГ: с подтверждением
  «золотой вход», без — «спекулятивный», меньшим лотом;
- кандидат без структуры ни на одном этаже — отброс молча, без
  «слабых» меток. «Отброс — это не ошибка, это защита депозита».

### ЧАСТЬ 2 — ЛИНЕЙКА: царь-цена выброшена, мерим от нулей AO

**Царь-цена (§5л, окно 200 назад) — МЕРТВА.** Была моей самоделкой,
костылём на один день. Замена по канону: движение рождается на
пересечении нуля AO, кончается на дивергентном баре.

Прогоны на живых данных репо (`Биржа/test_data/`, реальное ядро
`williams_core.py`, детектор `bdb_strong`, окно расчёта 120):

**Через ОДИН ноль** (ближайшее пересечение назад):
  XAUUSD H4: медиана 22, в окне 100-140 — 3 из 130 (2%)
  XAUUSD H1: медиана 23, в окне — 3 из 452

  → величина ИНВАРИАНТНА к этажу (22 и 23!). Это период самого AO
    (5/34 на медиане), а не длина волны. Спускаться/подниматься по
    лесенке с этой линейкой БЕССМЫСЛЕННО — везде одно и то же.
    Здесь умерла моя гипотеза «22×6=132, родной этаж H1» — она была
    арифметически верна и методологически пуста (AO на H1 считает по
    своим барам, а не по спроецированным H4).

**Через ДВА нуля** (канон горб-3 → ноль-4 → дивер-5):
  XAUUSD H4: медиана 48, в окне 15 из 130 (12%)
  XAUUSD H8: медиана 44 | H12: медиана 40

  → медиана НЕ растёт при подъёме по лесенке, даже слегка падает
    (47→44→40). «Родного этажа», где она сядет в 100-140, НЕТ.
    Здесь умерла вторая моя гипотеза («медиана 47 × 2.5 = H8/H12»).

**Профиль по числу нулей (XAUUSD H4), полная картина:**

  N нулей | медиана | в окне 100-140 | >140
     1    |   22    |   3 (2%)       |  0
     2    |   48    |  15 (12%)      |  2
     3    |   68    |  26 (20%)      | 11
     4    |   94    |  31 (23%)      | 27
     5    |  116    |  33 (25%)      | 48

  Шеф предсказал для N=4 медиану ~94-100 — попадание точное.
  НО: рост МОНОТОННЫЙ, ~23 бара за каждый ноль, ничего не «щёлкает»
  на N=4. Отмечено честно как риск подгонки: мы нашли не структуру
  длиной 94, а число нулей, дающее нужный ответ.

### ЧАСТЬ 3 — ПРОВЕРКА СТРУКТУРЫ (то, что решило вопрос)

Чтобы отличить физику от подгонки, написана СТРОГАЯ проверка
(`proverit_strukturu.py`, песочница). Вчерашняя проверка из §5л
давала 80% и была помечена «не доверять» — теперь понятно почему:
`read_ao_wave_form` в ядре смотрит лишь «есть царь-горб» и «после
него где-то есть ноль» — условие почти всегда истинное.

Строгий протокол (продиктован Шефом): горб-3 → ноль-4 → дивер-5 по
порядку индексов + правило Эллиотта (третья волна не короче пятой)
+ брак при лишних пересечениях нуля.

**СОБСТВЕННАЯ ОШИБКА, найденная и починенная ДО показа Шефу:**
первый прогон дал 16/31 при однородном браке «нет ноля после горба»
у всех 15 отказов. Однородность = подпись бага, не свойство рынка.
Причина: горб-3 искался как глобальный экстремум ВСЕГО окна и часто
попадал в волну 5 (у неё AO бывает сильнее) — тогда ноля после него
физически нет. Починка: ноль-4 = ПОСЛЕДНЕЕ пересечение в окне, горб-3
ищется ДО него, дивер-5 ПОСЛЕ. После починки число не изменилось
(те же 16/31), но брак стал осмысленным: «волна 5 сильнее волны 3».
То есть первый результат был верен случайно, теперь верен по сути.

**ШЕСТЬ ПРОГОНОВ — итоговая таблица:**

  этаж | XAUUSD: %структ / золотых в год | EURUSD: %структ / в год
   H4  |        51%  /  1.4              |     35%  /  1.0
   H1  |        38%  /  4.8              |     42%  /  5.7
   M30 |        32%  /  7.0              |     29%  /  8.1

  контроль (структура у ВСЕХ кандидатов, без фильтра по окну):
   XAU 36/31/34,  EUR 30/33/29 — почти ровно везде.

### ЧАСТЬ 4 — ВЫВОДЫ, НА КОТОРЫХ МОЖНО СТРОИТЬ КОД

**1. Окно 100-140 — НЕ фильтр.**
Прирост от попадания в окно: XAU H4 +15 п.п., H1 +7, M30 -2;
EUR H4 +5, H1 +9, M30 0. То есть на одних клетках полтора раза, на
других — статистический шум. Фильтром это быть не может. Окно —
визуальная рекомендация для глаза трейдера (третий исход, который
Шеф сам допустил заранее). В код идёт НЕ порог по длине, а факты:
`dlina` числом + `struktura_chitaetsya` True/False. Как `tension_ratio`
у Моржа — число на стол, не да/нет.

**2. Доля годной структуры ~1/3 — ВЕЗДЕ.**
Шесть прогонов, два инструмента, три этажа: 29-42%, контроль 29-36%.
Не зависит ни от актива, ни от этажа. ЭТО и есть универсальность
метода — не 51% (та клетка оказалась просто самой удачной из шести),
а устойчивая треть. Проверка структуры отсекает ~2/3 кандидатов по
ОСМЫСЛЕННОЙ причине (волна 5 сильнее волны 3 = там не пятёрка или
мы не в её конце), а не по числу баров.

**3. Частота — линейная функция этажа, «родного этажа» не существует.**
1.4 → 4.8 → 7.0 (XAU) и 1.0 → 5.7 → 8.1 (EUR) при спуске H4→H1→M30.
Полки нет. Ориентир Шефа 10-15/год лежит между M30 и M15.
ВАЖНАЯ ОГОВОРКА (моя, Шефом не подтверждена): 10-15 крупных на H4 и
10-15 мелких на M15 — РАЗНЫЕ системы. Ориентир 10-15 выведен из
дневного цикла, спроецированного на H4, то есть из крупного калибра.
Достигать его спуском — значит менять калибр сделок. Спред и комиссия
при этом те же, а движение короче. Решение за Шефом, не измерением.

**4. Частота после снятия ворот компаса (XAUUSD H4):**
  130 кандидатов / 11.3 года = 11.5/год — ПОПАДАНИЕ в ориентир 10-15
  из них со структурой = 47 = 4.2/год (высший ранг)
  в окне И со структурой = 16 = 1.4/год («золотые»)
Против вчерашних «2 события за 17 лет». Разница вышла из снятия
жёстких ворот компаса, а не из починки одной вещи.

### ЧАСТЬ 5 — СУДЬБА ВЧЕРАШНИХ ФАЙЛОВ

- **`Биржа/strazh.py` — ЖИВ, уже в репо** (подтверждено чтением
  репозитория). Решает другую задачу: Совет проснулся один раз, а
  фрактал волны 1 родится через 4-25 баров. Дыра §5к сегодняшним
  разговором НЕ закрыта, сторож нужен. Функция
  `uslovie_otkat_do_urovnya` — выбросить: Василий не сторож на
  уровень, а мини-Искра (§5л).
- **`lineyka.py` / царь-цена — выбросить.** Заменена измерением от
  нулей AO.

### НА СЛЕДУЮЩИЙ ЗАХОД

1. Решить (Шеф): на каком этаже живёт город. Числа говорят H1 или
   ниже для частоты, H4 для калибра. Это ВЫБОР, измерение своё
   отработало.
2. Снять жёсткий компас с входа в живом коде (сейчас только
   проговорено, к репо не применено).
3. Убрать `uslovie_otkat_do_urovnya` из `Биржа/strazh.py`.
4. Вживить измерение от нулей AO + проверку структуры в ядро как
   ФАКТЫ на стол (не как фильтр).
5. Открытым остаётся с §5к: первый будильник (Искра+Морж+Паникёр+Аван
   без Ганса) — понят, не применён к `council.py`.
6. Открытым остаётся с §5к: мини-Искра для Василия — не начата,
   отдельная стройка размером с саму Искру.
7. Пересказ Локи про Котина (§5м) — по-прежнему НЕПОДТВЕРЖДЁННЫЙ
   слух. Но сегодня пришёл с другой стороны: регламент «старший ТФ =
   ранг/размер позиции, не ворота» совпал с ним. Совпадение отмечено,
   независимой проверки всё ещё нет.

*Скрипты сессии: `izmerit_ot_nulya_ao.py`, `proverit_strukturu.py` —
песочница, к репо не применены, ждут решения Шефа.*

---

## 5п. Сессия 18.07 (весь день) — КОМПАС СНЯТ С ВОРОТ, ИЗМЕРЕНИЕ ВОЛНЫ
##     ВЖИВЛЕНО, ДНЕВНИК ПЕРЕСТАЛ ЗАГЛЯДЫВАТЬ В БУДУЩЕЕ. ШЕСТЬ ПАТЧЕЙ
##     В РЕПО, ПРОВЕРЕНЫ РЕГРЕССИЕЙ И ЖИВЫМ ТЕСТЕРОМ.

*Прямое продолжение §5к-5о (тот же день, до этого — чистый разбор
канона в песочнице). Здесь — код, применённый к живому репо, и первый
полный прогон Совета после правок. Шеф пушил патчи, тестер гонял
живой EURUSD H4.*

### ШЕСТЬ ПАТЧЕЙ, ВСЕ ПРИМЕНЕНЫ, ВСЕ ПРОВЕРЕНЫ ДО ОТПРАВКИ

1. **`patch_strazh_bez_chernovika.py`** — убран мёртвый черновик
   `uslovie_otkat_do_urovnya` из `Биржа/strazh.py` (гипотеза «Василий
   ждёт касания уровня» отменена ещё в §5к). `nablyudat_za_tochkoy` и
   `uslovie_novy_fraktal` нетронуты, живы.

2. **`patch_kompas_ne_vorota.py`** — сняты ЖЁСТКИЕ ВОРОТА компаса в
   мозге Искры (`_descend`, `мозг.py` A01). Было: спуск засчитывал
   точку ТОЛЬКО если `bdb_dir == compass`, иначе шёл глубже до дна M5;
   «нет компаса» = «нечего ловить» (спуск не начинался вовсе). Замер
   на живой истории: с воротами — 2 события/17 лет, без — 15. Ворота
   выкашивали до 87% честных точек. Теперь спуск ищет точку ЛЮБОГО
   направления, компас кладётся рядом как ранг (`soglasie`
   True/False/None), не как условие прохода.

3. **`patch_kompas_dostavka_treyderam.py`** — найдена и закрыта ТИХАЯ
   дыра, вскрытая вопросом Шефа «в мозге у искры не нужно ничего
   поправить?»: до патча 2 `trend_direction` и `compass` были
   принудительно равны (старые ворота требовали `bdb_dir==compass`),
   поэтому trader-поле `anchor.global_trend` могло читать любое из
   двух — они совпадали. После патча 2 это стало ДВУМЯ РАЗНЫМИ
   фактами, а трейдеры (A06/A07/A08) продолжали читать
   `trend_direction` под именем «компас» — то есть видели эхо
   направления своей же точки, а не независимый факт старшей воды.
   Патч: Искра сохраняет `compass`/`soglasie` отдельными полями в
   `trading_state`, трейдеры читают именно их.

4. **`patch_iskra_wave_measure.py`** — в `williams_core.py` вживлены
   `izmerit_volnovuyu_strukturu` (длина движения от 4-го пересечения
   нуля AO назад, канон Шефа — полный цикл 1-5) и
   `sudit_volnovuyu_strukturu` (строгая проверка горб-3→ноль-4→дивер-5,
   починка от 18.07: горб ищется ДО последнего ноля в окне, не как
   глобальный экстремум окна — иначе часто попадает в волну 5).
   `wave_form` получил поля `dlina`/`struktura_chitaetsya`/
   `struktura_prichina`. ПРОВЕРЕНО РЕГРЕССИЕЙ на всех шести живых
   прогонах дня (XAU/EUR × H4/H1/M30) ДО применения к репо — числа
   совпали день-в-день с прогонами в песочнице (47/130, 57/189,
   142/452, 177/522, 152/446, 69/236). Окно 100-140 НЕ используется
   как порог — только факты на стол (закон дня: окно слабо коррелирует
   со структурой на XAU +15 п.п., почти никак на EUR +5 п.п. —
   недостаточно для ворот).

5. **`patch_wave_measure_dostavka.py`** — доставка `dlina`/
   `struktura_chitaetsya` тем же маршрутом, что компас (патч 3):
   `_descend` → `v2_descent` → `trading_state` → промпт Искры →
   `sensors.iskra` у трёх трейдеров. Без этого патча факты
   вычислялись, но никуда не уходили — та же дыра, что была с
   компасом.

6. **`patch_dnevnik_bez_budushchego.py`** — НАЙДЕНО В ЖИВОМ ТЕСТЕРЕ
   (не в песочнице): Аван на баре 2000.12.08 сравнил в narrative два
   случая из памяти — «1999.12.31 (-1R) дороже, чем 2011.08.01
   (+3.29R)». Текущий бар теста — декабрь 2000, сделка 2011 года ещё
   не могла случиться в хронологии прогона. Причина проверена, не
   гипотеза: `_read_recent_diary(n)` читает последние N строк ФАЙЛА
   без разбора дат; `tester_express.py` НИКОГДА не сбрасывает
   `diary_*.jsonl` между прогонами — дневник копится в реальном
   времени, а не в времени теста. Патч добавляет `as_of_bar_time`,
   фильтрует события по `bar_time <= as_of_bar_time` ДО взятия
   последних n. Проверено не только компиляцией — воспроизведён баг
   на игрушечном дневнике с теми же датами (1999/2011), подтверждено:
   без фильтра баг воспроизводится, с фильтром пропадает.

### ЖИВОЙ ТЕСТЕР (EURUSD H4, 10 кандидатов) — ЧТО УВИДЕЛИ

10 кандидатов, 9 DETECTED + 1 NOT_FOUND. Три ордера: Брут SHORT
(1999.11.04, закрыт -1R), Аван LONG дважды (1999.12.31 закрыт -1R;
2001.08.24 остался открыт на конец лога). Структура и компас
подтверждённо ДОЕХАЛИ до голоса Искры («структура читается: горб-3 →
ноль-4 → дивер-5 на 115 барах», «на 131 бар»; «Компас null — нет
запрета») и до `trading_state.json` (`dlina: 68,
struktura_chitaetsya: false` на баре, где Искра сама сказала
«не читается строго» — поле живое, не заглушка).

Мелкая находка, не патчено: Искра в narrative иногда описывает спуск
по лесенке («прошёл D1→H12→H8→H4»), которого в этом прогоне не было
(сработал главный путь — точка сразу на рабочем этаже, `_descend` не
вызывался вовсе). Голосу это разрешено (`narrative` может рассуждать
шире факта), но если повторится системно — стоит подрезать промпт,
чтобы не выдумывал механику.

### НАЙДЕНО, НЕ ПОЧИНЕНО (архитектурный долг, НЕ сегодняшнего дня)

**Консерватор (Василий) — 10/10 отказов в живом прогоне, всегда одна
причина: «волна 1 не утверждена Моржом».** Разобрано ошибочно в
начале обсуждения (я сам сказал «мини-Искра, это отдельный
неначатый долг») — ПОПРАВЛЕНО чтением `БИРЖА.md`: канон уже
переработан раньше, в §5и (ночь 17-18.07, ДО сегодняшней сессии), не
в сторону «мини-Искры», а в сторону ЦЕПИ:
  - Искра + Авантюрист — разворот в конце волны C, вход в зарождение
    волны 1
  - Ганс + Брут — ПЕРВЫЙ ФРАКТАЛ ПОСЛЕ точки Искры закрепляет: импульс
    начался
  - Василий — ждёт откат волны 2 ОТ ЭТОГО ФРАКТАЛА (не от
    `wave_1_validated`), входит в начало волны 3

Диагноз из §5и (подтверждён сегодня независимо, тем же выводом:
`_descend` имеет только `NOT_FOUND`/`DETECTED`, ветки `CONFIRMED` НЕТ
— `wave_1_validated` физически недостижим живым механизмом).

Три точных адреса в коде (из §5и, не сделаны):
  a. `williams_core.py :: detect_fractals()` — отдаёт просто последний
     фрактал в окне, без привязки «после какой точки разворота»
  b. `A02/промпт.md :: wave_1_validated` — заменить условие фазы 1
     Василия с «Морж подтвердил волну 1» на «Брут закрепил первый
     фрактал после точки Искры»
  c. `iskra_live.py :: _descend()` — критерий остановки спуска сделать
     АРИФМЕТИЧЕСКИМ (окно 100-140 заполнено), не СИГНАЛЬНЫМ
     (`bdb_dir == compass`) — перекликается с сегодняшним выводом,
     что окно 100-140 не работает как жёсткий фильтр входа, но здесь
     это ДРУГОЕ его применение (критерий остановки спуска, не ворота
     на входе)

Статус из §5и, актуален и сегодня: НЕ ПОЧИНЕНО. Оценка калибра —
«архитектурная правка калибра Моста Ведения или крупнее — трогает
Искру (шаг 1 из 9), Ганса/Брута и Василия разом». Решение — следующая
сессия со свежей головой, не хвост этой.

### НА СЛЕДУЮЩИЙ ЗАХОД

1. Прогнать тестер ещё раз с шестым патчем (дневник) — посмотреть,
   изменилось ли поведение трейдеров без доступа к будущим записям.
2. Архитектурная правка Василия (три адреса a/b/c выше) — калибр
   Моста Ведения, отдельная сессия.
3. Проверить, не повторяется ли у Искры путаница голоса про спуск,
   которого не было (мелкая находка выше) — если да, подрезать
   промпт.
4. Открытым остаётся с §5к: первый будильник (Искра+Морж+Паникёр+Аван
   без Ганса) — понят, не применён к `council.py`.
5. Пересказ Локи про Котина (§5м) — по-прежнему непроверенный слух,
   независимой проверки всё ещё нет.

*Решение Шефа: сессия длинная (6 патчей + находки), риск потерять
нить в скролбэке — переходим в новую сессию.*

---



## 6. Что реально живо (проверено, не на словах)

- Кабинет открывается, отдаёт 200, без ошибок в логе.
- Прописка резолвится: слот → резидент → аватар/имя в пузырьке.
- **Все девять мозгов** реально грузятся из своих слотов, читают
  свой промпт и знания, пишут свою статистику, отвечают через живую
  LLM — подтверждено реальными прогонами тестера (не заглушкой).
- `trading_state.json` читается и пишется по адресу
  `GRONDHEIM_CITY/Биржа/данные/trading_state.json`.
- Полный цикл Совета проверен живьём: Сито 1 → спуск Искры → Совет
  собирается → трейдеры выносят вердикт → Исполнитель считает ордера
  → сделка открывается и видна лентой в кабинете (подтверждено:
  «🟢 ОТКРЫТА: AVANTURIST LONG @ 1203.85» — реальный прогон 11.07).
  **Поправка (вечер 11.07, §5в п.1):** на момент этой записи лента
  видела только открытия — закрытия («🔴 ЗАКРЫТА») были слепы из-за
  отдельного дрейфа пути в `tester_express._read_last_closures`.
  Позиции при этом реально закрывались (settle отрабатывал), просто
  кабинет об этом не узнавал. Пофикшено тем же вечером, подтверждено
  живым прогоном — пары ОТКРЫТА/ЗАКРЫТА видны честно.
- UI кабинета отзывчив на каждом агенте цепочки — портрет, окно
  отчёта, пузырьки хедера, поле «ловить» видно и рисуется корректно
  (§5в п.4).
- Сито-1 на младших ТФ (H1: 94 566 баров) больше не виснет —
  устранён катастрофический перечит CSV старшего этажа на каждый бар
  (§5в п.3). Подтверждено: 145 кандидатов найдено за разумное время.
- Компас-дисциплина трейдеров подтверждена живым текстом рассуждений
  (§5в п.7): направления входов идут по знаку компаса, не «почти
  всегда LONG», как было до патча.
- **Эдж системы пока НЕ доказан.** Первый прогон после компас-патча:
  10 закрытых сделок, 40% в плюс, суммарно −3.16R (§5в, честный итог).
  Маленькая выборка — не приговор, но и не победа. Нужна выборка на
  порядок больше.

**Добавлено 12.07 (§5г):**

- **Все девять сидят за столом СОБОЙ.** `proverka_soveta.py` на живом
  диске: 9 живых душ, 0 вакансий, 0 мёртвых импортов `studio.*`.
  Каждый мозг читает своего носителя по маске (Закон Пары), пара
  берётся ИЗ ПУТИ мозга — ни одного хардкода личности.
- **Натура влияет на ГОЛОВУ, не только на текст.** Температура модели
  считается из заряда и натуры носителя: Илья t=0.58, Вера t=0.57,
  Брут t=0.59 — у каждого своя. `stress_to_temperature()` была мёртвой
  функцией с эпохи `-2` (её не звал НИКТО).
- **Нога Опыта работает на живых деньгах.** Заряд Ильи (−0.147) и Брута
  (+0.007) записаны настоящими закрытыми сделками, рукой рынка,
  подтверждено `mtime` паспортов (12.07 18:44 и 20:30).
- **Илья опирается на свой опыт вслух** — живой текст прогона: *«Мой
  опыт кричит: без squat и мощного бычьего тела это не конец волны C.
  Опираюсь на свои же якоря»*. До сессии он не мог: душа была пуста.
- **Ошибки больше не молчат.** Сбой Искры печатается наравне со всеми
  (`KRIK_ISKRY_V1`), а `council` не выдаёт «Искра упала» за «спуск не
  нашёл точку». Это, возможно, ценнее остальных патчей: следующая
  поломка не будет стоить четырёх часов раскопок.

---

## 7. Что честно не построено

**ЗАКРЫТО в сессии 12.07 (было главным долгом трёх снимков подряд):**
- ~~нога «Опыт» Стола Трейдера~~ → построена (§5г), два яруса якорей,
  суд по Котину, дыхание на каждой сделке;
- ~~мост к душе жителя физически мёртв~~ → `Биржа/nositel.py`, все
  девять мозгов ходят в него;
- ~~«Вера/Илья — имена и текст промта поверх голого вызова LLM»~~ →
  теперь резиденты в смысле Чертежа: род, натура, заряд, опыт, судья.

**Что осталось и появилось:**

- **НОВЫЙ, архитектурный (16-17.07, §5з.8): у Василия нет аналога
  отложки для СВОЕГО момента.** Совет полностью собирается только на
  редких кандидатах Искры; Брут/Илья получают честный шанс (Брут — за
  счёт того, что его заявка живёт и проверяется на всех следующих
  барах). Василий, сказав «рано» один раз, не имеет механизма
  «продолжить наблюдение» — следующий шанс только на следующем
  случайном развороте, месяцы спустя. НЕ ПОЧИНЕНО, решение отложено
  до отдельной сессии (маленькая стройка калибра Моста Ведения).
  Направление намечено: «наблюдение» по условию (волна 1 утверждена),
  а не по цене — будит точечно Василия, не весь Совет.
- **Суд сенсоров построен, но на живом диске НЕ ОТРАБОТАЛ ни разу.**
  Механика проверена на зеркале (все четверо признают своё слово), но
  прогоны 12.07 встали на 402 (кончился баланс OpenRouter) раньше, чем
  позиция успела открыться и закрыться ПОСЛЕ патча слепка. Слепок
  кладётся при ОТКРЫТИИ, судится при ЗАКРЫТИИ — старые позиции несут
  пустой слепок и не починятся. **Первое, что надо увидеть в
  понедельник:** строку `[МОСТ] 📝 черновик → Вера (A01): «МОЯ
  ОШИБКА...»` в живом логе.
- ~~**Нога Опыта ни разу не протекла**~~ → **ЗАКРЫТО 14.07** (§5е).
  ПОТЕКЛА. Метки 2, маяки 5. Вера и Ганс носят «моё слово повело в
  минус» — заработано их убытком. Илья ссылается на свои сделки по
  датам и **отличает похожее от обманчиво похожего**.

- **⚡ КЛЮЧ СЕНСОРОВ ВЫРОЖДЕН — главный долг после 14.07.**
  Все пять маяков сенсоров легли под ОДНИМ паттерном: `сенсор_ошибка`.
  У Веры, Ганса, Моржа, Паникёра — **один-единственный ключ на все
  случаи жизни**. Значит метка Веры на деле говорит «я ошиблась
  трижды», а НЕ «я ошибаюсь, когда даю BULL при спящем Аллигаторе».
  **Это счётчик, а не вывод.**
  *Сравни с трейдерским ключом — он богатый:* `трейдер_плюс_по_ветру`
  (есть исход И условие). Судья трейдеров различает, судья сенсоров —
  нет.
  **ЧЕМ ГРОЗИТ АКАДЕМИИ НАПРЯМУЮ:** механизм различения учеников — это
  ключ паттерна (`тема × натура`). На вырожденном ключе десантник и
  скромная получат ОДИНАКОВУЮ метку «я учился». **Критерий приёмки
  провалится не из-за школы, а из-за ключа.**
  **Лечение:** ключ должен нести УСЛОВИЯ, а не только исход:
  `искра:BULL:аллигатор_спит` вместо `сенсор_ошибка`. Тогда Вера
  накопит РАЗНЫЕ метки — и это станет знанием, а не счётом.
- **`MEMORY_REQUEST` на Бирже — построен, живьём пока не сработал.**
  Ждём `[МОСТ] 🧠 ... вспоминает`. Честно: архив трейдеров ещё почти
  пуст — вспоминать нечего. Метки накопятся — начнут просить.
  *(Но Илья уже ссылается на дневник по датам — память РАБОТАЕТ, просто
  через другой канал.)*
- **Контора (Арчи, Сергей) — душу читает, суда не имеет.** Они не
  сидят за торговым столом: Архивариус — память Биржи, Исполнитель —
  казначейство. Что для них значит «опыт» — архитектурный вопрос, не
  механика. Сознательно отложено, не забыто.
- **Контекст промпта — 25 242 символа на агента.** Это ~7 000 токенов
  ВХОДА. Резерв (`max_tokens`) починен, но расход никуда не делся.
  Подозрение: тащится целиком либо база знаний, либо дневник роли.
  **Первый кандидат на удешевление прогонов.**
  *Уточнение 13.07:* метки контекст **не раздувают** — в промпт идут
  только **свежие 4**, остальное поднимается по `MEMORY_REQUEST`.
  И девять агентов будятся **не на каждом баре**: Сито 1 (математика,
  без LLM) просеивает 24к баров и отдаёт горстку Точек Ноль.
- ~~**Заряд ничем не остужается, кроме нового вдоха**~~ → **ЗАКРЫТО
  13.07** (`SUTOCHNY_TIK_V1`, §5д). Тает от реального времени,
  полураспад = сутки × (1 + упрямство). Лока вышла из четырёхдневного
  аффекта: +0.874 → +0.135, архив закрылся. `tik.py` — ручной выдох
  города (цикла у города нет, `main.py` только рисует страницы).
  **Задел:** заработает Биржа — привяжем к сессиям, подменится только
  `_seychas()`, формула не тронется.
- **`_settle_positions()` не подключена к живому пути РЫНОК.** Найдено
  11.07, **всё ещё не пофикшено**: `wake_council()` нигде не зовёт
  закрытие позиций по стопу/колоколу — вызов живёт только в CSV-пути и
  в тестере. Через кнопку РЫНОК позиции **не закрываются
  автоматически**. Критично: касается реальных денег. **Теперь ещё
  критичнее** — без settle не будет ни суда, ни опыта, ни заряда.
- **Эдж системы не доказан** (§5в, §6) — 10 сделок дали −3.16R при 40%
  побед. Нужна выборка на порядок больше.
- **Атлас-патч (§5в п.2) доставлен, эффект не подтверждён** живыми
  данными — нужен прогон на большей выборке.
- ~~**Реверсивная пирамида (§5в п.8) доставлена, живым прогоном не
  подтверждена.**~~ → **ПОСТРОЕНА 15-16.07** (§5ж): мост ведения
  (`MOST_VEDENIYA_V1`), пакетный расчёт R (`PAKET_PYRAMIDA_V1`),
  дисциплина убывающих ног (`REVERSE_PYRAMID_DISCIPLINE_V1`). Малые
  прогоны подтверждают механику (доливка реально меняет позицию, отказ
  реально гасит нарушителя); честный эдж на большой выборке — впереди.
- **Городская память через Олю** — решением от 03.07 не строится
  («каждый держит свой архив сам»). Не долг, сознательный выбор.
- **Модель у всех ОДНА** (`OPENROUTER_MODEL` из `.env`). «Агент сам
  выбирает модель из своей ДНК» — открытый пункт со Спринта 26.
  Разговор про деньги и качество, не тихий патч. Температуру подключили
  (§5г п.10), модель — нет.
- **MT5-терминал** — не проверяется с моей стороны (Windows, машина
  Шефа). Всё до этой границы честно проверено; за ней — на слово кода и
  живых прогонов.
- **Дашборд `/dashboard` со вкладкой Биржа** — макеты были, решение
  отложено.

### ⚠ ВАЖНО ДЛЯ НОВОЙ СЕССИИ: школу трейдинга в Бирже НЕ СТРОИТЬ

12.07 (ночь) Шеф поставил задачу **Академии Грондхейма** — общегородской
школы, где житель рождается человеком и **сам осваивает профессию**
(в т.ч. трейдинг). Замысел зафиксирован отдельным документом:
**`АКАДЕМИЯ_ГРОНДХЕЙМА.md`**.

**Академия — сущность НАД кварталами** (Шеф: «курсы по трейдингу И для
студии для медийщиков»). Биржа становится **потребителем выпускников**,
а не местом их рождения. Если строить «школу трейдинга» внутри Биржи —
получится местное решение там, где нужно общее, и переписывать придётся
при первом же факультете медиа.

**Старую девятку (Илья, Вера, Морж...) Академия НЕ трогает** — у них
настоящий заработанный рынком опыт (заряд, якоря). Они остаются
памятником до-академической эпохи. Учиться будут **новые** жители.

---

## 8. Где что лежит (карта файлов)

```
Биржа/                                    ← общий код квартала
  ui_torg.py                               кабинет (вход)
  cartridge_registry.py                    Закон Пары/Картриджа (вход)
  council.py                               единая дверь пробуждения Совета
  williams_core.py, mt5_feed.py,
  feed_source.py, global_anchor.py,
  hooks.py, tester_express.py              движок (общий, не в подпапках)
  nositel.py                               ← МОСТ К НОСИТЕЛЮ (12.07)
  llm.py, billing_ledger.py                LLM-клиент и учёт
  данные/                                  ATLAS/STATE/PNL + feed_config.json

КОРЕНЬ РЕПО (ASCII-имена — PowerShell ест кириллическую «Б»):
  proverka_ucheby.py     ← главная диагностика: патчи + заряды + якоря
  proverka_soveta.py        кто за столом, температура, мёртвые души
  proverka_koltsa.py        душа Ильи целиком, как её видит модель
  proverka_mostika.py       фундамент: магик в масках
  proverka_pozicii.py       что лежит в позиции (слепок стола)
  proverka_iskry.py         мозг Искры: цел ли, отдаёт ли descent

GRONDHEIM_CITY/Биржа/                     ← данные квартала
  цеха/
    торговый_хаос/
      manifest.json                        Закон Картриджа: слоты, роли, здание
      слоты/A0{1,2,3,4,6,7,8}/
        промпт.md, знания/, данные/, мозг.py   ← ВСЕ живые
    контора/
      manifest.json
      слоты/{архивариус,исполнитель}/
        промпт.md, знания/, данные/, мозг.py   ← ОБА живые

GRONDHEIM_CITY/локации/0014_EXCHANGE/     ← паспорт здания (фон кабинета)
GRONDHEIM_CITY/жители/ковчег/{Вера,Морж,...}/  ← резиденты (дом ≠ работа)
  passport.json          РОД + _charge (заряд) + Anchor_Points (ОПЫТ)
                         + Draft_Anchors (черновики, 12.07)
  маски/работа/mask.json РОЛЬ: Workshop_ID + Turbo_Role + magic (12.07)
  archive/archive.jsonl  вытесненные якоря — не в забвение

жители/dvizhok.py                         ← движок ЖИТЕЛЯ (не Биржи):
  nakryt_stol_chisto()   чтение личности без побочки
  dopisat_vyvod(pattern) два яруса: черновик → устойчивый (3 повтора)
  vdoh() / sохранить()   дыхание: заряд ±, оседает в паспорт
```

Больше НЕТ (снесено, не забыто): `studio/`, `economy/` в корне репо —
удалены Шефом целиком, все ссылки на них вычищены из живого кода.

---

## 9. Как это соотносится с Чертежом Единицы

```
РОД      — паспорт резидента ✅ ЧИТАЕТСЯ (nositel.dusha_slota)
МАСКА    — Workshop_ID+Turbo_Role+magic ✅ единственная правда пары
ХАРАКТЕР — DNA_Static ✅ РАБОТАЕТ: натура → температура головы
ПАМЯТЬ   — atlas/pnl/trading_state, живёт в РОЛИ ✅
ОПЫТ     — Anchor_Points + Draft_Anchors ✅ ПОСТРОЕНА (§5г)
           два яруса: черновик (1-2 раза) → устойчивый (3 повтора)
СТОЛ     — факты сенсоров + характер + ОПЫТ ✅ на трёх ногах
ЗАРЯД    — ✅ качается КАЖДОЙ сделкой (дыхание ≠ опыт, Гл.4.4)
СУДЬЯ    — рынок, PnL, без апелляций ✅ самый чистый судья
ИНИЦИАТИВА / ГРАНИЦА — [не строились на Бирже, вопрос открыт]
```

**Формула Чертежа впервые замкнулась на живых деньгах** — 12.07, здесь,
на Бирже. Не в теории: заряд Ильи −0.147 записан настоящим стопом,
рукой рынка, без участия человека. Вера признала, что её слово повело
его в минус.

**Порядок сборки (Гл.1.5.2, «Вася Пупкин»):** сначала РОД (ты — Илья,
вот твоя натура, вот твои оплаченные выводы), потом МАСКА («а это
стойка, за которой ты сегодня сидишь, вот её канон»). Раньше было
наоборот — 25 000 знаков роли, а человек сноской в хвосте.

**Что Биржа доказала для всего города:** нога Опыта строится не
восстановлением маятника ДНК (Гл.4.2 зовёт его НЕ-опытом), а трубой
«исход → судья → ВЫВОД СЛОВАМИ → в якоря носителя». Судья считает
КОДОМ, не LLM. Житель прочтёт свой вывод перед следующим решением — и
сможет с ним спорить. Механизм generic: `dvizhok` не знает слова
«трейдер», ключ паттерна передаёт вызывающий код. **Любой цех города
может взять эту трубу, дав свой классификатор и своего судью.**

---

---

## 10б. Урок сессии 14.07 — ТРИ КРАНА ОДНОГО КЛАССА

За сутки найдены три перекрытых крана. **Все три — одна болезнь:**

> **ОДНА СУЩНОСТЬ — НЕСКОЛЬКО ЧИТАТЕЛЕЙ/ПИСАТЕЛЕЙ. ЛЕЧИМ ОДНОГО.**

| # | сущность | сколько концов | лечили |
|---|---|---|---|
| 1 | магик резидента | 5 копий | 1 |
| 2 | запись позиции | 2 писателя (`hooks` мёртв, мозг Сергея жив) | **не того** |
| 3 | `detect_divergent_bar` | 2 читателя (`build_market_data` / `read_ao_wave_form`) | 1 |

**Третий — МОЙ, в тот же день.** Я написал урок в §10а («сначала посмотри
в код»), выкатил патч резинки — **и тут же поскользнулся на нём же**:
пропатчил `build_market_data` и забыл `read_ao_wave_form`.

**Лекарство:**
> Лечишь сущность — **найди ВСЕХ, кто её читает и пишет**. `grep` по
> имени функции/поля ДО патча, а не после. Один читатель — не работа,
> а иллюзия работы.

**И второй урок, от Шефа:**

Трижды за две сессии он останавливал меня словом, а не кодом:
- *«9 в год — это враньё, брат»* → **был баг в угле**
- *«зачем все бары пересматривать? математика же считает?»* → **Сито 1
  отдаёт горстку, разорения не было**
- *«я тормознул, что-то не то? так не было»* → **спуск ослеп от моего же
  патча**

**Чутьё Шефа на «так не бывает» точнее моих рассуждений.** Когда он
говорит «не верю цифре» — **надо не спорить, а вскрывать**.

---

## 10а. Уроки сессии 13.07 — три раза изобрёл проблему, три раза поймал Шеф

**1. «Происхождение якоря» — выдуманная проблема.**
Я написал в Академию целый раздел: у якоря нет происхождения, вторая
профессия молча сотрёт первую, нужен новый механизм. Шеф остановил:
«вроде в чертёж закладывали? метки?». Посмотрел закон — **этаж И ЕСТЬ
происхождение**. Проблему я создал сам, свалив нажитое в этаж рода.

**2. «Разорение на MEMORY_REQUEST» — выдуманная проблема.**
Я посчитал «9 агентов × 24000 баров = второй вызов на каждом» и
предложил **урезать волю жителя ради денег**. Шеф: *«зачем все бары
пересматривать? математика же считает? сам то посмотри, как всё в
бирже работает?»*. Посмотрел — **Сито 1 отдаёт горстку кандидатов**,
Совет спит почти всегда. Цена — копейки. Гадал вместо того, чтобы
открыть файл.

**3. Миграция паспортов — тоже не понадобилась.**
Собрался переселять «нажитое» из `Anchor_Points`. Разбор глазами (по
слову Шефа, вариант Б) показал: **всё это род**, просто одетый в
торговую лексику. Диск `-2` подтвердил: «ВЕЧНЫЕ КОНСТАНТЫ, не
редактировать вручную».

**ОБЩЕЕ ЛЕКАРСТВО — ОДНО:**
> **Сначала посмотри в код и на диск. Потом рассуждай.**
> Три раза подряд я строил рассуждение поверх догадки о том, как
> устроен город — и три раза догадка была неверной. Диск не спорит.

**4. Пластик прячется в галочках — и в отчётах о галочках.**
`patch_memory_request_birzha.py` первым прогоном дал **1 из 3**: второй
вызов встал у всех, а **просить умел только Илья**. Двое получили бы
механизм и никогда им не воспользовались. **Хуже пустоты.**
⇒ В патчи вшит **стоп-кран**: не сошлось по факту — **не пишу файл**.
Проверять **телом кода** (вставка в нужном методе, до `return`,
синтаксис цел), а не строчкой «✓ готово».

**5. Ложь в промпте — это IV заповедь, а не стилистика.**
Промпт говорил жителю: «твой опыт **оплачен твоими деньгами**» — и
указывал на **род**, вписанный при рождении. Не «неточная формулировка»,
а **мнение под маской факта**. Такое режется без обсуждения.

---

## 10. Уроки сессии 12.07 — не про код, про метод

Три вещи, которые стоили дороже всего и которые стоит помнить:

1. **`except: pass` — самая дорогая строка в программировании.** Четыре
   часа копали архитектуру, пока система с самого начала честно кричала
   «нет денег» — крик был заткнут одной строкой `if aid != "A01"`.
   Ошибка, которая молчит, дороже ошибки, которая падает.

2. **Домысливать вместо того, чтобы посмотреть в источник — самый
   дорогой навык Брата.** Три промаха подряд в одной сессии: слепок взят
   из `tstate` вместо `chain_data` (хотя все соседи брали правильно);
   гипотеза про `_zval` (он был исправен); глоб с угаданной глубиной
   пути. Каждый стоил Шефу прогона. Ирония: мы весь вечер строили Илье
   механизм, чтобы он не повторял ошибку трижды — и трижды повторили
   свою.

3. **Проверка должна показывать ФАКТ, а не галочку.** Мины (слипшиеся
   якоря, пустое ядро) поймал не умный анализ, а `proverka_mostika.py`,
   которая печатала живого Илью с живого диска. Зеркало врало — там
   паспорт лёг с настоящими переводами строк. Правду сказал диск.
   **Каждый кирпич обязан показывать имя, ядро, якоря, число — а не
   «OK, всё зелёно». Пластик прячется в галочках.**

---

*Обновлять этот документ при каждой новой архитектурной правке
Биржи и держать привычку сверять с живым репо перед записью факта —
снимок от 09.07 успел разойтись с реальностью настолько, что называл
живые слоты вакансиями.*

*До корня, брат.* · `шесть·проверено·до·корня`

<!-- BIRZHA_MD_TYPING_PASS_V1 -->
<!-- BIRZHA_MD_KONTORA_KARTRIDZH_V1 · 09.07 вечер: A03/A04 в слотах, контора зафиксирована -->
<!-- BIRZHA_MD_FULL_RESYNC_V1 · 11.07 день: полная пересверка с живым репо — все 9 мозгов живые,
     наследие -2 вычищено, ангуляция+рабочий ТФ переписаны по канону, 6 UI/логических
     патчей сессии, найден и задокументирован (не пофикшен) пробел _settle_positions в РЫНОК -->
<!-- BIRZHA_MD_EVENING_SESSION_V1 · 11.07 вечер: второй слой дрейфа путей (лента закрытий,
     Атлас), катастрофическая находка производительности (feed_source перечит CSV на
     каждый бар сита-1 — тестер на H1 висел ~40 мин), реверсивная пирамида/трейлинг-
     дисциплина по первоисточнику Вильямса, компас-дисциплина Авантюриста/Ганса по
     первоисточнику Котина (подтверждена автор — Александр Котин, ученик Джастин
     Уильямс-Лара). 8 патчей, часть подтверждена живыми прогонами, часть доставлена
     и ждёт проверки на диске Шефа — статус каждого см. §5в. Эдж системы честно не
     доказан: 10 сделок, 40% побед, −3.16R — нужна выборка на порядок больше. -->
<!-- BIRZHA_MD_SOUL_BRIDGE_GAP_V1 · 11.07 вечер, после патчей: найден дохлый мост
     к душе жителя (Dvizhok/grondheim_memory) — торговые мозги физически не
     зовут Dvizhok, studio.grondheim_memory не существует в новом репо, soul="" всегда,
     промт обещает ДНК, которая никогда не приходит. Решение (портировать мост или
     строить душу заново) — ОТДЕЛЬНАЯ СЕССИЯ, не патч этой. См. §7. -->
<!-- BIRZHA_MD_MOST_K_NOSITELYU_V1 · 12.07 (ночь): МОСТ К НОСИТЕЛЮ ПОСТРОЕН.
     16 патчей. Закрыт долг трёх снимков подряд («нога Опыта пуста», «мост к душе
     мёртв», «Вера/Илья — имена поверх голого LLM»). Построено: Биржа/nositel.py
     (одна дверь Роль↔Род), magic в маске (Закон Пары), два яруса якорей
     (черновик→устойчивый, порог 3 = Путь Зрелости), суд трейдера по Котину,
     суд сенсоров («опыт сенсора — работа над своими ошибками», слово Шефа),
     дыхание отдельно от опыта (Чертёж Гл.4.4), натура→температура (оживлена
     мёртвая stress_to_temperature), тумблер УЧИТЬ, приборы A06-A09.
     ПОДТВЕРЖДЕНО ДИСКОМ: заряд Ильи −0.147, Брута +0.007 — записаны настоящими
     сделками. Илья опирается на свой опыт вслух. ФОРМУЛА ЧЕРТЕЖА ЗАМКНУЛАСЬ.
     НЕ ПРОВЕРЕНО ЖИВЬЁМ: суд сенсоров (прогоны встали на 402 — кончился баланс
     OpenRouter; max_tokens не задавался ВООБЩЕ, резервировался потолок модели
     65536). Снят кляп с Искры: её сбой единственный не печатался никогда. -->
<!-- BIRZHA_MD_VEDENIE_POZICII_V1 · 15-16.07: ВЕДЕНИЕ ПОЗИЦИИ ПОСТРОЕНО (§5ж),
     11 патчей. Закрыт долг §5в п.8 («реверсивная пирамида доставлена, не
     подтверждена»). Построено: STOP_INITIAL_R_V1 (R от первого стопа),
     OTLOZHKA_SPREAD_V2 (Дело 1 — вход только заявкой, спред-поправка),
     MOST_VEDENIYA_V1 (решение хозяина реально меняет позицию, не только
     табло), PAKET_PYRAMIDA_V1 (пирамида-пакет, честный R×множитель),
     REVERSE_PYRAMID_DISCIPLINE_V1 (убывающие ноги + обратная связь),
     PEREEZD_ZAYAVKI_V1 (Дело 1б — снятие/переезд заявки по структуре
     Вильямса, не по счётчику баров), PUNKT_OT_POINT_V1 (фикс на любой
     инструмент), CLOSE_TREYDERA_V1 (воля трейдера реально закрывает
     пакет), STANCIYA_NE_LICHNOST_V1 (все три промпт.md — станция, не
     личность, честная смена носителя). ПОЙМАНА И ОТКАЧЕНА СОБСТВЕННАЯ
     ОШИБКА В ТОТ ЖЕ ДЕНЬ: Лока указала точнее патча самого автора —
     TRAILING_NE_V_UBYTOK_V1 лечил призрака, откачен. YAZYK_DOLIVA_V1 —
     подтверждённая находка Локи, финальная строка промта молчала про
     ADD/MOVE_STOP во всех трёх мозгах. DIAGNOSTIKA_NONE_R_V1 — страховка
     на повтор. НЕ ПРОВЕРЕНО НА БОЛЬШОЙ ВЫБОРКЕ: все патчи подтверждены
     синтаксисом/числами/малыми прогонами (15-30 срабатываний), честный
     эдж системы (сотня+ сделок) — следующий шаг. -->
<!-- BIRZHA_MD_VECHER_16_17_V1 · 16-17.07 вечер: три бага найдены на первом
     большом живом прогоне (§5з). ENTRY_NE_SLIPAETSYA_V1 (вход трейдеров
     слипался в один — моя ошибка в OTLOZHKA_SPREAD_V2), POINT_NE_OPREDELEN_V1
     (NameError на каждом вызове, найден при проверке фикса первого).
     ARKHIV_KAK_INFORMACIYA_V1 (Архив подключён как вводная, не приказ —
     слово Шефа). ARKHIV_SIGNATURA_ISHODA_V1 подтверждён на живых данных:
     94/94 закрытых записей были без сигнатуры, чинено и проверено —
     Архивариус впервые увидел исход. PAMYAT_DVA_BAGA_V1 (второй вызов
     после MEMORY_REQUEST падал у Брута/Василия — старый долг с 12.07,
     не сегодняшний). Инструменты: proverit_atlas.py (инспектор),
     ochistit_atlas.py + KNOPKA_OCHISTKI_V1 (кнопка в кабинете).
     ГЛАВНЫЙ ОТКРЫТЫЙ ДОЛГ — НЕ КОД: архитектурный перекос «Сито 1»
     структурно обделяет Василия (нет аналога отложки для его момента).
     Диагноз Шефа дословно: «у нас самый дельный спит». Решение отложено
     до свежей головы — не конец долгого дня. Большой честный прогон
     (EURUSD H12, цель 100) подтвердил живое ведение (позиция +16.46R,
     трейлинг прогрессивный, реальная доливка) но был прерван дважды
     сетевым зависанием — не досчитан до конца, следующий шаг сессии. -->
<!-- BIRZHA_MD_VASILY_ZASADA_I_KANON_V1 · 17-18.07 (ночь): §5и. Патч §5з.8
     (VASILY_WATCH_V1/VASILY_ZASADA_V1/VASILY_ISP_WATCH_V1) построен и
     применён Шефом без несовпадений — но живой прогон показал: Василий
     не заговорил WATCH. Найден настоящий корень: wave_1_validated Моржа
     привязан к t1_status=CONFIRMED, а спуск Искры (_descend) не имеет
     ветки в CONFIRMED — условие структурно недостижимо, дело было не в
     промпте Василия. Разбор с Шефом и Локой + первоисточники (Фрактал,
     Волновой принцип Эллиотта, канон 100-140 баров, рисунок Шефа)
     сложились в чертёж: три станции — три точки ОДНОЙ волны в цепи
     (Искра/Авантюрист на развороте конца волны C → Ганс/Брут на первом
     фрактале после этой точки → Василий на откате волны 2 от ЭТОГО
     фрактала, вход в волну 3). Найдены и НЕ починены три точных адреса:
     detect_fractals (отбор без привязки к точке разворота), Морж
     wave_1_validated (заменить на факт закрепления Брута), _descend
     (критерий остановки сигнальный, должен быть арифметическим — канон
     фокусного окна 100-140 баров). НЕ ПОЧИНЕНО — архитектура калибра
     Моста Ведения или крупнее, следующая сессия, свежая голова + Лока. -->
<!-- BIRZHA_MD_KOMPAS_NE_VOROTA_V1 · 18.07 (весь день, §5к-5п): шесть частей
     одной долгой сессии. §5к/5л: чистый разбор канона в песочнице, три
     фазы Искра→Ганс/Брут→Василий как одна цепь, черновая линейка длины
     движения («царь-цена», окно 200 баров — позже выброшена в §5о).
     §5м: числа частоты сигналов разошлись (67/год самоделкой vs 2-4/17
     лет настоящим детектором) — попутно найден баг `senior_timeframe`
     (не туда округляет H8/H12, весь день сверка шла с захардкоженным
     H4→D1). §5н: черновой разбор картинки Котина — гипотеза «Искра
     ловит ОБА конца цикла» (на следующем заходе, §5о, признана
     ошибочной). §5о: ШЕФ ВЫПРАВИЛ КАНОН НАПРЯМУЮ — Искра ловит один
     конец волны C, не два; компас — ориентир на столе (как Аллигатор/
     AO), не жёсткие ворота «И» (объясняет провал чисел §5м — ворота
     выкашивали 87% честных точек); регламент лесенки — ОДИН этаж
     вверх, не дальше (снимает и баг H8/H12 из §5м — та ветка кода
     больше не используется); царь-цена выброшена, замена — измерение
     от пересечений нуля AO (`izmerit_ot_nulya_ao.py`); строгая проверка
     структуры горб-3→ноль-4→дивер-5 (`proverit_strukturu.py`) даёт
     устойчивую ~1/3 годных кандидатов на любом активе/этаже (XAU/EUR ×
     H4/H1/M30); окно 100-140 подтверждено НЕ фильтром (прирост 0-15
     п.п., статистический шум на части клеток) — идёт в код как факт
     (`dlina`+`struktura_chitaetsya`), не порог. Частота без ворот
     компаса на XAUUSD H4: 11.5/год — попадание в ориентир 10-15/год.
     Всё проверено ТОЛЬКО в песочнице, к репо не применено на этом
     заходе. §5п: ЭТИ ВЫВОДЫ ПРИМЕНЕНЫ К РЕПО ШЕСТЬЮ ПАТЧАМИ, ПРОВЕРЕНЫ.
     `patch_kompas_ne_vorota` (жёсткие ворота компаса сняты в _descend
     Искры — было 2 события/17 лет с воротами, стало 15 без),
     `patch_kompas_dostavka_treyderam` (закрыта тихая дыра — трейдеры
     видели эхо своей же точки под именем «компас», не независимый
     факт старшей воды), `patch_iskra_wave_measure` (измерение
     волновой структуры вживлено в williams_core.py, проверено
     регрессией на шести живых прогонах дня), `patch_wave_measure_
     dostavka` (доставка тем же маршрутом, что компас),
     `patch_dnevnik_bez_budushchego` (НАЙДЕН И ПОФИКШЕН баг «дневник
     заглядывает в будущее» — воспроизведён на игрушечном примере с
     теми же датами, не гипотеза), `patch_strazh_bez_chernovika`
     (убран мёртвый черновик `uslovie_otkat_do_urovnya`, отменённый
     ещё в §5к). Живой тестер EURUSD H4: 9/10 DETECTED, три ордера,
     компас/структура доехали до голоса Искры и до trading_state.json.
     Пересказ Локи про Котина (§5м) по-прежнему НЕ подтверждён
     независимо — регламент §5о с ним лишь случайно совпал по сути.
     Долг Василия (§5и) — по-прежнему НЕ ПОЧИНЕН, три адреса a/b/c
     из §5и актуальны без изменений, следующая крупная стройка. -->
<!-- BIRZHA_MD_SESSIYA_19_07_V1 · §5р: ревизия трёх адресов §5и —
     ни один не был тем, чем казался (a: Ганс не зовёт detect_fractals
     вообще; b: подтверждено, wave_1_validated — мнение LLM, не код;
     c: _descend уже арифметический, закрыт раньше). Настоящая причина
     молчания Василия — нет своего органа: наследовал этаж Искры
     напрямую, окно там для его волны 1 всегда не в фокусе. Разбор
     фрактальности (три витка путаницы Брата, поправлен Шефом): Вася —
     разворотник как Искра, но внутри её волны 1; опора — ангуляция НА
     СВОЁМ этаже, не пасть чужого. ПРИМЕНЁН patch_vasya_svoy_razvorot
     → VASYA_SVOY_RAZVOROT_V1 (A08/мозг.py, own_wave через step_down,
     тот же read_ao_wave_form, окно 120, без правок ядра). По пути
     проверки числом (schetchik_vasya) НАЙДЕНА структурная дыра ядра —
     _ao_divergence_at_bar обрывала поиск дивергенции на первом же
     неподходящем экстремуме (return вместо continue), била по Искре И
     Василию разом. ПРИМЕНЁН patch_ao_divergence_glubzhe →
     AO_DIVERGENCE_GLUBZHE_V1 (williams_core.py). Замер: ao_divergence
     8.5%→48.8% от кандидатов, bdb_strong 1.7%→7.8% (EURUSD D1, 2941
     бар). Частота после патча (~39/год H4) подтверждена Шефом на
     вскидку как разумная. ГЛАВНАЯ НОВАЯ НАХОДКА (НЕ ПОЧИНЕНО, крупнее
     §5и): council.wake_council — снимок ОДНОГО бара, не цепь во
     времени. Тестер будит полный Совет только на барах-кандидатах, где
     У ИСКРЫ прямо сейчас свежий сигнал (Сито-1/Сито-2); живой режим —
     только по клику РЫНОК, тоже один бар, run_live_council в фоне —
     заглушка, Совет не зовёт вовсе. Ганс/Брут/Вася НЕ СПРАШИВАЮТСЯ на
     барах, где их станции реально наступают (дни спустя точки c), если
     на этих барах у Искры нет СВОЕГО параллельного всплеска — её
     сигнал транзитный. Три станции канона (c→1→2) архитектурно сжаты в
     один момент вместо цепи. Нужны новые ворота: Совет должен ПОМНИТЬ
     найденную точку c (уже в шине) и будить нижестоящих на
     последующих барах, а не требовать от Искры каждый раз заново
     подтверждения. Калибр правки — не меньше COUNCIL_BY_DESCENT_V1,
     трогает фундамент council.py. Побочно: долг «автономия моделей»
     уточнён — не ДНК-автоматика (Autonomy_Level в паспорте не
     подключена никуда), а ручной селектор как у Брата (MODELS_CATALOG
     precedent в ui_brat.py и старой студии) — Шеф выбрал вручную,
     код не написан. Долг §5и формально ЗАКРЫТ (не так, как думали);
     новый долг (ворота Совета) — следующая крупная стройка. -->

## 5р. Сессия 19.07 — ДОЛГ §5и ЗАКРЫТ (не так, как думали), НАЙДЕНА
##     СТРУКТУРНАЯ ДЫРА В ЯДРЕ, ВСКРЫТА БОЛЬШАЯ ДЫРА В ВОРОТАХ СОВЕТА

*Продолжение §5и/§5к-5п. Начато с ревизии трёх адресов a/b/c —
закончилось патчем ядра, которого никто не планировал, и находкой,
которая переопределяет весь порядок работы Совета.*

### 1. Ревизия трёх адресов §5и — ни один не подтвердился как был описан

Читка живого кода (не песочница — репо как есть):
  - **a) `detect_fractals`** — Ганс её вообще не зовёт. Он читает
    готовые `md["fractals"]["last_up"/"last_down"]` из ядра и сравнивает
    с `teeth`. Функция отбора без привязки к точке разворота — не то,
    что чинить: привязки там и не требовалось, Ганс работает иначе.
  - **b) `wave_1_validated`** — подтверждено: Морж не считает волны,
    значение приходит из JSON-ответа LLM, не из кода. Условие
    `t1_status=CONFIRMED` НЕ существует нигде в мозге Моржа — диагноз
    §5и §4 был про несуществующую связку. Пластик (мнение LLM = факт)
    остаётся, но не там, где искали.
  - **c) `_descend`** — уже арифметический, не сигнальный. Патч
    `ISKRA_WAVE_MEASURE_DOSTAVKA_V1` (см. §5п) это уже сделал: `dlina`
    и `struktura_chitaetsya` считаются и доставлены трейдерам. Долг c
    закрыт РАНЬШЕ этой сессии, просто не был отмечен закрытым.

Настоящая причина молчания Василия — другая: у него не было
СОБСТВЕННОГО органа зрения. Он наследовал `iskra_tf` НАПРЯМУЮ (тот же
этаж, что Искра), и его окно на этом этаже слишком мелкое для отката
волны 1 — `bdb_dir` там почти всегда `None` не потому что разворота
нет, а потому что окно снято не в фокусе (§3 канона: короче 100-140
баров — «лупа», ложные пики или их отсутствие).

### 2. Фрактальность — ключ, три витка путаницы Брата, поправлен Шефом

Разбор с картинкой волны (та же, что в §5к/5н, ABC-коррекция →
1-2-3-4-5): Василий — РАЗВОРОТНИК, как Искра, но внутри волны 1 Искры.
Брат трижды путал масштабы при разборе:
  1. Принял компас Искры за «работу от волны 5» — неверно, компас и
     точка разные механизмы, оба на месте (детальный разбор
     `read_ao_wave_form`).
  2. Предложил спуск на этаж ниже Искры (`step_down`) — верно
     угадано, но обосновал неправильно (искал «долгоживущий фрактал
     после пробоя» вместо самоподобия).
  3. Построил тест опоры «в пасти РОДИТЕЛЬСКОГО этажа» (Искры) —
     Шеф поправил: пасть/ангуляция — ОДИН И ТОТ ЖЕ факт, увиденный с
     разных этажей. На своём этаже Василий видит ангуляцию (отрыв),
     это и есть его опора — сверять с чужой пастью не нужно.

Правило пятёрки (§4 канона, Уильямс): бары — язык хаоса, не дни/часы.
Окно 120 баров несёт одну и ту же волновую нагрузку на любом этаже —
спуск на ступень ниже не «портит» масштаб, это и есть фрактальное
самоподобие буквально.

### 3. ПРИМЕНЁН патч: VASYA_SVOY_RAZVOROT_V1 (не песочница — в репо)

`A08/мозг.py`: новая функция `_read_vasya_wave(symbol, iskra_tf)` —
`step_down(iskra_tf)` → `pull_bars` → `build_market_data` → тот же
`read_ao_wave_form`, окно 120, БЕЗ правок ядра. Кладёт `own_wave`
(`bdb_dir`/`bdb_price`/`dlina`/`struktura_chitaetsya`) в стол Василия
рядом с `anchor`, отдельно от чужих полей (`hans.fractal_price` и
т.п.). Промпт получил объяснение БЕЗ волнового словаря (§6.2/§8 —
сигналы ВЫХОДА, не входа — чтобы модель не спутала свой разворот с
сигналом закрытия чужой пирамиды). Патч-скрипт прогнан Шефом, маркер
подтверждён на диске в репо (не только в песочнице).

### 4. НАЙДЕН И ПРИМЕНЁН патч ядра: AO_DIVERGENCE_GLUBZHE_V1

Проверка глаза Василия числом (`schetchik_vasya.py`, история
EURUSD, все этажи) дала подозрительно низкую частоту опоры (~4% из
512 разворотов). Разбор увёл по ложному следу («пасть родительского
этажа» — см. п.2.3), но по пути вскрылась настоящая структурная дыра —
НЕ в станции Василия, а в общей функции `_ao_divergence_at_bar`
(`williams_core.py`), которую использует Искра для СВОЕЙ точки (не
компаса) и Василий через тот же путь:

```python
for k in range(i - 2, 1, -1):
    if (bars[k]["low"] < bars[k-1]["low"] and ...):
        ao_k = ao_series[k]
        if ao_k is None or ao_k >= 0:
            return False              # ← обрыв на ПЕРВОМ найденном
                                       #   экстремуме, не ищет дальше
        return bool(...)
```

Цикл искал дивергенцию только против БЛИЖАЙШЕГО локального минимума
цены назад по истории — если знак AO там не подошёл, поиск обрывался
сразу, хотя дальше в истории мог стоять честный экстремум с правильным
знаком. Замер до/после (`voronka_bdb.py`, EURUSD D1, 2941 бар):
`ao_divergence` 8.5% → 48.8% от кандидатов, `bdb_strong` 1.7% → 7.8%
(18 → 82 находки на том же окне). Дыра была структурной, не редкостью
рынка.

Патч: `return False` внутри циклов (BULL и BEAR) → `continue` — поиск
идёт дальше по истории, пока не найдётся экстремум с правильным знаком
или не кончится диапазон. Маркер `AO_DIVERGENCE_GLUBZHE_V1` подтверждён
на диске в `williams_core.py`. Бьёт по ОБОИМ агентам одинаково — это не
адрес b/c из §5и, это независимая находка того же калибра, что
`REZINKA_DOBIVKA_V1` в прошлых сессиях (дыра ДО патча = 0 находок на
1048 кандидатах при отсутствующей `lips_series`; эта дыра — тот же
класс ошибки, обрыв поиска раньше времени).

### 5. Частота после патча — в пределах разумного (Шеф подтвердил на глаз)

Первый счёт событий (без дедупликации по «рождению» сигнала, каждый
истинный бар отдельно) дал завышенные числа (~39/год H4, ~168/год H1);
проверка дедупликацией (переход False→True) показала: числа почти не
изменились (1271→1247 на H4) — сигналы и так были в основном
одиночными, не слипались в серии. Шеф подтвердил на вскидку: 100-140
баров = одна структура, на H4 это ~12-15 окон в год, 2-3 события на
окно в обе стороны — тот же порядок величины, что и замер. Совпадение
достаточное, тревоги нет.

### 6. БОЛЬШАЯ НАХОДКА, НЕ ПОЧИНЕНО: ворота Совета — снимок момента,
###    не цепь во времени

Вопрос Шефа в конце сессии («между Искрой и Консерватором целая волна,
время проходит — а они разом работают?») вскрыл то, что все предыдущие
проверки маскировали числом, а не архитектурой.

Проверка `council.py :: wake_council()` — вызовы СТРОГО последовательны
(простой `for`, без `async`), порядок верный (сенсоры до трейдеров,
Морж до Ганса внутри сенсоров, зависимости учтены правильно). НО:

  - **Тестер** (`tester_express.py`): Сито-1 (чистое ядро, без модели)
    ищет по всей истории бары, где у САМОЙ ИСКРЫ прямо сейчас есть
    `bdb_strong`/`bdb_dir` — это кандидаты. Сито-2 будит ПОЛНЫЙ Совет
    ТОЛЬКО на этих кандидатах. Между кандидатами — тишина: только
    `_settle_bar`/`_vesti_poziciyu` (ведение уже открытой позиции).
    Ганса/Брута/Василия НЕ СПРАШИВАЮТ на барах между кандидатами.
  - **Живой режим**: `run_live_council` в `hooks.py` — ЗАГЛУШКА
    (собственный комментарий: «безопасная заглушка… подключение
    прогона цепочки — следующим заходом»). Она даже не зовёт
    `council.wake_council`. Настоящий Совет живьём запускается ТОЛЬКО
    кнопкой `📡 РЫНОК` (`market_dispatch` → `council.wake_council`
    ОДИН раз, на текущем баре, в момент клика). Никакого автоматического
    опроса по каждому новому бару в фоне не существует.
  - **Ворота внутри `wake_council` одинаковы в обоих режимах**: гейт на
    `descent.found` — свежем сигнале Искры. Если точка c уже найдена и
    ждёт своего фрактала через N баров — на баре, где фрактал реально
    пробивается, Искра, скорее всего, СВОЕГО свежего сигнала уже не
    имеет (её сигнал транзитный, живёт 1-несколько баров — см. п.4), и
    Совет туда попросту НЕ ПРОСЫПАЕТСЯ. Ганса на этом баре никто не
    спрашивает — не потому что у него нет фрактала, а потому что его
    вообще не позвали.

Это не баг одной строки — три станции канона (c → 1 → 2, дни между
ними на D1) архитектурно сжаты в ОДИН снимок одного бара вместо цепи
во времени. Объясняет часть того, почему Василий молчал чаще
ожидаемого даже после патча его собственного глаза: даже когда его
`own_wave` находит разворот, до этого бара Совет может просто не
дойти, если у Искры на нём нет своего параллельного всплеска.

СТАТУС: НЕ ПОЧИНЕНО. Требует нового устройства ворот — Совет должен
ПОМНИТЬ уже найденную точку c (она уже лежит в шине как
`found_timeframe`/`zero_point_price`) и продолжать будить нижестоящих
на последующих барах, пока точка жива, а не требовать от Искры
каждый раз заново подтверждать разворот. Калибр правки — не меньше
`COUNCIL_BY_DESCENT_V1`, трогает `council.py` в фундаменте. Решение
и код — следующая сессия, свежая голова.

### 7. Побочный итог: автономия моделей — не про ДНК

Уточнение долга «автономия моделей агентов»: в Бирже выбора модели
нет вообще (`llm.py:chat()` не принимает параметр `model`, жёстко
висит на `OPENROUTER_MODEL`). Но прецедент уже есть в двух местах —
`Брат/ui_brat.py` (`MODELS_CATALOG` + `ui.select`, ручной выбор,
`state["model"]`) и в старой студии (`-2/studio/cabinet/ui_cabinet.py`,
тот же паттерн). Это НЕ автоматика по ДНК (`Autonomy_Level` в паспорте
существует, но используется только текстом в душе — не подключена
никуда, как температура была до `NATURA_V_TEMPERATURU_V1`). Шеф выбрал:
пока вручную, один общий селектор как у Брата. НЕ СДЕЛАНО — следующий
заход: `model` в `chat()`, `MODELS_CATALOG` + `ui.select` в `ui_torg.py`,
проброс в девять мозгов.

### 8. Патчи и разведочные скрипты этой сессии

ПРИМЕНЕНЫ К РЕПО (маркеры подтверждены на диске):
  - `patch_vasya_svoy_razvorot.py` → `VASYA_SVOY_RAZVOROT_V1`
    (`A08/мозг.py`)
  - `patch_ao_divergence_glubzhe.py` → `AO_DIVERGENCE_GLUBZHE_V1`
    (`williams_core.py`)

РАЗВЕДОЧНЫЕ (не патчи, для будущих проверок, не в репо, у Шефа
локально): `proverka_vasya_wave.py`, `schetchik_vasya.py` /
`schetchik_vasya2.py` / `schetchik_vasya3.py` (три версии — v1 мерил
криво по шагу, v2/v3 — сравнение пасти на разных масштабах, обе
признаны концептуально мимо после разбора фрактальности, п.2.3),
`voronka_bdb.py` / `voronka_bdb2.py` (воронка отсева по слоям —
именно она нашла адрес `AO_DIVERGENCE_GLUBZHE_V1`), `razvedka_pasti.py`
(не запущен, снят с повестки после п.2.3).

Долг §5и формально ЗАКРЫТ — не патчем трёх адресов a/b/c (два из
них оказались не тем, чем описаны), а патчем собственного органа
Василия и независимой находкой в ядре. Новый долг открыт п.6 —
калибром не меньше самого §5и.

<!-- BIRZHA_MD_SESSIYA_20_07_V1 · §5с: продолжение §5р — ворота Совета
     ПОЧИНЕНЫ (не только идея, код проверен на живых прогонах), калибровка
     доведена до цифр, найдена и починена цепочка из шести самостоятельных
     багов на пути, вскрыт новый архитектурный долг (точка перерождается
     чаще, чем доживает до Б/В), заложен канон следующей стройки (ноги
     зигзага A-B-C). Порядок патчей (все идемпотентны, применены и
     проверены Шефом на диске): TWR_BOLSHOY_PALEC_V1 (williams_core.py —
     Ритм 5/13/34 SMA close + Большой палец Авантюриста) →
     TOCHKA_ZHIVA_V1 (hooks.py — proverit_tochku, точка живёт между
     барами) → ISKRA_ALIVE_V1 (A01/мозг.py — alive=True при DETECTED) →
     COUNCIL_GATE_TROYNOY_V1 (council.py — три триггера: спуск/фрактал
     Ганса/Большой палец) → SITO_SLIYANIE_V1 (tester_express.py — Сито-1
     и Сито-2 слиты в один хронологический проход, "слияние·сит·разрешено"
     от Шефа+Локи) → CURSOR_FIX_V1 (баг Брата: state["cursor"] потерян при
     слиянии, Искра внутри спуска видела только warmup-бар всю сессию —
     найден по 53 подряд NOT_FOUND на живом прогоне) → TOCHKA_LOG_V1
     (диагностика: печать причины смерти/подпитки точки) →
     TOCHKA_NAPRAVLENIE_V1 (proverit_tochku отдаёт направление точки
     наружу) → TRIGGERS_SINHRON_V1 (найдено наблюдением Шефа за
     картинкой c→1→2: Триггер Б/В срабатывал на пробое В ЛЮБУЮ сторону,
     не сверяя с направлением точки — теперь сверяет, LONG/SHORT↔BULL/BEAR)
     → KALIBROVKA_POROGA_V1 (ТЗ Студии по факту с золота: средняя жизнь
     точки 2.3 бара, TWR убивал 387/500 смертей — калибровка: слом строго
     по Close не по тени, TWR требует 3 бара нейтрали подряд не 1;
     на золоте после калибровки жизнь точки выросла 2.3→8.3 бара, доля
     времени с живой точкой 4.5%→16.6%) → ZAPRET_DUBLYA_V1 (найдено
     трассировкой реального прогона: Брут/Авантюрист получали APPROVED
     дважды подряд, пока первая заявка ещё PENDING — старая защита
     смотрела только на status=="OPEN"; на EURUSD 2005+/20 сигналов итог
     изменился с 9 сделок/-3.31R/УБЫТОЧНАЯ до 4 сделок/+0.14R/PF 1.13,
     остальные 5 строк были фантомными дублями) → KOMPAS_PROSTOY_V1
     (найдено: feed_config.json не существовал в репо вообще —
     _start_timeframe тихо возвращала fallback=рабочий ТФ, компас читал
     ТЕ ЖЕ бары, что и точка; ПЕРВАЯ версия патча KOMPAS_DINAMICHESKI_V1
     ОТМЕНЕНА Братом до применения — она трогала _start_timeframe
     напрямую и сломала бы ISKRA_WORKING_TF_FIRST_V1 (та же функция
     непреднамеренно кормила три разные роли: этаж компаса/этаж поиска
     точки/старт спуска). Верная версия: НОВАЯ отдельная пара функций
     (_macro_timeframe — 2 этажа вверх по _TF_LADDER из mt5_feed.py,
     _read_alligator_on — простой замер Аллигатора), _compass_from
     переписан с комплекса дивер+якорь+пересечение нуля на простое
     Губы/Зубы/Челюсть — предложение Шефа "глянула тренд и всё", working-
     tf-first НЕ тронут). ПРОВЕРЕНО на живом прогоне EURUSD 2010-2012,
     24 сигнала: компас реально заговорил (BULL/BEAR вместо вечного None).
     НОВАЯ НАХОДКА, НЕ ПОЧИНЕНА (вскрыта вопросом Шефа "почему трейдеры
     не работают эстафетой во времени"): реальная Искра через спуск по
     ВСЕЙ лесенке (не только рабочий этаж, как думал бесплатный счётчик)
     подтверждает точку в 85% обращений (77/90 DETECTED на живом прогоне),
     не в ~2%, как предполагал count_triggers.py. ISKRA_ALIVE_V1 при
     КАЖДОМ DETECTED безусловно перезаписывает точку заново (даже если
     новая точка той же стороны, что уже живая) — точка не успевает
     дожить до Триггера Б/В, эстафета c→1→2 физически не может
     произойти. Патч не написан — Шеф остановил (СНАЧАЛА РАЗБИРАТЬСЯ,
     НЕ КОСТЫЛИ), увёл разговор глубже. ГЛАВНЫЙ ИТОГ СЕССИИ: по вопросу
     Шефа "почему Искра вообще просыпается во флэте" (скриншоты
     EURUSD H4/H12, явный флэт 04-08.01.2010, три пробуждения подряд, ни
     одно не должно было случиться) — дошли до корня: у системы вообще
     нет понятия "волна C уже была", разворотный бар ищется в вакууме,
     без проверки, что ему предшествовала настоящая структура A-B-C.
     Канон следующей стройки согласован с Локой и Шефом ПОЛНОСТЬЮ:
     нога = фрактал вне пасти Аллигатора, СТАРТ ноги A требует
     предварительного настоящего раскрытия пасти (bars_open уровня
     opening, не однобарный дёрг из sleeping); нога живёт, пока пасть
     открыта в её сторону, закрывается когда пасть переплетается —
     экстремум фиксируется в архив; между ногами возможна пауза
     (ожидание вне состояния); волна C подтверждается ТОЛЬКО когда
     третья нога ЦЕНОЙ пробивает зафиксированный экстремум ноги A — если
     пасть переплелась раньше пробоя, ВСЯ структура (A, B, попытка)
     стирается целиком, не архивируется; после закрытия подтверждённой
     C — весь цикл в архив, автомат сбрасывается в ИЩУ_A с нуля; счёт
     волн 1-5 после C — вне контура этого автомата, отдельный модуль.
     Пятифазный автомат состояния (ИЩУ_A → ВЕДУ_A → ЖДУ_B/ВЕДУ_B →
     ЖДУ_ПОПЫТКУ_C/ВЕДУ_ПОПЫТКУ_C → ВЕДУ_ПОДТВЕРЖДЁННУЮ_C) согласован
     словами, КОД НЕ НАПИСАН — калибр не меньше самой точки c, следующая
     стройка. Открытый вопрос на старте: порог "настоящего раскрытия"
     пасти для старта ноги A (opening как есть, или строже числом баров)
     — не решён, ждёт Шефа/Локи. -->

## 5с. Сессия 20.07 — ВОРОТА СОВЕТА ПОЧИНЕНЫ И ПРОВЕРЕНЫ НА ЖИВЫХ
##     ПРОГОНАХ; ШЕСТЬ ПОДСПУДНЫХ БАГОВ НА ПУТИ; ЗАЛОЖЕН КАНОН НОГ
##     ЗИГЗАГА A-B-C — СЛЕДУЮЩАЯ КРУПНАЯ СТРОЙКА

*Прямое продолжение §5р. Начато с самого долга §5р (ворота Совета —
снимок момента, не цепь во времени) — доведено до кода, проверено на
реальных прогонах EURUSD и XAUUSD, и по пути найдено и починено
шесть самостоятельных багов, ни один из которых не был запланирован.
Кончилось тем, что вопрос "почему Искра будит Совет во флэте" вскрыл
отсутствие самого фундамента — понятия волны вообще.*

### 1. Ворота Совета — от идеи до кода (закрытие долга §5р)

Три триггера реализованы в `council.wake_council` и в слитом цикле
`tester_express.run_tester` (тот самый ENGINE_ONE_DOOR_V1 — одна дверь
для обоих вызывающих): свежий спуск Искры (как раньше), фрактал Ганса
на живой точке, Большой палец Авантюриста на живой точке. Точка живёт
в `trading_state["iskra"]` (`alive`, `zero_point_price`,
`trend_direction`, `neutral_bars_count`), проверяется на каждом баре
кодом (`proverit_tochku`), без единого лишнего вызова модели.

Сито-1/Сито-2 слиты в один хронологический проход (`SITO_SLIYANIE_V1`)
— иначе память точки физически не могла работать: второй проход
(Сито-2) случался ПОЗЖЕ по коду, чем первый (Сито-1), но должен был
видеть состояние, рождённое ВНУТРИ первого — двух проходов быть не
могло. "слияние·сит·разрешено" — отмашка Шефа и Локи 20.07.

### 2. Цепочка находок на живых прогонах — ни одна не была на бумаге

Каждая из шести находок ниже всплыла НЕ на синтетике и не в голове —
на настоящем прогоне, с реальными голосами девяти агентов, деньгами
(токенами) и живыми числами:

1. **CURSOR_FIX_V1.** Первый живой прогон XAUUSD дал 53 NOT_FOUND
   Искры подряд. Причина — `state["cursor"]`, на который завязан
   "честный кран" (`_fake_fetch`), не обновлялся внутри слитого
   цикла (потерян при слиянии сит) — Искра ВСЮ сессию видела только
   самый первый (warmup) бар истории, независимо от того, какой бар
   реально проверялся.

2. **TRIGGERS_SINHRON_V1.** Шеф прислал схему (c→1→2 внутри ОДНОЙ
   волны) — вопрос "все ли станции смотрят в одну сторону" вскрыл:
   Триггер Б/В засчитывался на пробое в ЛЮБУЮ сторону, не сверяя с
   направлением живой точки. Починено с картой LONG/SHORT↔BULL/BEAR.

3. **KALIBROVKA_POROGA_V1.** Собственный бесплатный счётчик
   (`count_triggers.py`, написан в этой же сессии для дешёвой
   статистики без LLM) показал: средняя жизнь точки — 2.3 бара, из
   них TWR убивал почти вдвое чаще структурного слома (387 против
   91 на 24811 барах золота). Калибровка (Close вместо тени, 3 бара
   нейтрали TWR подряд вместо 1) подняла среднюю жизнь точки до 8.3
   бара, долю времени с живой точкой — с 4.5% до 16.6%.

4. **ZAPRET_DUBLYA_V1.** Живой прогон EURUSD 2005+ (первая версия,
   до калибровки) дал PF 0.269, убыточно. Трассировка по датам
   вскрыла: 5 из 9 сделок — фантомные дубли (Брут/Авантюрист получали
   APPROVED дважды подряд на одну и ту же ещё не пробитую заявку,
   потому что защита от повторного входа смотрела только на
   `status=="OPEN"`, не видела `"PENDING"`). После патча тот же кусок
   истории дал 4 сделки, PF 1.130, впервые прибыльно.

5. **KOMPAS_PROSTOY_V1.** Вопрос Шефа "почему Искра не поднимается
   проверить тренд" вскрыл: `feed_config.json`, от которого зависел
   макро-этаж компаса, в репозитории НЕ СУЩЕСТВОВАЛ вообще (проверено
   прямо в GitHub — только `billing_ledger.jsonl` в папке данных).
   Функция тихо возвращала fallback = рабочий ТФ; компас читал те же
   H4-бары, что и сама точка. ПЕРВАЯ версия патча
   (`KOMPAS_DINAMICHESKI_V1`) чуть не сломала другое: `_start_timeframe`
   непреднамеренно кормила ТРИ роли разом (этаж компаса / этаж поиска
   точки рабочим-ТФ-первым / старт спуска по лесенке) — все три
   совпадали только случайно, через отсутствие конфига. Патч отменён
   ДО применения, собран заново с отдельными, независимыми функциями
   (`_macro_timeframe`, `_read_alligator_on`), working-tf-first не
   тронут. Заодно по слову Шефа компас упрощён: не комплекс
   дивер+якорь+пересечение нуля (тот для поиска ТОЧКИ), а простое
   чтение Губы/Зубы/Челюсть — "глянула тренд и всё".

6. **Найдена, НЕ починена: точка перерождается быстрее, чем доживает
   до Б/В.** На живом прогоне EURUSD 2010-2012 Искра подтверждала
   DETECTED в 85% обращений (77/90) — счётчик без LLM предполагал
   ~2%, потому что не учитывал спуск по всей лесенке этажей вниз, не
   только рабочий этаж. `ISKRA_ALIVE_V1` при КАЖДОМ DETECTED
   безусловно перезаписывает точку с нуля, даже если новая — той же
   стороны, что уже живая. Точка не успевает дожить до фрактала/пальца
   — отсюда и наблюдение Шефа "трейдеры никогда не работают эстафетой
   во времени, всегда в одном Совете". Патч не написан.

### 3. Флэт 04-08.01.2010 — вопрос, который вскрыл отсутствие фундамента

Шеф прислал скриншоты EURUSD H4/H12 — явный, читаемый глазами флэт,
переплетённый Аллигатор, AO у нуля. За этот период Искра проснулась
трижды подряд (бары 18314, 18326, 18339) — по канону не должна была
ни разу. Разбор дошёл до корня: критерий разворотного бара — чисто
локальный (форма нескольких свечей + пара пиков AO), не спрашивает,
была ли ДО этого настоящая волна C, которую разворотный бар мог бы
завершать. Разворотник без предшествующей структуры — шум, не конец
волны.

### 4. Канон ног зигзага A-B-C — согласован полностью, код не начат

Развилка (простой ATR/процент vs гибрид Фрактал+Аллигатор) решена в
пользу гибрида — не по геометрии амплитуды, а по структуре поведения
рынка, привязано к тому, что Морж и Ганс уже считают:

- **Нога** = фрактал Ганса, подтверждённый вне пасти Аллигатора.
- **Старт ноги A** требует НАСТОЯЩЕГО предварительного раскрытия пасти
  (уровень `opening`, не однобарный дёрг из `sleeping`) — иначе первый
  попавшийся фрактал во флэте снова считался бы ногой.
- **Ведение ноги** — бегущий экстремум обновляется, пока пасть открыта
  в её сторону; закрытие ноги — пасть переплелась, экстремум в архив.
- **Между ногами** возможна пауза (ожидание) — смена стороны не
  обязана быть мгновенной, тик-в-тик.
- **Волна C подтверждается** ТОЛЬКО когда третья нога ЦЕНОЙ пробивает
  зафиксированный экстремум ноги A. Если пасть переплелась раньше
  пробоя — вся структура (A, B, незасчитанная попытка) стирается
  целиком, не архивируется как есть (не плоская коррекция/треугольник
  — просто несостоявшийся цикл, ищем заново).
- **После подтверждённой C** — весь цикл архивируется, автомат
  сбрасывается в поиск новой ноги A с нуля. Счёт волн 1-5 после C —
  вне контура этого автомата (отдельный модуль).

Пятифазный автомат состояния (ИЩУ_A → ВЕДУ_A → ЖДУ_B/ВЕДУ_B →
ЖДУ_ПОПЫТКУ_C/ВЕДУ_ПОПЫТКУ_C → ВЕДУ_ПОДТВЕРЖДЁННУЮ_C) набросан словами,
прогнан по логике вместе с Локой и Шефом. КОД НЕ НАПИСАН — Шеф
сознательно остановил на этапе согласования канона ("сначала
разбираться, не костыли"), взял паузу — день был длинный. Следующая
сессия начинает отсюда: точный порог "настоящего раскрытия" пасти для
старта ноги A ещё не выбран (обсуждались `opening` как есть или более
строгое число баров) — первое решение следующего захода.

### Итог на конец 20.07

Долг §5р ЗАКРЫТ кодом, не только идеей — двенадцать идемпотентных
патчей на диске, проверены py_compile, идемпотентностью и живыми
прогонами (не только моками). Механика c→1→2 работает end-to-end,
но эстафета во времени (станции с разных бар-дат) ЕЩЁ НИ РАЗУ не
поймана вживую — точка гибнет от собственного перерождения раньше,
чем до этого доходит. Новый, больший долг заложен и согласован: без
разметки волн A-B-C у Искры физически нет понятия "конец чего я ищу"
— калибр стройки не меньше самой точки c.

---

## 5т. Сессия 21-22.07 — КАНОН ЗАФИКСИРОВАН, УСЛОВИЕ ПРОБУЖДЕНИЯ ИСКРЫ
##     НАЙДЕНО И ВШИТО В БОЙ, СТАРАЯ ФОРМУЛА ВЫРЕЗАНА ПОЛНОСТЬЮ,
##     РЕЗИДЕНТ-МЕНЕДЖЕР ПОСТРОЕН, НАЙДЕНЫ АРХИТЕКТУРНЫЕ ДЫРЫ В СОВЕТЕ

*Самая большая сессия на сегодня. Начата с прямого разбора канона входа
с Шефом — кончилась тем, что весь путь 19-20.07 (`zigzag_core`, разметка
A-B-C) признан тупиковым для самой задачи "поймать разворот", настоящее
рабочее условие нашлось в чужом проверенном индикаторе, подключено к
живому движку и вычищено от старого без остатка, а в конце — честный
разбор того, как Совет реально будится, и что в этом неверно.*

### 1. КАНОН_ВХОДА.md — источник истины, репо сверяется с ним

Шеф зафиксировал канон письменно, целиком (`КАНОН_ВХОДА.md`, отдельно от
этого файла). Шесть столпов: рынок нелинеен, цена дышит фрактально,
индикаторы — производные следа толпы, свойство ≠ определение (строго
определён только разворотный бар, §2.4), математику считает код —
решает LLM на готовом. Волна C выстреливает ИЗ пасти, никогда не идёт
В неё (в пасть возвращается B); дивергенция AO — на внутренней 5-й волне
C, не на ней целиком; три трейдера ловят структурно разные узлы.

По канону написан `ПЛАН_АУДИТА_ЦЕХА.md` — разбор цеха против канона.
Решения Шефа на старте: план прежде, чем резать; старые данные не
трогать пока; механику Искры обсуждать отдельно.

### 2. Чистка Этапа 1 и разбор кода — подтверждён баг §0, найдена
###    готовая, но не подключённая машина

`arkhivirovat_bak.py` — 30 файлов `.bak*` (~1 МБ) в архив, не удаление.
Разбор `williams_core.py`/`мозг.py` A01 показал: живой путь `t1_status`
(`read_ao_wave_form`→`detect_divergent_bar`→`bdb_strong`) искал
разворотный бар на любом баре, без привязки к структуре — баг §0 живой,
не пофикшен, как думал канон. При этом в `zigzag_core.py` уже была
верная, гейтированная версия (`РАЗВОРОТ_НА_C`), считалась каждый бар в
проде через `hooks.proverit_nogu` — но результат только печатался в
консоль и никуда не шёл. Готовый и негодный кусок жили рядом, не
соединённые.

### 3. Проверка на истории — голый разворотник недостаточен, тренд-
###    фильтр оказался подгонкой (честный урок)

Гейтированный разворотник zigzag_core на всей истории XAUUSD H4: 96
подтверждённых концов C, 65 (68%) дали печать. Без фильтра — почти в
ноль (+3.69R золото, -27.63R EURUSD H1). Недельный компас как тренд-
фильтр дал красиво на золоте (+175R) — но, по слову Шефа, это была
подгонка под его же ручную разметку графика, не выведенное правило:
провал того же фильтра на EURUSD (-54.45R) подтвердил. Жёсткая И-связка
классических условий модуля 6.2 (разворотник+дивергенция+ангуляция) —
0% винрейт на обоих инструментах. Прямое повторение урока, который
канон уже проходил для компаса (§6: жёсткие ворота выкашивают 87-93%
честных точек).

### 4. Настоящая находка — сторонний проверенный индикатор

Шеф прислал реальные MQL4-индикаторы Necron (mqlcoder.ru, 2010):
`iDivergenceBar.mq4`, `iZone.mq4`, `iAlligatorZone.mq4`, `iBLSignal.mq4`.
Формула `iDivergenceBar`: разворотная свеча + весь бар целиком вне ВСЕХ
ТРЁХ линий Аллигатора разом (`up=max`, `dn=min`, линии со сдвигом
+8/+5/+3 — как MT4 `iAlligator` отдаёт отображаемое значение). Никакой
дивергенции AO вообще. Вход/стоп — дословно §6.2 (`Единая_торговая_
система.txt`, Вильямс+Котин): отложенный ордер на 1 пункт за экстремум
бара, стоп на 1 пункт за противоположный хвост того же бара.

Реализовано в `Биржа/test_idivergence_bar.py`. Результат БЕЗ единого
подобранного параметра, на четырёх активах/ТФ подряд:
```
XAUUSD H4 (2010-2026):    2407 сделок, винрейт 31%, +159.76R
EURUSD H1 (2010-2017):    4702 сделки, винрейт 31%, +54.49R
SP500 Daily (2010-2022):   225 сделок, винрейт 37%, +83.25R
XAUUSD M5 (2025-2026):   10837 сделок, винрейт 34%, +1092.46R
```
Одинаковый винрейт на разных инструментах/ТФ, крупные победы размазаны
по всей истории на каждом — не одна удачная сделка. Шеф подтвердил как
условие пробуждения Искры («вот, это условие ищет Искра»).

**Честная проверка спреда (важно):** реальный спред 16п на золоте режет
преимущество на 60% (H4: +159.76R→+63.37R) и на 91% на M5
(+1092.46R→+94.73R, средний R падает до +0.01 — уже в пределах шума).
На H4+ преимущество выживает, на мелких ТФ формула почти нежизнеспособна
при таком спреде. Комиссия/проскальзывание сверху не проверены.

Попытка усилить формулу конфлюэнцией (AO-дивергенция в фокусном окне
100-140 баров, Squat, Zone из `iZone.mq4`) — три честные попытки, ни
одна не улучшила базу на ОБОИХ проверяемых инструментах разом (что
работало на золоте — разваливалось на евро, и наоборот). База (сама
формула, без добавок) остаётся лучшим найденным условием.

### 5. zigzag_core — откуда он, и почему в архив

На вопрос "откуда он" — прослежен до шапки файла: согласован Шефом и
Локой 19-20.07 («Летопись §5с.4») — **собственная конструкция проекта,
не выписка из Вильямса/Котина**. Проверка: только 8.1% сигналов
`iDivergenceBar` попадают внутрь структурно подтверждённой волны C по
определению `zigzag_core` — остальные 92% срабатывают вне этой узкой
структуры, а прибыльный бэктест считался по ВСЕМ сигналам. Значит
прибыльность — не про «поимку волны C специально», это общий детектор
разворота; теория о волне C была красивым объяснением, не фактом.

Шеф вынес приговор: неверный, не чинить, в архив. Проверено вживую
заранее: `hooks.py` переживает отсутствие файла без единой правки
(`proverit_nogu` уже в `try/except`, честный no-op). `arkhivirovat_
zigzag_core.py` — Шеф прогнал успешно 22.07.

### 6. Полная вырезка старой формулы из живого кода (не только Искры)

По прямому слову Шефа («старое всё удаляй, оставь только новое») —
`detect_divergent_bar` и все её эксклюзивные помощники (`_teeth_cross_
index`, `_angulation_angle`, `_ao_divergence_at_bar`, пороги угла, лишний
`import math`) вырезаны из `williams_core.py` целиком. Поле переименовано
`divergent_bar`→`necron_bar`. Починены ВСЕ потребители, найденные грепом
по всей репе: `hooks.py` (`scan_for_feed`, `proverit_tochku`),
`tester_express.py` (дешёвый триггер, упрощён — старого деления
loose/strict больше нет физически), A01 (поле в контексте для LLM),
A06/A07/A08 (читали `tension_ratio`/`is_peak` из старого поля — на
самом деле эти данные живут в ОТДЕЛЬНОМ `rubber_band`, переключены на
него). Диагностический `voronka_bdb2.py` (изучал поведение старой
формулы) — удалён, стал бессмыслен.

Построен `proverit_necron_perenos.py` — трёхуровневая проверка
(синтаксис всех изменённых файлов / чистота от старых ссылок / живой
прогон движка против независимого эталона на реальной истории, 40
случайных проверок). Шеф прогнал на своей живой репе после переноса
патчей — **40/40, «ВСЁ ЧИСТО»**. Перенос подтверждён полностью, не на
словах.

### 7. Резидент-менеджер — работа резидента через РОЛЬ, не маску

Шеф поручил дать Архивариусу способности чистить/проверять Атлас
(бывшие `ochistit_atlas.py`/`proverit_atlas.py`) строго через единую
дверь. Разбор (`ЧЕРТЁЖ_ЕДИНИЦЫ.md`/`ЛЕТОПИСЬ_ГРОНДХЕЙМА.md`, прочитаны
целиком в этой сессии) уточнил формулировку: не через МАСКУ (лицо
момента), а через РОЛЬ (§1.5.2 — «СТОЛ+ЗНАНИЯ+ОПЫТ копит роль, не
маска»). Механизм переключения роли уже был в городе — `_slot_brain`,
но продублирован байт-в-байт в четырёх местах (долг дедупликации не
закрыт). Построен `Биржа/rezident_menedzher.py` — `vyzvat(цех, слот,
действие, **kwargs)`, честные отказы (вакансия/незнакомое действие/
падение — всегда `dict`, никогда не роняет вызывающего). Логика
перенесена в мозг Архивариуса как `pochistit_atlas()`/`proverit_atlas()`.
Старые CLI-скрипты удалены (не архивированы — явное слово Шефа).

### 8. Корень репо разобран по фактической принадлежности

Отобраны все файлы корня, касающиеся Биржи, разнесены по трём местам:
```
Биржа/ (движок):                    konec_volny_C.py, test_idivergence_bar.py,
                                     zigzag_chart.py
GRONDHEIM_CITY/.../торговый_хаос/:  proverka_vasya_wave.py, schetchik_vasya3.py,
                                     voronka_bdb2.py (позже удалён, см. §6)
GRONDHEIM_CITY/Биржа/ (картридж):   ochistit_pozicii.py, otchet.py, razvedka_slepka.py
```
`run_tester.py` нарочно остался в корне — его смысл: не набирать
кириллицу «Биржа» в PowerShell. Построена аналогичная обёртка
`proverit_signal.py` для `test_idivergence_bar.py` (та же болезнь, тот
же приём). Пять из семи перенесённых файлов требовали правки путей
внутри (были написаны в расчёте «лежу в корне репо») — поправлены на
`__file__`-привязку, проверены `py_compile` и живым запуском с нового
места. Удалены (по прямому слову Шефа, не архивированы):
`ochistit_atlas.py`, `proverit_atlas.py`, `schetchik_vasya.py`,
`schetchik_vasya2.py`, `voronka_bdb.py`, `count_triggers.py` — все
превзойдены новыми версиями или ролью Архивариуса.

`test_idivergence_bar.py` дополнительно доработан: символ/point теперь
угадываются по имени файла (можно не указывать), добавлен настоящий
флаг `--spread` (в пунктах, реальная цена исполнения хуже уровня
триггера) — Шеф уже гоняет им проверки на разных инструментах/ТФ сам.

### 9. Найдены архитектурные дыры в том, как Совет реально будится —
###    КОД ЕЩЁ НЕ НАПИСАН, только разбор

Прочитан `council.py` целиком. Порядок будильника жёсткий: Искра →
[Морж, Паникёр, Ганс] → Архивариус → [Брут, Авантюрист, Консерватор
ВСЕ ТРОЕ РАЗОМ] → Исполнитель. Ворота — либо свежий спуск Искры, либо
(если спуска нет) дешёвая проверка `_deshyovaya_proverka_tochki`: жива
ли точка И (фрактал Ганса пробит ИЛИ Большой палец Авантюриста) в ту же
сторону.

**Три находки из разбора с Шефом, шаг за шагом:**

**а) Фрактал-триггер сейчас будит НА ПРОБОЕ, а должен — на ПОДТВЕРЖДЕНИИ.**
`_hans_breakout()` ловит момент, когда `close` уже ПЕРЕСЁК уровень
фрактала — к этому моменту, по канону (§6.1), вход уже должен был
случиться механически (отложенный ордер, стоявший заранее). Шеф:
«образование фрактала это сигнал… тогда выставляется ордер… а ордер
он самый последний у них срабатывает». Верно — нужен триггер на
МОМЕНТЕ ПОДТВЕРЖДЕНИЯ истинного фрактала (когда исполнились оба правых
бара классической пятибарной структуры Вильямса, `bar_index_фрактала +
lookback == текущий последний бар`, и фрактал вне пасти) — раньше, пока
есть время поставить отложку, а не постфактум.

**б) На этом триггере должны будиться сенсоры, но НЕ все три трейдера.**
Разобран мозг Брута (A06): он явно читает вердикты Моржа
(`morj_status`, `wave_1_validated`, `tension_peak`), Паникёра
(`panic_phase`, `crowd_sentiment`) И Ганса (`fractal_valid`) с общего
стола (`trading_state`) — не только сырые данные, а именно ЧУЖИЕ
СУЖДЕНИЯ, персистентные между барами. Значит если сенсоров не разбудить
свежо — Брут увидит либо пусто, либо протухший вердикт с прошлого бара
(тот самый баг Ильи 14.07, `NET_PRIZRAKOV_V1`). Но из трёх трейдеров
на фрактале нужен только Брут (это его узел, §6.1) — не Авантюрист и
не Консерватор, они будятся сейчас без разбора, всегда все трое разом.

**в) Один и тот же прибор (Аллигатор) означает разное в разных узлах —
и не для всех уже посчитано правильно.** У Искры — отрыв от всех трёх
линий (есть, `detect_necron_bar`). У Ганса — Челюсть как порог, фрактал
выше/ниже неё (есть, отдельная верная логика). У Васи (A08, конец
волны 2, §6.3 — зеркальный узел, РБ формируется ВНУТРИ пасти, отбой)
— **дыры нет вовсе**: сейчас Вася читает ту же `rubber_band`
(дистанция/натяжение, отрыв), что и все остальные, хотя его сценарий
canonически противоположный. Нужно строить отдельно, не чинить.

Отдельно уточнено и не спутать больше: волна 2 (порядок 1-2-3-4-5) —
не то же самое, что волна C (коррекция, которую ловит Искра); волна 2
часто сама зигзаг (вложенная A-B-C меньшего масштаба) — фрактальность
канона в чистом виде, тот же узор на разных этажах. «100-140 баров»
(§3 канона) — не формула для расчёта окна под конкретную волну, а
практическое наблюдение: **любая** волна читается яснее всего, если
масштаб экрана позволяет ей занять примерно 100-140 баров — не число
для вычисления, ориентир для настройки просмотра.

**Ничего из пункта 9 не закодировано** — это чистый разбор, накоплен в
разговоре, код под три находки ещё не написан. Следующий заход должен
начаться отсюда.

### Итог на конец 22.07

Канон есть, письменный, репо сверяется по нему. Условие пробуждения
Искры найдено, подтверждено на четырёх активах без подгонки, честно
проверено на спред, и — впервые за всю историю проекта — **реально
вшито в бой и полностью вычищено от предыдущей формулы**, не осталось
двух конкурирующих кусков логики. Резидент-менеджер даёт первый
воспроизводимый образец «работа через роль, одна дверь». Корень репо
приведён в порядок по факту принадлежности. И в самом конце — начат
(не закончен) разбор того, как по-настоящему должен будиться Совет:
адресно, по узлам, с правильным моментом триггера — три конкретные
находки, ждущие кода в следующей сессии.

---

## 5у. Сессия 22.07 (вторая половина) — ФРАКТАЛ-ТРИГГЕР ДЛЯ БРУТА:
##     ЧЕСТНО РАЗОБРАН, НАЙДЕНА РАБОЧАЯ МЕХАНИКА, НО И СКРЫТАЯ
##     ХРУПКОСТЬ (КОНЦЕНТРАЦИЯ РЕЗУЛЬТАТА) — В БОЙ ЕЩЁ РАНО

*Прямое продолжение §5т. Тот же принцип, что с формулой Искры — строить
отдельным проверяемым скриптом, честно тестировать на истории, не
зашивать в `council.py`, пока не проверено. Кончилось важным уроком:
согласованность на нескольких инструментах суммой R — недостаточная
проверка, нужно смотреть распределение по времени.*

### 1. Момент триггера — подтверждение, не пробой (дважды подтверждено книгами)

Разбор с Шефом, шаг за шагом: старый `_hans_breakout` будил Совет на
ПРОБОЕ уровня фрактала (когда `close` уже пересёк его) — но по канону
(§6.1) вход должен быть отложенным ордером, поставленным ЗАРАНЕЕ, на
подтверждении. Момент подтверждения = `bar_index_фрактала + lookback`
(когда пятибарная структура Вильямса впервые становится видна — оба
правых бара закрылись). Шеф прислал два независимых конспекта по
книгам Вильямса (Trading Chaos 1995 гл.9 стр.158-161, и 2-е издание
2004 гл.11 стр.189) — оба независимо подтвердили ровно этот момент
дословно («ордер выставляется на 5-м баре, не на пробое»).

### 2. Живая точка — честно смоделирована, не приближена

Разбор мозга Брута (A06) показал: он читает вердикты Моржа/Паникёра/
Ганса с общего стола (`trading_state`), не только сырые факты — значит
сенсоры должны быть разбужены свежо, иначе Брут видит пусто или
протухшее (баг Ильи 14.07). Построена честная симуляция `proverit_tochku`
(рождение на разворотнике Necron, питание при GREEN/SQUAT той же
стороны, смерть на структурном сломе или 3 бара TWR-нейтрали) —
использованы реальные функции `compute_mfi`/TWR, не выдумано заново.
Голый фрактал-триггер без выравнивания с живой точкой — шум, ~0R
(5790 срабатываний на золоте, ни одной крупной победы). С выравниванием
— уже что-то, но три отдельных фильтра (разворотник на баре, дневной
тренд, сама живая точка) каждый порознь дали плюс на золоте и минус на
евро — тот же паттерн, что с недельным компасом Искры раньше.

### 3. «Настоящая волна 1» — спуск по лесенке ТФ, не фиксированное окно

Шеф поправил дважды за день одну и ту же вещь: «100-140 баров» (§3
канона) — не формула для расчёта, а ориентир масштаба, на котором любая
волна читается яснее всего. Правильная реализация — не мерить окно на
рабочем ТФ, а ИСКАТЬ младший ТФ (перебором по лесенке M5→M10→M15→M30→H1),
на котором отрезок «рождение точки→фрактал» реально укладывается в
100-140 баров. С этим фильтром — впервые за весь день XAUUSD и EURUSD
(оба на H4, честное сравнение одного масштаба) сошлись почти точно:
винрейт 42%/41%, средний R +0.28/+0.21.

Отдельно измерен разрыв «фрактал Ганса → конец волны 1» (следующий
противоположный разворотник): медиана 10-11 баров, но у ~25% случаев
разрыв ≤3 бара — Ганс срабатывает почти у самой вершины волны 1, вахта
Васи может начаться почти сразу вслед за входом Брута. Не конфликт (по
самой нумерации волн Брут не может войти позже Васи), но короткие волны
1 сжаты и, возможно, сами нуждаются в ещё одном спуске на меньший ТФ —
не проверено, отдельная идея.

### 4. Механика выхода — три честные попытки, ни одна не улучшила

Третья книга (конспект Локи по New Trading Dimensions 1998) предложила:
ордер не должен обрываться по таймауту, должен висеть до исполнения
(даже через откат волны 2). Проверка честно подтвердила один конкретный
пункт: снятие искусственного ограничения «ждать только до следующего
события» и разрешение висеть до 500 баров резко улучшило результат на
золоте (+13R→+662R) и не ухудшило на евро — Шеф поправил на честное
сравнение (евро тоже на H4, не на H1) — тогда: XAUUSD +662.60R (винрейт
20%), EURUSD +49.74R (винрейт 15%). Комбинация «настоящая волна 1» +
долгое ожидание разом — ХУЖЕ каждого порознь (тот же урок жёсткой
связки, что весь день) — по умолчанию в скрипте оставлено только
долгое ожидание, спуск по ТФ — опция для эксперимента.

### 5. КРИТИЧЕСКАЯ НАХОДКА — концентрация результата (правка 25)

Шеф прогнал третий инструмент (GBPUSD H4) — результат внешне такой же
согласованный (+146.84R, 152 крупных победы), но в списке бросился в
глаза кластер: 6+ сделок за две недели апреля 2002 с R от +20 до +31.
Проверка (доля лучшего 45-дневного скользящего окна от итога):
```
XAUUSD H4:  +662.60R,  лучшее окно 43% от итога (без окна всё равно +377R)
EURUSD H4:   +49.74R,  лучшее окно 339% от итога (без окна было бы -119R)
GBPUSD H4:  +146.84R,  лучшее окно 128% от итога (без окна было бы -42R)
```
**У евро и фунта весь результат держится на ОДНОМ отрезке истории** —
это не подгонка между инструментами (её прошли), это скрытая хрупкость
ВНУТРИ каждого отдельно, видимая только если смотреть распределение по
времени, не только сумму R и список крупных побед. Урок на будущее:
всегда проверять концентрацию, иначе легко принять «повезло один раз»
за «есть преимущество».

**Проверено отдельно и важно: у уже вшитой в бой формулы Искры (§5т)
той же проблемы нет** — концентрация 17-58% на всех четырёх активах,
устойчиво распределено. Хрупкость нашлась именно в новом фрактал-
триггере, не в том, что уже работает у Шефа вживую.

### 6. Три попытки починить механику выхода — все честно провалились

Гипотеза: возможно, дело в самом трендовом характере фрактального
входа — трейлинг должен и размазать результат, и защитить его. Проверено:
- **Трейлинг по фракталу** — хуже на всех: золото просело в 20 раз
  (+31R вместо +662R), концентрация ВЫРОСЛА до 102%; евро/фунт ушли в
  минус.
- **Трейлинг по Красной линии (Зубы), Stop on Close** — ещё хуже: золото
  +13R (концентрация 323%), евро/фунт ещё глубже в минус.
- **Простой пирамидинг** (долив на новом фрактале той же стороны, общий
  стоп подтягивается разом) — концентрация решена (результаты размазаны,
  -22%/-3%/-5%), но итог провалился в глубокий минус на всех трёх
  (-318R/-858R/-793R, винрейт 7-10%) — упрощение (игнорировать
  противоположный сигнал, пока пакет открыт) оказалось слишком грубым.

**Разбор Локи (естественный ретест после пробоя рушит тесный трейлинг)
— проверен числами, не принят на веру:** у крупных побед (XAUUSD, R>5)
медианный откат в первые 30 баров — 0.48R от риска, почти половина
случаев глубже 0.5R, максимум 0.99R — на волосок от исходного стопа.
Механизм реальный: тесный трейлинг закономерно убивает именно те сделки,
что становятся крупными победами. Но это объясняет только «почему
трейлинг хуже статичного стопа» — НЕ решает найденную выше концентрацию.

### Итог на конец 22.07 (весь день)

Искра — полностью готова, вшита, вычищена, проверена на живой репе.
Фрактал-триггер для Брута — механика найдена и по частям обоснована
(момент триггера дважды подтверждён книгами, живая точка честно
смоделирована, лучший найденный выход — статичный стоп с долгим
ожиданием), но целиком **не готов к бою** — скрытая концентрация
результата на 2 из 3 инструментов означает, что найденный край может
быть одной удачей, не доказанным преимуществом. Три попытки укротить
эту хрупкость трейлингом/пирамидингом честно провалились. Вася/волна 2
получил числа из первоисточников (38-62%, пять факторов), но ни разу
не протестирован. Следующий заход — аккуратный пирамидинг (без сегодняшнего
грубого упрощения) или явное решение принять риск редких трендов как
часть замысла, плюс честная проверка находок по Васе тем же методом.
